// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;

namespace BeaconAr.Data.Sales.Mappers;

public static class SalesStoredProcedureMappersRegisterer
{
    public static void RegisterMappers()
    {
        RegisterDataReaderMappers();
        RegisterSqlParameterMappers();
    }

    private static void RegisterDataReaderMappers()
    {
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.AddressSalesReferenceRow>(() => new DataReaders.AddressSalesReferenceRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.CarrierSalesReferenceRow>(() => new DataReaders.CarrierSalesReferenceRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.CustomerSalesReferenceRow>(() => new DataReaders.CustomerSalesReferenceRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.ProductSalesReferenceRow>(() => new DataReaders.ProductSalesReferenceRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.QuoteSearchRow>(() => new DataReaders.QuoteSearchRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.SalesOrderSearchRow>(() => new DataReaders.SalesOrderSearchRowDataReaderMapper());

    }

    private static void RegisterSqlParameterMappers()
    {
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.AllocateQuoteNumberParameters>(() => new SqlParameters.AllocateQuoteNumberParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.AllocateSalesOrderNumberParameters>(() => new SqlParameters.AllocateSalesOrderNumberParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.GetAddressSalesReferenceForUpdateParameters>(() => new SqlParameters.GetAddressSalesReferenceForUpdateParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.GetCarrierSalesReferenceForUpdateParameters>(() => new SqlParameters.GetCarrierSalesReferenceForUpdateParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.GetCustomerSalesReferenceForUpdateParameters>(() => new SqlParameters.GetCustomerSalesReferenceForUpdateParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.GetProductSalesReferenceForUpdateParameters>(() => new SqlParameters.GetProductSalesReferenceForUpdateParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.LockQuoteForConversionParameters>(() => new SqlParameters.LockQuoteForConversionParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.QuoteSearchParameters>(() => new SqlParameters.QuoteSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.SalesOrderSearchParameters>(() => new SqlParameters.SalesOrderSearchParametersMapper());

    }
}