// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Access.StoredProcedures;

namespace BeaconAr.Data.Access.Mappers.SqlParameters;

internal partial class GetOrCreateApplicationUserParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is GetOrCreateApplicationUserParameters instance)) return;

        AddSqlParameter(nameof(GetOrCreateApplicationUserParameters.Issuer), instance.Issuer);
        AddSqlParameter(nameof(GetOrCreateApplicationUserParameters.Subject), instance.Subject);
        AddSqlParameter(nameof(GetOrCreateApplicationUserParameters.DisplayName), instance.DisplayName);
        AddSqlParameter(nameof(GetOrCreateApplicationUserParameters.Email), instance.Email);
        AddSqlParameter(nameof(GetOrCreateApplicationUserParameters.Now), instance.Now);

    }
}