// <auto-generated/>
using BeaconAr.Domain.MasterData.Entities;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.MasterData.Mappers.DataReaders;

internal partial class CarrierViewDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CarrierView();
        if (FieldIsValid(reader, nameof(CarrierView.Id))) instance.Id = GetInt32(reader, nameof(CarrierView.Id));
        if (FieldIsValid(reader, nameof(CarrierView.Code))) instance.Code = GetString(reader, nameof(CarrierView.Code));
        if (FieldIsValid(reader, nameof(CarrierView.Name))) instance.Name = GetString(reader, nameof(CarrierView.Name));
        if (FieldIsValid(reader, nameof(CarrierView.ServiceLevel))) instance.ServiceLevel = GetString(reader, nameof(CarrierView.ServiceLevel));
        if (FieldIsValid(reader, nameof(CarrierView.TrackingUrlTemplate))) instance.TrackingUrlTemplate = GetString(reader, nameof(CarrierView.TrackingUrlTemplate));
        if (FieldIsValid(reader, nameof(CarrierView.IsActive))) instance.IsActive = GetBoolean(reader, nameof(CarrierView.IsActive));
        if (FieldIsValid(reader, nameof(CarrierView.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(CarrierView.CreatedByUserId));
        if (FieldIsValid(reader, nameof(CarrierView.CreatedByUserDisplayName))) instance.CreatedByUserDisplayName = GetString(reader, nameof(CarrierView.CreatedByUserDisplayName));
        if (FieldIsValid(reader, nameof(CarrierView.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(CarrierView.CreationDate));
        if (FieldIsValid(reader, nameof(CarrierView.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(CarrierView.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(CarrierView.ModifiedByUserDisplayName))) instance.ModifiedByUserDisplayName = GetString(reader, nameof(CarrierView.ModifiedByUserDisplayName));
        if (FieldIsValid(reader, nameof(CarrierView.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(CarrierView.ModificationDate));
        if (FieldIsValid(reader, nameof(CarrierView.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(CarrierView.RowVersion));

        return instance;
    }
}