// <auto-generated/>
using BeaconAr.Domain.MasterData.Entities;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.MasterData.Mappers.DataReaders;

internal partial class CustomerAddressViewDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CustomerAddressView();
        if (FieldIsValid(reader, nameof(CustomerAddressView.Id))) instance.Id = GetInt32(reader, nameof(CustomerAddressView.Id));
        if (FieldIsValid(reader, nameof(CustomerAddressView.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(CustomerAddressView.CustomerId));
        if (FieldIsValid(reader, nameof(CustomerAddressView.CustomerAccountNumber))) instance.CustomerAccountNumber = GetString(reader, nameof(CustomerAddressView.CustomerAccountNumber));
        if (FieldIsValid(reader, nameof(CustomerAddressView.CustomerName))) instance.CustomerName = GetString(reader, nameof(CustomerAddressView.CustomerName));
        if (FieldIsValid(reader, nameof(CustomerAddressView.AddressTypeId))) instance.AddressTypeId = GetInt32(reader, nameof(CustomerAddressView.AddressTypeId));
        if (FieldIsValid(reader, nameof(CustomerAddressView.AddressTypeCode))) instance.AddressTypeCode = GetString(reader, nameof(CustomerAddressView.AddressTypeCode));
        if (FieldIsValid(reader, nameof(CustomerAddressView.AddressTypeDisplayName))) instance.AddressTypeDisplayName = GetString(reader, nameof(CustomerAddressView.AddressTypeDisplayName));
        if (FieldIsValid(reader, nameof(CustomerAddressView.Label))) instance.Label = GetString(reader, nameof(CustomerAddressView.Label));
        if (FieldIsValid(reader, nameof(CustomerAddressView.Line1))) instance.Line1 = GetString(reader, nameof(CustomerAddressView.Line1));
        if (FieldIsValid(reader, nameof(CustomerAddressView.Line2))) instance.Line2 = GetString(reader, nameof(CustomerAddressView.Line2));
        if (FieldIsValid(reader, nameof(CustomerAddressView.City))) instance.City = GetString(reader, nameof(CustomerAddressView.City));
        if (FieldIsValid(reader, nameof(CustomerAddressView.State))) instance.State = GetString(reader, nameof(CustomerAddressView.State));
        if (FieldIsValid(reader, nameof(CustomerAddressView.PostalCode))) instance.PostalCode = GetString(reader, nameof(CustomerAddressView.PostalCode));
        if (FieldIsValid(reader, nameof(CustomerAddressView.Country))) instance.Country = GetString(reader, nameof(CustomerAddressView.Country));
        if (FieldIsValid(reader, nameof(CustomerAddressView.IsDefaultBilling))) instance.IsDefaultBilling = GetBoolean(reader, nameof(CustomerAddressView.IsDefaultBilling));
        if (FieldIsValid(reader, nameof(CustomerAddressView.IsDefaultShipping))) instance.IsDefaultShipping = GetBoolean(reader, nameof(CustomerAddressView.IsDefaultShipping));
        if (FieldIsValid(reader, nameof(CustomerAddressView.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(CustomerAddressView.CreatedByUserId));
        if (FieldIsValid(reader, nameof(CustomerAddressView.CreatedByUserDisplayName))) instance.CreatedByUserDisplayName = GetString(reader, nameof(CustomerAddressView.CreatedByUserDisplayName));
        if (FieldIsValid(reader, nameof(CustomerAddressView.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(CustomerAddressView.CreationDate));
        if (FieldIsValid(reader, nameof(CustomerAddressView.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(CustomerAddressView.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(CustomerAddressView.ModifiedByUserDisplayName))) instance.ModifiedByUserDisplayName = GetString(reader, nameof(CustomerAddressView.ModifiedByUserDisplayName));
        if (FieldIsValid(reader, nameof(CustomerAddressView.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(CustomerAddressView.ModificationDate));
        if (FieldIsValid(reader, nameof(CustomerAddressView.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(CustomerAddressView.RowVersion));

        return instance;
    }
}