// <auto-generated/>
using BeaconAr.Domain.MasterData.Entities;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.MasterData.Mappers.DataReaders;

internal partial class CustomerViewDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CustomerView();
        if (FieldIsValid(reader, nameof(CustomerView.Id))) instance.Id = GetInt32(reader, nameof(CustomerView.Id));
        if (FieldIsValid(reader, nameof(CustomerView.AccountNumber))) instance.AccountNumber = GetString(reader, nameof(CustomerView.AccountNumber));
        if (FieldIsValid(reader, nameof(CustomerView.Name))) instance.Name = GetString(reader, nameof(CustomerView.Name));
        if (FieldIsValid(reader, nameof(CustomerView.Email))) instance.Email = GetString(reader, nameof(CustomerView.Email));
        if (FieldIsValid(reader, nameof(CustomerView.Phone))) instance.Phone = GetString(reader, nameof(CustomerView.Phone));
        if (FieldIsValid(reader, nameof(CustomerView.CreditLimit))) instance.CreditLimit = GetDecimal(reader, nameof(CustomerView.CreditLimit));
        if (FieldIsValid(reader, nameof(CustomerView.PaymentTermsDays))) instance.PaymentTermsDays = GetInt16(reader, nameof(CustomerView.PaymentTermsDays));
        if (FieldIsValid(reader, nameof(CustomerView.IsActive))) instance.IsActive = GetBoolean(reader, nameof(CustomerView.IsActive));
        if (FieldIsValid(reader, nameof(CustomerView.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(CustomerView.CreatedByUserId));
        if (FieldIsValid(reader, nameof(CustomerView.CreatedByUserDisplayName))) instance.CreatedByUserDisplayName = GetString(reader, nameof(CustomerView.CreatedByUserDisplayName));
        if (FieldIsValid(reader, nameof(CustomerView.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(CustomerView.CreationDate));
        if (FieldIsValid(reader, nameof(CustomerView.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(CustomerView.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(CustomerView.ModifiedByUserDisplayName))) instance.ModifiedByUserDisplayName = GetString(reader, nameof(CustomerView.ModifiedByUserDisplayName));
        if (FieldIsValid(reader, nameof(CustomerView.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(CustomerView.ModificationDate));
        if (FieldIsValid(reader, nameof(CustomerView.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(CustomerView.RowVersion));

        return instance;
    }
}