// <auto-generated/>
using BeaconAr.Domain.MasterData.Entities;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.MasterData.Mappers.DataReaders;

internal partial class ProductViewDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new ProductView();
        if (FieldIsValid(reader, nameof(ProductView.Id))) instance.Id = GetInt32(reader, nameof(ProductView.Id));
        if (FieldIsValid(reader, nameof(ProductView.Sku))) instance.Sku = GetString(reader, nameof(ProductView.Sku));
        if (FieldIsValid(reader, nameof(ProductView.Name))) instance.Name = GetString(reader, nameof(ProductView.Name));
        if (FieldIsValid(reader, nameof(ProductView.Category))) instance.Category = GetString(reader, nameof(ProductView.Category));
        if (FieldIsValid(reader, nameof(ProductView.UnitPrice))) instance.UnitPrice = GetDecimal(reader, nameof(ProductView.UnitPrice));
        if (FieldIsValid(reader, nameof(ProductView.StockQuantity))) instance.StockQuantity = GetInt32(reader, nameof(ProductView.StockQuantity));
        if (FieldIsValid(reader, nameof(ProductView.ThumbnailUrl))) instance.ThumbnailUrl = GetString(reader, nameof(ProductView.ThumbnailUrl));
        if (FieldIsValid(reader, nameof(ProductView.IsActive))) instance.IsActive = GetBoolean(reader, nameof(ProductView.IsActive));
        if (FieldIsValid(reader, nameof(ProductView.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(ProductView.CreatedByUserId));
        if (FieldIsValid(reader, nameof(ProductView.CreatedByUserDisplayName))) instance.CreatedByUserDisplayName = GetString(reader, nameof(ProductView.CreatedByUserDisplayName));
        if (FieldIsValid(reader, nameof(ProductView.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(ProductView.CreationDate));
        if (FieldIsValid(reader, nameof(ProductView.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(ProductView.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(ProductView.ModifiedByUserDisplayName))) instance.ModifiedByUserDisplayName = GetString(reader, nameof(ProductView.ModifiedByUserDisplayName));
        if (FieldIsValid(reader, nameof(ProductView.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(ProductView.ModificationDate));
        if (FieldIsValid(reader, nameof(ProductView.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(ProductView.RowVersion));

        return instance;
    }
}