// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Sales.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class QuoteStatusHistory : EntityBase<int>
{
    public int QuoteId { get; set; }

    public int StatusId { get; set; }

    public int CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public virtual Quote Quote { get; set; } = null!;

    public virtual QuoteStatus Status { get; set; } = null!;
}
