// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Sales.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;
using Paradigm.Enterprise.Interfaces;

namespace BeaconAr.Domain.Sales.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrder : EntityBase<int, ISalesOrder, SalesOrder, SalesOrderView>, ISalesOrder, IAuditableEntity<DateTimeOffset, int>
{
    public string OrderNumber { get; set; } = null!;

    public int? SourceQuoteId { get; set; }

    public int CustomerId { get; set; }

    public int ShippingAddressId { get; set; }

    public int StatusId { get; set; }

    public DateOnly? RequestedShipDate { get; set; }

    public int? CarrierId { get; set; }

    public string? TrackingNumber { get; set; }

    public string? CustomerAccountNumberSnapshot { get; set; }

    public string? CustomerNameSnapshot { get; set; }

    public string? CustomerEmailSnapshot { get; set; }

    public string? CustomerPhoneSnapshot { get; set; }

    public string? ShippingLabelSnapshot { get; set; }

    public string? ShippingLine1Snapshot { get; set; }

    public string? ShippingLine2Snapshot { get; set; }

    public string? ShippingCitySnapshot { get; set; }

    public string? ShippingStateSnapshot { get; set; }

    public string? ShippingPostalCodeSnapshot { get; set; }

    public string? ShippingCountrySnapshot { get; set; }

    public string? ShippingAddressTypeCodeSnapshot { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public DateTimeOffset? DeletionDate { get; set; }

    public int? DeletedByUserId { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public virtual ICollection<SalesOrderLine> SalesOrderLines { get; set; } = new List<SalesOrderLine>();

    public virtual ICollection<SalesOrderStatusHistory> SalesOrderStatusHistories { get; set; } = new List<SalesOrderStatusHistory>();

    public virtual Quote? SourceQuote { get; set; }

    public virtual SalesOrderStatus Status { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
    }

    public override SalesOrder MapFrom(IServiceProvider serviceProvider, ISalesOrder model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<SalesOrderMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override SalesOrderView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<SalesOrderView>();
        serviceProvider.GetRequiredService<SalesOrderMapper>().MapTo(this, view);
        return view;
    }
    partial void ValidateEntity();

    partial void BeforeMap(ISalesOrder model);

    partial void AfterMap(ISalesOrder model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrderMapper : EntityMapperBase<int, ISalesOrder, SalesOrder, SalesOrderView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<ISalesOrder, SalesOrder>.NewConfig()
            .Ignore(entity => entity.CreatedByUserId!)
            .Ignore(entity => entity.CreationDate!)
            .Ignore(entity => entity.CustomerAccountNumberSnapshot!)
            .Ignore(entity => entity.CustomerEmailSnapshot!)
            .Ignore(entity => entity.CustomerNameSnapshot!)
            .Ignore(entity => entity.CustomerPhoneSnapshot!)
            .Ignore(entity => entity.DeletedByUserId!)
            .Ignore(entity => entity.DeletionDate!)
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ModificationDate!)
            .Ignore(entity => entity.ModifiedByUserId!)
            .Ignore(entity => entity.ShippingAddressTypeCodeSnapshot!)
            .Ignore(entity => entity.ShippingCitySnapshot!)
            .Ignore(entity => entity.ShippingCountrySnapshot!)
            .Ignore(entity => entity.ShippingLabelSnapshot!)
            .Ignore(entity => entity.ShippingLine1Snapshot!)
            .Ignore(entity => entity.ShippingLine2Snapshot!)
            .Ignore(entity => entity.ShippingPostalCodeSnapshot!)
            .Ignore(entity => entity.ShippingStateSnapshot!);
    }
}
