// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Sales.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;

namespace BeaconAr.Domain.Sales.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrderLine : EntityBase<int, ISalesOrderLine, SalesOrderLine, SalesOrderLineView>, ISalesOrderLine
{
    public int SalesOrderId { get; set; }

    public int ProductId { get; set; }

    public string SkuSnapshot { get; set; } = null!;

    public string ProductNameSnapshot { get; set; } = null!;

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal DiscountPercent { get; set; }

    public decimal? LineSubtotal { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? LineTotal { get; set; }

    public virtual SalesOrder SalesOrder { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
    }

    public override SalesOrderLine MapFrom(IServiceProvider serviceProvider, ISalesOrderLine model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<SalesOrderLineMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override SalesOrderLineView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<SalesOrderLineView>();
        serviceProvider.GetRequiredService<SalesOrderLineMapper>().MapTo(this, view);
        return view;
    }
    partial void ValidateEntity();

    partial void BeforeMap(ISalesOrderLine model);

    partial void AfterMap(ISalesOrderLine model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrderLineMapper : EntityMapperBase<int, ISalesOrderLine, SalesOrderLine, SalesOrderLineView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<ISalesOrderLine, SalesOrderLine>.NewConfig()
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ProductNameSnapshot!)
            .Ignore(entity => entity.SkuSnapshot!);
    }
}
