// <auto-generated />
using Paradigm.Enterprise.Domain.Repositories;

namespace SemanticViolations;

public sealed class GeneratedRawSqlRepository : IRepository
{
    public const string Statement = "DELETE FROM dbo.GeneratedRows";

    public void Dispose()
    {
    }
}
