// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;

namespace BeaconAr.Data.Operations.Mappers;

public static class OperationsStoredProcedureMappersRegisterer
{
    public static void RegisterMappers()
    {
        RegisterDataReaderMappers();
        RegisterSqlParameterMappers();
    }

    private static void RegisterDataReaderMappers()
    {
        DataReaderMapperFactory.RegisterMapper<Data.Operations.StoredProcedures.DashboardRow>(() => new DataReaders.DashboardRowDataReaderMapper());

    }

    private static void RegisterSqlParameterMappers()
    {
        SqlParameterMapperFactory.RegisterMapper<Data.Operations.StoredProcedures.DashboardParameters>(() => new SqlParameters.DashboardParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Operations.StoredProcedures.LockIdempotencyRequestParameters>(() => new SqlParameters.LockIdempotencyRequestParametersMapper());

    }
}