// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Operations.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Operations.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyRequestView : EntityBase<long>, IIdempotencyRequest
{
    public int UserId { get; set; }

    public string UserDisplayName { get; set; } = null!;

    public string Operation { get; set; } = null!;

    public byte[] KeyHash { get; set; } = null!;

    public byte[] RequestHash { get; set; } = null!;

    public int StateId { get; set; }

    public string StateCode { get; set; } = null!;

    public string StateDisplayName { get; set; } = null!;

    public string? ResourceType { get; set; }

    public string? ResourceId { get; set; }

    public short? ResponseStatusCode { get; set; }

    public int? CreatedByUserId { get; set; }

    public string? CreatedByUserDisplayName { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public string? ModifiedByUserDisplayName { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public DateTimeOffset? CompletionDate { get; set; }

    public DateTimeOffset ExpirationDate { get; set; }
}
