// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Operations.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Operations.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyStateView : EntityBase<int>, IIdempotencyState
{
    public string Code { get; set; } = null!;

    public string DisplayName { get; set; } = null!;

    public bool IsActive { get; set; }
}
