// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Operations.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;

namespace BeaconAr.Domain.Operations.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyState : EntityBase<int, IIdempotencyState, IdempotencyState, IdempotencyStateView>, IIdempotencyState
{
    public string Code { get; set; } = null!;

    public string DisplayName { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual ICollection<IdempotencyRequest> IdempotencyRequests { get; set; } = new List<IdempotencyRequest>();

    public override void Validate()
    {
        ValidateEntity();
    }

    public override IdempotencyState MapFrom(IServiceProvider serviceProvider, IIdempotencyState model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<IdempotencyStateMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override IdempotencyStateView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<IdempotencyStateView>();
        serviceProvider.GetRequiredService<IdempotencyStateMapper>().MapTo(this, view);
        return view;
    }
    partial void ValidateEntity();

    partial void BeforeMap(IIdempotencyState model);

    partial void AfterMap(IIdempotencyState model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyStateMapper : EntityMapperBase<int, IIdempotencyState, IdempotencyState, IdempotencyStateView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<IIdempotencyState, IdempotencyState>.NewConfig()
            .Ignore(entity => entity.Id!);
    }
}
