// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.MasterData.StoredProcedures;

namespace BeaconAr.Data.MasterData.Mappers.SqlParameters;

internal partial class HasProductReferencesParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is HasProductReferencesParameters instance)) return;

        AddSqlParameter(nameof(HasProductReferencesParameters.Id), instance.Id);

    }
}