using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace RepositorySqlSourceGenerator;

[Generator]
public sealed class RepositorySqlGenerator : IIncrementalGenerator
{
    #region Public Methods

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output => output.AddSource(
            "SourceGeneratedRawSqlRepository.g.cs",
            SourceText.From("""
                // <auto-generated />
                using Paradigm.Enterprise.Domain.Repositories;

                namespace SemanticViolations;

                public sealed class SourceGeneratedRawSqlRepository : IRepository
                {
                    public const string Statement = "SELECT Id FROM dbo.SourceGeneratedRows";

                    public void Dispose()
                    {
                    }
                }
                """, Encoding.UTF8)));
    }

    #endregion
}
