// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Domain.Receivables.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;

namespace BeaconAr.Data.Receivables.Context;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class ReceivablesDbContext : DbContextBase<int>
{
    public ReceivablesDbContext(IServiceProvider serviceProvider, DbContextOptions<ReceivablesDbContext> options)
        : base(serviceProvider, options)
    {
    }

    public virtual DbSet<AddressType> AddressTypes { get; set; }

    public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }

    public virtual DbSet<ApplicationUserView> ApplicationUserViews { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Carrier> Carriers { get; set; }

    public virtual DbSet<CarrierView> CarrierViews { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<CustomerAddressView> CustomerAddressViews { get; set; }

    public virtual DbSet<CustomerView> CustomerViews { get; set; }

    public virtual DbSet<IdempotencyRequest> IdempotencyRequests { get; set; }

    public virtual DbSet<IdempotencyState> IdempotencyStates { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductView> ProductViews { get; set; }

    public virtual DbSet<Quote> Quotes { get; set; }

    public virtual DbSet<QuoteLine> QuoteLines { get; set; }

    public virtual DbSet<QuoteLineView> QuoteLineViews { get; set; }

    public virtual DbSet<QuotePricing> QuotePricings { get; set; }

    public virtual DbSet<QuoteStatus> QuoteStatuses { get; set; }

    public virtual DbSet<QuoteStatusHistory> QuoteStatusHistories { get; set; }

    public virtual DbSet<QuoteView> QuoteViews { get; set; }

    public virtual DbSet<SalesOrder> SalesOrders { get; set; }

    public virtual DbSet<SalesOrderLine> SalesOrderLines { get; set; }

    public virtual DbSet<SalesOrderLineView> SalesOrderLineViews { get; set; }

    public virtual DbSet<SalesOrderPricing> SalesOrderPricings { get; set; }

    public virtual DbSet<SalesOrderStatus> SalesOrderStatuses { get; set; }

    public virtual DbSet<SalesOrderStatusHistory> SalesOrderStatusHistories { get; set; }

    public virtual DbSet<SalesOrderView> SalesOrderViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<AddressType>(entity =>
        {
            entity.ToTable("AddressType");

            entity.HasIndex(e => e.Code, "UQ_AddressType_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_AddressType_IsActive");
        });

        modelBuilder.Entity<ApplicationUser>(entity =>
        {
            entity.ToTable("ApplicationUser");

            entity.HasIndex(e => e.Email, "IX_ApplicationUser_Email").HasFilter("([Email] IS NOT NULL)");

            entity.HasIndex(e => new { e.Issuer, e.Subject }, "UQ_ApplicationUser_Issuer_Subject").IsUnique();

            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_ApplicationUser_IsActive");
            entity.Property(e => e.Issuer)
                .HasMaxLength(400)
                .UseCollation("Latin1_General_100_BIN2");
            entity.Property(e => e.Subject)
                .HasMaxLength(200)
                .UseCollation("Latin1_General_100_BIN2");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.InverseCreatedByUser).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.InverseModifiedByUser).HasForeignKey(d => d.ModifiedByUserId);
        });

        modelBuilder.Entity<ApplicationUserView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ApplicationUserView");

            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.Issuer)
                .HasMaxLength(400)
                .UseCollation("Latin1_General_100_BIN2");
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Subject)
                .HasMaxLength(200)
                .UseCollation("Latin1_General_100_BIN2");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.ToTable("AuditLog");

            entity.HasIndex(e => e.CorrelationId, "IX_AuditLog_CorrelationId");

            entity.HasIndex(e => new { e.ResourceType, e.ResourceId, e.RecordedAt }, "IX_AuditLog_ResourceType_ResourceId_RecordedAt");

            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.CorrelationId).HasMaxLength(128);
            entity.Property(e => e.MetadataJson).HasMaxLength(4000);
            entity.Property(e => e.NewStatusCode).HasMaxLength(32);
            entity.Property(e => e.PreviousStatusCode).HasMaxLength(32);
            entity.Property(e => e.ResourceId).HasMaxLength(50);
            entity.Property(e => e.ResourceType).HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuditLog_ApplicationUser");
        });

        modelBuilder.Entity<Carrier>(entity =>
        {
            entity.ToTable("Carrier");

            entity.HasIndex(e => new { e.IsActive, e.Id }, "IX_Carrier_IsActive_Id");

            entity.HasIndex(e => new { e.Name, e.Id }, "IX_Carrier_Name_Id");

            entity.HasIndex(e => e.Code, "UQ_Carrier_Code").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Carrier_IsActive");
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ServiceLevel).HasMaxLength(120);
            entity.Property(e => e.TrackingUrlTemplate).HasMaxLength(2048);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.CarrierCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.CarrierModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);
        });

        modelBuilder.Entity<CarrierView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CarrierView");

            entity.Property(e => e.Code)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ServiceLevel).HasMaxLength(120);
            entity.Property(e => e.TrackingUrlTemplate).HasMaxLength(2048);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer");

            entity.HasIndex(e => new { e.IsActive, e.Id }, "IX_Customer_IsActive_Id");

            entity.HasIndex(e => new { e.Name, e.Id }, "IX_Customer_Name_Id");

            entity.HasIndex(e => e.AccountNumber, "UQ_Customer_AccountNumber").IsUnique();

            entity.Property(e => e.AccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Customer_IsActive");
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.CustomerCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.CustomerModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);
        });

        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.ToTable("CustomerAddress");

            entity.HasIndex(e => new { e.CustomerId, e.AddressTypeId, e.Id }, "IX_CustomerAddress_CustomerId_AddressTypeId_Id");

            entity.HasIndex(e => e.CustomerId, "UQ_CustomerAddress_CustomerId_DefaultBilling")
                .IsUnique()
                .HasFilter("([IsDefaultBilling]=(1))");

            entity.HasIndex(e => e.CustomerId, "UQ_CustomerAddress_CustomerId_DefaultShipping")
                .IsUnique()
                .HasFilter("([IsDefaultShipping]=(1))");

            entity.HasIndex(e => new { e.CustomerId, e.Id }, "UQ_CustomerAddress_CustomerId_Id").IsUnique();

            entity.Property(e => e.City).HasMaxLength(120);
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.Label).HasMaxLength(120);
            entity.Property(e => e.Line1).HasMaxLength(200);
            entity.Property(e => e.Line2).HasMaxLength(200);
            entity.Property(e => e.PostalCode).HasMaxLength(32);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.State).HasMaxLength(120);

            entity.HasOne(d => d.AddressType).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.AddressTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerAddress_AddressType");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.CustomerAddressCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerAddress_Customer");

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.CustomerAddressModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);
        });

        modelBuilder.Entity<CustomerAddressView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CustomerAddressView");

            entity.Property(e => e.AddressTypeCode).HasMaxLength(32);
            entity.Property(e => e.AddressTypeDisplayName).HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(120);
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CustomerAccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CustomerName).HasMaxLength(120);
            entity.Property(e => e.Label).HasMaxLength(120);
            entity.Property(e => e.Line1).HasMaxLength(200);
            entity.Property(e => e.Line2).HasMaxLength(200);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.PostalCode).HasMaxLength(32);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.State).HasMaxLength(120);
        });

        modelBuilder.Entity<CustomerView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CustomerView");

            entity.Property(e => e.AccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<IdempotencyRequest>(entity =>
        {
            entity.ToTable("IdempotencyRequest");

            entity.HasIndex(e => new { e.StateId, e.ExpirationDate }, "IX_IdempotencyRequest_StateId_ExpirationDate");

            entity.HasIndex(e => new { e.UserId, e.Operation, e.KeyHash }, "UQ_IdempotencyRequest_UserId_Operation_KeyHash").IsUnique();

            entity.Property(e => e.KeyHash)
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.Operation).HasMaxLength(150);
            entity.Property(e => e.RequestHash)
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.ResourceId).HasMaxLength(50);
            entity.Property(e => e.ResourceType).HasMaxLength(100);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.IdempotencyRequestCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.IdempotencyRequestModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);

            entity.HasOne(d => d.State).WithMany(p => p.IdempotencyRequests)
                .HasForeignKey(d => d.StateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IdempotencyRequest_IdempotencyState");

            entity.HasOne(d => d.User).WithMany(p => p.IdempotencyRequestUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IdempotencyRequest_ApplicationUser");
        });

        modelBuilder.Entity<IdempotencyState>(entity =>
        {
            entity.ToTable("IdempotencyState");

            entity.HasIndex(e => e.Code, "UQ_IdempotencyState_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_IdempotencyState_IsActive");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.HasIndex(e => new { e.IsActive, e.Id }, "IX_Product_IsActive_Id");

            entity.HasIndex(e => new { e.Name, e.Id }, "IX_Product_Name_Id");

            entity.HasIndex(e => e.Sku, "UQ_Product_Sku").IsUnique();

            entity.Property(e => e.Category).HasMaxLength(120);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Product_IsActive");
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Sku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.ThumbnailUrl).HasMaxLength(2048);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.ProductCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.ProductModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);
        });

        modelBuilder.Entity<ProductView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ProductView");

            entity.Property(e => e.Category).HasMaxLength(120);
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Sku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.ThumbnailUrl).HasMaxLength(2048);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });

        modelBuilder.Entity<Quote>(entity =>
        {
            entity.ToTable("Quote");

            entity.HasIndex(e => new { e.CustomerId, e.Id }, "IX_Quote_CustomerId_Id");

            entity.HasIndex(e => new { e.StatusId, e.QuoteDate, e.Id }, "IX_Quote_StatusId_QuoteDate_Id");

            entity.HasIndex(e => new { e.ValidUntil, e.Id }, "IX_Quote_ValidUntil_Id");

            entity.HasIndex(e => e.QuoteNumber, "UQ_Quote_QuoteNumber").IsUnique();

            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QuoteNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.QuoteCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.Customer).WithMany(p => p.Quotes)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Quote_Customer");

            entity.HasOne(d => d.DeletedByUser).WithMany(p => p.QuoteDeletedByUsers).HasForeignKey(d => d.DeletedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.QuoteModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);

            entity.HasOne(d => d.Status).WithMany(p => p.Quotes)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Quote_QuoteStatus");

            entity.HasOne(d => d.CustomerAddress).WithMany(p => p.Quotes)
                .HasPrincipalKey(p => new { p.CustomerId, p.Id })
                .HasForeignKey(d => new { d.CustomerId, d.ShippingAddressId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Quote_CustomerAddress");
        });

        modelBuilder.Entity<QuoteLine>(entity =>
        {
            entity.ToTable("QuoteLine");

            entity.HasIndex(e => new { e.QuoteId, e.Id }, "IX_QuoteLine_QuoteId_Id");

            entity.HasIndex(e => new { e.QuoteId, e.ProductId }, "UQ_QuoteLine_QuoteId_ProductId").IsUnique();

            entity.Property(e => e.DiscountAmount)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))-round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");

            entity.HasOne(d => d.Product).WithMany(p => p.QuoteLines)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteLine_Product");

            entity.HasOne(d => d.Quote).WithMany(p => p.QuoteLines)
                .HasForeignKey(d => d.QuoteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteLine_Quote");
        });

        modelBuilder.Entity<QuoteLineView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("QuoteLineView");

            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ProductName).HasMaxLength(120);
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.ProductSku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.QuoteNumber).HasMaxLength(20);
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });

        modelBuilder.Entity<QuotePricing>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("QuotePricing");

            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
        });

        modelBuilder.Entity<QuoteStatus>(entity =>
        {
            entity.ToTable("QuoteStatus");

            entity.HasIndex(e => e.Code, "UQ_QuoteStatus_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_QuoteStatus_IsActive");
        });

        modelBuilder.Entity<QuoteStatusHistory>(entity =>
        {
            entity.ToTable("QuoteStatusHistory");

            entity.HasIndex(e => new { e.QuoteId, e.CreationDate, e.Id }, "IX_QuoteStatusHistory_QuoteId_CreationDate_Id");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.QuoteStatusHistories)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteStatusHistory_ApplicationUser");

            entity.HasOne(d => d.Quote).WithMany(p => p.QuoteStatusHistories)
                .HasForeignKey(d => d.QuoteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteStatusHistory_Quote");

            entity.HasOne(d => d.Status).WithMany(p => p.QuoteStatusHistories)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteStatusHistory_QuoteStatus");
        });

        modelBuilder.Entity<QuoteView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("QuoteView");

            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CustomerAccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerName).HasMaxLength(120);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.DeletedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QuoteNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressCity).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressCountry)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingAddressLabel).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressLine1).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressLine2).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressPostalCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressState).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressTypeCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeDisplayName).HasMaxLength(100);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);
            entity.Property(e => e.StatusCode).HasMaxLength(32);
            entity.Property(e => e.StatusDisplayName).HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
        });

        modelBuilder.Entity<SalesOrder>(entity =>
        {
            entity.ToTable("SalesOrder");

            entity.HasIndex(e => new { e.CustomerId, e.Id }, "IX_SalesOrder_CustomerId_Id");

            entity.HasIndex(e => new { e.RequestedShipDate, e.Id }, "IX_SalesOrder_RequestedShipDate_Id");

            entity.HasIndex(e => new { e.StatusId, e.Id }, "IX_SalesOrder_StatusId_Id");

            entity.HasIndex(e => e.TrackingNumber, "IX_SalesOrder_TrackingNumber").HasFilter("([TrackingNumber] IS NOT NULL)");

            entity.HasIndex(e => e.OrderNumber, "UQ_SalesOrder_OrderNumber").IsUnique();

            entity.HasIndex(e => e.SourceQuoteId, "UQ_SalesOrder_SourceQuoteId")
                .IsUnique()
                .HasFilter("([SourceQuoteId] IS NOT NULL)");

            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.OrderNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);
            entity.Property(e => e.TrackingNumber).HasMaxLength(200);

            entity.HasOne(d => d.Carrier).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.CarrierId)
                .HasConstraintName("FK_SalesOrder_Carrier");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.SalesOrderCreatedByUsers).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.Customer).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrder_Customer");

            entity.HasOne(d => d.DeletedByUser).WithMany(p => p.SalesOrderDeletedByUsers).HasForeignKey(d => d.DeletedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.SalesOrderModifiedByUsers).HasForeignKey(d => d.ModifiedByUserId);

            entity.HasOne(d => d.SourceQuote).WithOne(p => p.SalesOrder)
                .HasForeignKey<SalesOrder>(d => d.SourceQuoteId)
                .HasConstraintName("FK_SalesOrder_Quote");

            entity.HasOne(d => d.Status).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrder_SalesOrderStatus");

            entity.HasOne(d => d.CustomerAddress).WithMany(p => p.SalesOrders)
                .HasPrincipalKey(p => new { p.CustomerId, p.Id })
                .HasForeignKey(d => new { d.CustomerId, d.ShippingAddressId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrder_CustomerAddress");
        });

        modelBuilder.Entity<SalesOrderLine>(entity =>
        {
            entity.ToTable("SalesOrderLine");

            entity.HasIndex(e => new { e.SalesOrderId, e.Id }, "IX_SalesOrderLine_SalesOrderId_Id");

            entity.HasIndex(e => new { e.SalesOrderId, e.ProductId }, "UQ_SalesOrderLine_SalesOrderId_ProductId").IsUnique();

            entity.Property(e => e.DiscountAmount)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))-round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");

            entity.HasOne(d => d.Product).WithMany(p => p.SalesOrderLines)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderLine_Product");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesOrderLines)
                .HasForeignKey(d => d.SalesOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderLine_SalesOrder");
        });

        modelBuilder.Entity<SalesOrderLineView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SalesOrderLineView");

            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.OrderNumber).HasMaxLength(20);
            entity.Property(e => e.ProductName).HasMaxLength(120);
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.ProductSku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });

        modelBuilder.Entity<SalesOrderPricing>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SalesOrderPricing");

            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
        });

        modelBuilder.Entity<SalesOrderStatus>(entity =>
        {
            entity.ToTable("SalesOrderStatus");

            entity.HasIndex(e => e.Code, "UQ_SalesOrderStatus_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_SalesOrderStatus_IsActive");
        });

        modelBuilder.Entity<SalesOrderStatusHistory>(entity =>
        {
            entity.ToTable("SalesOrderStatusHistory");

            entity.HasIndex(e => new { e.SalesOrderId, e.CreationDate, e.Id }, "IX_SalesOrderStatusHistory_SalesOrderId_CreationDate_Id");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.SalesOrderStatusHistories)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderStatusHistory_ApplicationUser");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesOrderStatusHistories)
                .HasForeignKey(d => d.SalesOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderStatusHistory_SalesOrder");

            entity.HasOne(d => d.Status).WithMany(p => p.SalesOrderStatusHistories)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderStatusHistory_SalesOrderStatus");
        });

        modelBuilder.Entity<SalesOrderView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SalesOrderView");

            entity.Property(e => e.CarrierCode)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CarrierName).HasMaxLength(120);
            entity.Property(e => e.CarrierServiceLevel).HasMaxLength(120);
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CustomerAccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerName).HasMaxLength(120);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.DeletedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.OrderNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressCity).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressCountry)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingAddressLabel).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressLine1).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressLine2).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressPostalCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressState).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressTypeCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeDisplayName).HasMaxLength(100);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);
            entity.Property(e => e.SourceQuoteNumber).HasMaxLength(20);
            entity.Property(e => e.StatusCode).HasMaxLength(32);
            entity.Property(e => e.StatusDisplayName).HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.TrackingNumber).HasMaxLength(200);
        });
        modelBuilder.HasSequence("QuoteNumberSequence");
        modelBuilder.HasSequence("SalesOrderNumberSequence");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
