// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.MasterData.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;
using Paradigm.Enterprise.Interfaces;

namespace BeaconAr.Domain.MasterData.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class Carrier : EntityBase<int, ICarrier, Carrier, CarrierView>, ICarrier, IAuditableEntity<DateTimeOffset, int>
{
    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string ServiceLevel { get; set; } = null!;

    public string? TrackingUrlTemplate { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
    }

    public override Carrier MapFrom(IServiceProvider serviceProvider, ICarrier model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<CarrierMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override CarrierView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<CarrierView>();
        serviceProvider.GetRequiredService<CarrierMapper>().MapTo(this, view);
        return view;
    }
    partial void ValidateEntity();

    partial void BeforeMap(ICarrier model);

    partial void AfterMap(ICarrier model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class CarrierMapper : EntityMapperBase<int, ICarrier, Carrier, CarrierView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<ICarrier, Carrier>.NewConfig()
            .Ignore(entity => entity.CreatedByUserId!)
            .Ignore(entity => entity.CreationDate!)
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ModificationDate!)
            .Ignore(entity => entity.ModifiedByUserId!);
    }
}
