// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.MasterData.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;
using Paradigm.Enterprise.Interfaces;

namespace BeaconAr.Domain.MasterData.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class CustomerAddress : EntityBase<int, ICustomerAddress, CustomerAddress, CustomerAddressView>, ICustomerAddress, IAuditableEntity<DateTimeOffset, int>
{
    public int CustomerId { get; set; }

    public int AddressTypeId { get; set; }

    public string Label { get; set; } = null!;

    public string Line1 { get; set; } = null!;

    public string? Line2 { get; set; }

    public string City { get; set; } = null!;

    public string? State { get; set; }

    public string PostalCode { get; set; } = null!;

    public string Country { get; set; } = null!;

    public bool IsDefaultBilling { get; set; }

    public bool IsDefaultShipping { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public virtual AddressType AddressType { get; set; } = null!;

    public virtual Customer Customer { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
    }

    public override CustomerAddress MapFrom(IServiceProvider serviceProvider, ICustomerAddress model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<CustomerAddressMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override CustomerAddressView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<CustomerAddressView>();
        serviceProvider.GetRequiredService<CustomerAddressMapper>().MapTo(this, view);
        return view;
    }
    partial void ValidateEntity();

    partial void BeforeMap(ICustomerAddress model);

    partial void AfterMap(ICustomerAddress model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class CustomerAddressMapper : EntityMapperBase<int, ICustomerAddress, CustomerAddress, CustomerAddressView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<ICustomerAddress, CustomerAddress>.NewConfig()
            .Ignore(entity => entity.CreatedByUserId!)
            .Ignore(entity => entity.CreationDate!)
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ModificationDate!)
            .Ignore(entity => entity.ModifiedByUserId!);
    }
}
