// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Domain.Operations.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;

namespace BeaconAr.Data.Operations.Context;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class OperationsDbContext : DbContextBase<int>
{
    public OperationsDbContext(IServiceProvider serviceProvider, DbContextOptions<OperationsDbContext> options)
        : base(serviceProvider, options)
    {
    }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<AuditLogView> AuditLogViews { get; set; }

    public virtual DbSet<IdempotencyRequest> IdempotencyRequests { get; set; }

    public virtual DbSet<IdempotencyRequestView> IdempotencyRequestViews { get; set; }

    public virtual DbSet<IdempotencyState> IdempotencyStates { get; set; }

    public virtual DbSet<IdempotencyStateView> IdempotencyStateViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.ToTable("AuditLog");

            entity.HasIndex(e => e.CorrelationId, "IX_AuditLog_CorrelationId");

            entity.HasIndex(e => new { e.ResourceType, e.ResourceId, e.RecordedAt }, "IX_AuditLog_ResourceType_ResourceId_RecordedAt");

            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.CorrelationId).HasMaxLength(128);
            entity.Property(e => e.MetadataJson).HasMaxLength(4000);
            entity.Property(e => e.NewStatusCode).HasMaxLength(32);
            entity.Property(e => e.PreviousStatusCode).HasMaxLength(32);
            entity.Property(e => e.ResourceId).HasMaxLength(50);
            entity.Property(e => e.ResourceType).HasMaxLength(100);
        });

        modelBuilder.Entity<AuditLogView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("AuditLogView");

            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.CorrelationId).HasMaxLength(128);
            entity.Property(e => e.MetadataJson).HasMaxLength(4000);
            entity.Property(e => e.NewStatusCode).HasMaxLength(32);
            entity.Property(e => e.PreviousStatusCode).HasMaxLength(32);
            entity.Property(e => e.ResourceId).HasMaxLength(50);
            entity.Property(e => e.ResourceType).HasMaxLength(100);
            entity.Property(e => e.UserDisplayName).HasMaxLength(200);
        });

        modelBuilder.Entity<IdempotencyRequest>(entity =>
        {
            entity.ToTable("IdempotencyRequest");

            entity.HasIndex(e => new { e.StateId, e.ExpirationDate }, "IX_IdempotencyRequest_StateId_ExpirationDate");

            entity.HasIndex(e => new { e.UserId, e.Operation, e.KeyHash }, "UQ_IdempotencyRequest_UserId_Operation_KeyHash").IsUnique();

            entity.Property(e => e.KeyHash)
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.Operation).HasMaxLength(150);
            entity.Property(e => e.RequestHash)
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.ResourceId).HasMaxLength(50);
            entity.Property(e => e.ResourceType).HasMaxLength(100);

            entity.HasOne(d => d.State).WithMany(p => p.IdempotencyRequests)
                .HasForeignKey(d => d.StateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IdempotencyRequest_IdempotencyState");
        });

        modelBuilder.Entity<IdempotencyRequestView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("IdempotencyRequestView");

            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.KeyHash)
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Operation).HasMaxLength(150);
            entity.Property(e => e.RequestHash)
                .HasMaxLength(32)
                .IsFixedLength();
            entity.Property(e => e.ResourceId).HasMaxLength(50);
            entity.Property(e => e.ResourceType).HasMaxLength(100);
            entity.Property(e => e.StateCode).HasMaxLength(32);
            entity.Property(e => e.StateDisplayName).HasMaxLength(100);
            entity.Property(e => e.UserDisplayName).HasMaxLength(200);
        });

        modelBuilder.Entity<IdempotencyState>(entity =>
        {
            entity.ToTable("IdempotencyState");

            entity.HasIndex(e => e.Code, "UQ_IdempotencyState_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_IdempotencyState_IsActive");
        });

        modelBuilder.Entity<IdempotencyStateView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("IdempotencyStateView");

            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
        });
        modelBuilder.HasSequence("QuoteNumberSequence");
        modelBuilder.HasSequence("SalesOrderNumberSequence");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
