// <auto-generated/>
using BeaconAr.Data.MasterData.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Mappers.DataReaders;

internal partial class AddressSearchRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new AddressSearchRow();
        if (FieldIsValid(reader, nameof(AddressSearchRow.Id))) instance.Id = GetInt32(reader, nameof(AddressSearchRow.Id));
        if (FieldIsValid(reader, nameof(AddressSearchRow.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(AddressSearchRow.CustomerId));
        if (FieldIsValid(reader, nameof(AddressSearchRow.Type))) instance.Type = GetString(reader, nameof(AddressSearchRow.Type));
        if (FieldIsValid(reader, nameof(AddressSearchRow.Label))) instance.Label = GetString(reader, nameof(AddressSearchRow.Label));
        if (FieldIsValid(reader, nameof(AddressSearchRow.Line1))) instance.Line1 = GetString(reader, nameof(AddressSearchRow.Line1));
        if (FieldIsValid(reader, nameof(AddressSearchRow.Line2))) instance.Line2 = GetString(reader, nameof(AddressSearchRow.Line2));
        if (FieldIsValid(reader, nameof(AddressSearchRow.City))) instance.City = GetString(reader, nameof(AddressSearchRow.City));
        if (FieldIsValid(reader, nameof(AddressSearchRow.State))) instance.State = GetString(reader, nameof(AddressSearchRow.State));
        if (FieldIsValid(reader, nameof(AddressSearchRow.PostalCode))) instance.PostalCode = GetString(reader, nameof(AddressSearchRow.PostalCode));
        if (FieldIsValid(reader, nameof(AddressSearchRow.Country))) instance.Country = GetString(reader, nameof(AddressSearchRow.Country));
        if (FieldIsValid(reader, nameof(AddressSearchRow.DefaultBilling))) instance.DefaultBilling = GetBoolean(reader, nameof(AddressSearchRow.DefaultBilling));
        if (FieldIsValid(reader, nameof(AddressSearchRow.DefaultShipping))) instance.DefaultShipping = GetBoolean(reader, nameof(AddressSearchRow.DefaultShipping));
        if (FieldIsValid(reader, nameof(AddressSearchRow.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(AddressSearchRow.CreatedByUserId));
        if (FieldIsValid(reader, nameof(AddressSearchRow.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(AddressSearchRow.CreationDate));
        if (FieldIsValid(reader, nameof(AddressSearchRow.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(AddressSearchRow.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(AddressSearchRow.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(AddressSearchRow.ModificationDate));
        if (FieldIsValid(reader, nameof(AddressSearchRow.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(AddressSearchRow.RowVersion));

        return instance;
    }
}