// <auto-generated/>
using BeaconAr.Data.MasterData.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Mappers.DataReaders;

internal partial class CarrierSearchRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CarrierSearchRow();
        if (FieldIsValid(reader, nameof(CarrierSearchRow.Id))) instance.Id = GetInt32(reader, nameof(CarrierSearchRow.Id));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.Code))) instance.Code = GetString(reader, nameof(CarrierSearchRow.Code));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.Name))) instance.Name = GetString(reader, nameof(CarrierSearchRow.Name));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.ServiceLevel))) instance.ServiceLevel = GetString(reader, nameof(CarrierSearchRow.ServiceLevel));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.TrackingUrlTemplate))) instance.TrackingUrlTemplate = GetString(reader, nameof(CarrierSearchRow.TrackingUrlTemplate));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.IsActive))) instance.IsActive = GetBoolean(reader, nameof(CarrierSearchRow.IsActive));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(CarrierSearchRow.CreatedByUserId));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(CarrierSearchRow.CreationDate));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(CarrierSearchRow.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(CarrierSearchRow.ModificationDate));
        if (FieldIsValid(reader, nameof(CarrierSearchRow.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(CarrierSearchRow.RowVersion));

        return instance;
    }
}