// <auto-generated/>
using BeaconAr.Data.MasterData.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Mappers.DataReaders;

internal partial class CustomerSearchRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CustomerSearchRow();
        if (FieldIsValid(reader, nameof(CustomerSearchRow.Id))) instance.Id = GetInt32(reader, nameof(CustomerSearchRow.Id));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.AccountNumber))) instance.AccountNumber = GetString(reader, nameof(CustomerSearchRow.AccountNumber));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.Name))) instance.Name = GetString(reader, nameof(CustomerSearchRow.Name));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.Email))) instance.Email = GetString(reader, nameof(CustomerSearchRow.Email));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.Phone))) instance.Phone = GetString(reader, nameof(CustomerSearchRow.Phone));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.CreditLimit))) instance.CreditLimit = GetDecimal(reader, nameof(CustomerSearchRow.CreditLimit));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.PaymentTermsDays))) instance.PaymentTermsDays = GetInt16(reader, nameof(CustomerSearchRow.PaymentTermsDays));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.IsActive))) instance.IsActive = GetBoolean(reader, nameof(CustomerSearchRow.IsActive));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(CustomerSearchRow.CreatedByUserId));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(CustomerSearchRow.CreationDate));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(CustomerSearchRow.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(CustomerSearchRow.ModificationDate));
        if (FieldIsValid(reader, nameof(CustomerSearchRow.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(CustomerSearchRow.RowVersion));

        return instance;
    }
}