// <auto-generated/>
using BeaconAr.Data.MasterData.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Mappers.DataReaders;

internal partial class ProductSearchRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new ProductSearchRow();
        if (FieldIsValid(reader, nameof(ProductSearchRow.Id))) instance.Id = GetInt32(reader, nameof(ProductSearchRow.Id));
        if (FieldIsValid(reader, nameof(ProductSearchRow.Sku))) instance.Sku = GetString(reader, nameof(ProductSearchRow.Sku));
        if (FieldIsValid(reader, nameof(ProductSearchRow.Name))) instance.Name = GetString(reader, nameof(ProductSearchRow.Name));
        if (FieldIsValid(reader, nameof(ProductSearchRow.Category))) instance.Category = GetString(reader, nameof(ProductSearchRow.Category));
        if (FieldIsValid(reader, nameof(ProductSearchRow.UnitPrice))) instance.UnitPrice = GetDecimal(reader, nameof(ProductSearchRow.UnitPrice));
        if (FieldIsValid(reader, nameof(ProductSearchRow.StockQuantity))) instance.StockQuantity = GetInt32(reader, nameof(ProductSearchRow.StockQuantity));
        if (FieldIsValid(reader, nameof(ProductSearchRow.ThumbnailUrl))) instance.ThumbnailUrl = GetString(reader, nameof(ProductSearchRow.ThumbnailUrl));
        if (FieldIsValid(reader, nameof(ProductSearchRow.IsActive))) instance.IsActive = GetBoolean(reader, nameof(ProductSearchRow.IsActive));
        if (FieldIsValid(reader, nameof(ProductSearchRow.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(ProductSearchRow.CreatedByUserId));
        if (FieldIsValid(reader, nameof(ProductSearchRow.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(ProductSearchRow.CreationDate));
        if (FieldIsValid(reader, nameof(ProductSearchRow.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(ProductSearchRow.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(ProductSearchRow.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(ProductSearchRow.ModificationDate));
        if (FieldIsValid(reader, nameof(ProductSearchRow.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(ProductSearchRow.RowVersion));

        return instance;
    }
}