// <auto-generated/>
using BeaconAr.Data.Sales.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Mappers.DataReaders;

internal partial class QuoteSearchRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new QuoteSearchRow();
        if (FieldIsValid(reader, nameof(QuoteSearchRow.Id))) instance.Id = GetInt32(reader, nameof(QuoteSearchRow.Id));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.QuoteNumber))) instance.QuoteNumber = GetString(reader, nameof(QuoteSearchRow.QuoteNumber));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(QuoteSearchRow.CustomerId));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.CustomerAccountNumberSnapshot))) instance.CustomerAccountNumberSnapshot = GetString(reader, nameof(QuoteSearchRow.CustomerAccountNumberSnapshot));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.CustomerNameSnapshot))) instance.CustomerNameSnapshot = GetString(reader, nameof(QuoteSearchRow.CustomerNameSnapshot));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.QuoteDate))) instance.QuoteDate = GetDateTime(reader, nameof(QuoteSearchRow.QuoteDate));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.ValidUntil))) instance.ValidUntil = GetDateTime(reader, nameof(QuoteSearchRow.ValidUntil));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.StatusId))) instance.StatusId = GetInt32(reader, nameof(QuoteSearchRow.StatusId));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.Subtotal))) instance.Subtotal = GetDecimal(reader, nameof(QuoteSearchRow.Subtotal));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.DiscountTotal))) instance.DiscountTotal = GetDecimal(reader, nameof(QuoteSearchRow.DiscountTotal));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.GrandTotal))) instance.GrandTotal = GetDecimal(reader, nameof(QuoteSearchRow.GrandTotal));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.SalesOrderId))) instance.SalesOrderId = GetInt32(reader, nameof(QuoteSearchRow.SalesOrderId));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(QuoteSearchRow.CreatedByUserId));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(QuoteSearchRow.CreationDate));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(QuoteSearchRow.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(QuoteSearchRow.ModificationDate));
        if (FieldIsValid(reader, nameof(QuoteSearchRow.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(QuoteSearchRow.RowVersion));

        return instance;
    }
}