// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Access.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;
using Paradigm.Enterprise.Interfaces;

namespace BeaconAr.Domain.Access.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class ApplicationUser : EntityBase<int, IApplicationUser, ApplicationUser, ApplicationUserView>, IApplicationUser, IAuditableEntity<DateTimeOffset, int>
{
    public string Issuer { get; set; } = null!;

    public string Subject { get; set; } = null!;

    public string DisplayName { get; set; } = null!;

    public string? Email { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public virtual ApplicationUser? CreatedByUser { get; set; }

    public virtual ICollection<ApplicationUser> InverseCreatedByUser { get; set; } = new List<ApplicationUser>();

    public virtual ICollection<ApplicationUser> InverseModifiedByUser { get; set; } = new List<ApplicationUser>();

    public virtual ApplicationUser? ModifiedByUser { get; set; }

    public override void Validate()
    {
        ValidateEntity();
    }

    public override ApplicationUser MapFrom(IServiceProvider serviceProvider, IApplicationUser model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<ApplicationUserMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override ApplicationUserView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<ApplicationUserView>();
        serviceProvider.GetRequiredService<ApplicationUserMapper>().MapTo(this, view);
        return view;
    }
    partial void ValidateEntity();

    partial void BeforeMap(IApplicationUser model);

    partial void AfterMap(IApplicationUser model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class ApplicationUserMapper : EntityMapperBase<int, IApplicationUser, ApplicationUser, ApplicationUserView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<IApplicationUser, ApplicationUser>.NewConfig()
            .Ignore(entity => entity.CreatedByUserId!)
            .Ignore(entity => entity.CreationDate!)
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ModificationDate!)
            .Ignore(entity => entity.ModifiedByUserId!);
    }
}
