// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Sales.StoredProcedures;

namespace BeaconAr.Data.Sales.Mappers.SqlParameters;

internal partial class GetCarrierSalesReferenceForUpdateParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is GetCarrierSalesReferenceForUpdateParameters instance)) return;

        AddSqlParameter(nameof(GetCarrierSalesReferenceForUpdateParameters.Id), instance.Id);

    }
}