// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Sales.StoredProcedures;

namespace BeaconAr.Data.Sales.Mappers.SqlParameters;

internal partial class GetCustomerSalesReferenceForUpdateParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is GetCustomerSalesReferenceForUpdateParameters instance)) return;

        AddSqlParameter(nameof(GetCustomerSalesReferenceForUpdateParameters.Id), instance.Id);

    }
}