// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Sales.StoredProcedures;

namespace BeaconAr.Data.Sales.Mappers.SqlParameters;

internal partial class QuoteSearchParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is QuoteSearchParameters instance)) return;

        AddSqlParameter(nameof(QuoteSearchParameters.Search), instance.Search);
        AddSqlParameter(nameof(QuoteSearchParameters.StatusId), instance.StatusId);
        AddSqlParameter(nameof(QuoteSearchParameters.CustomerId), instance.CustomerId);
        AddSqlParameter(nameof(QuoteSearchParameters.PageNumber), instance.PageNumber);
        AddSqlParameter(nameof(QuoteSearchParameters.PageSize), instance.PageSize);
        AddSqlParameter(nameof(QuoteSearchParameters.SortField), instance.SortField);
        AddSqlParameter(nameof(QuoteSearchParameters.SortDirection), instance.SortDirection);

    }
}