<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
		<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" />
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Paradigm.Enterprise.WebApi" />
	</ItemGroup>

	<PropertyGroup>
		<OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)\..\..\artifacts\openapi</OpenApiDocumentsDirectory>
		<OpenApiGenerateDocumentsOptions>--file-name beacon-ar-v1 --openapi-version OpenApi3_0</OpenApiGenerateDocumentsOptions>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeaconAr.Data\BeaconAr.Data.csproj" />
		<ProjectReference Include="..\BeaconAr.Domain\BeaconAr.Domain.csproj" />
		<ProjectReference Include="..\BeaconAr.Providers\BeaconAr.Providers.csproj" />
		<ProjectReference Include="..\BeaconAr.ServiceDefaults\BeaconAr.ServiceDefaults.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\swagger\" />
	</ItemGroup>

</Project>
