services:
  #################################################################
  # MY-SQL
  #################################################################
  paradigm-enterprise-mysql:
    image: paradigm-enterprise-mysql
    container_name: paradigm-enterprise-mysql
    build:
      context: ./
      dockerfile: ./mysql.dockerfile
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Paradigm_Test_1234
      - MYSQL_DATABASE=test

  #################################################################
  # T-SQL
  #################################################################
  paradigm-enterprise-mssql:
    image: paradigm-enterprise-mssql
    container_name: paradigm-enterprise-mssql
    build:
      context: ./
      dockerfile: ./mssql.dockerfile
    restart: "no"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Paradigm_Test_1234
      - MSSQL_PID=Developer

  #################################################################
  # PG-SQL
  #################################################################
  paradigm-enterprise-pgsql:
    image: paradigm-enterprise-pgsql
    container_name: paradigm-enterprise-pgsql
    build:
      context: ./
      dockerfile: ./pgsql.dockerfile
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Paradigm_Test_1234
      - POSTGRES_DB=test
      - TZ=GMT+3
      - PGTZ=GMT+3
