// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Domain.MasterData.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;

namespace BeaconAr.Data.MasterData.Context;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class MasterDataDbContext : DbContextBase<int>
{
    public MasterDataDbContext(IServiceProvider serviceProvider, DbContextOptions<MasterDataDbContext> options)
        : base(serviceProvider, options)
    {
    }

    public virtual DbSet<AddressType> AddressTypes { get; set; }

    public virtual DbSet<Carrier> Carriers { get; set; }

    public virtual DbSet<CarrierView> CarrierViews { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<CustomerAddressView> CustomerAddressViews { get; set; }

    public virtual DbSet<CustomerView> CustomerViews { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductView> ProductViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<AddressType>(entity =>
        {
            entity.ToTable("AddressType");

            entity.HasIndex(e => e.Code, "UQ_AddressType_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_AddressType_IsActive");
        });

        modelBuilder.Entity<Carrier>(entity =>
        {
            entity.ToTable("Carrier");

            entity.HasIndex(e => new { e.IsActive, e.Id }, "IX_Carrier_IsActive_Id");

            entity.HasIndex(e => new { e.Name, e.Id }, "IX_Carrier_Name_Id");

            entity.HasIndex(e => e.Code, "UQ_Carrier_Code").IsUnique();

            entity.Property(e => e.Code)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Carrier_IsActive");
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ServiceLevel).HasMaxLength(120);
            entity.Property(e => e.TrackingUrlTemplate).HasMaxLength(2048);
        });

        modelBuilder.Entity<CarrierView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CarrierView");

            entity.Property(e => e.Code)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ServiceLevel).HasMaxLength(120);
            entity.Property(e => e.TrackingUrlTemplate).HasMaxLength(2048);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer");

            entity.HasIndex(e => new { e.IsActive, e.Id }, "IX_Customer_IsActive_Id");

            entity.HasIndex(e => new { e.Name, e.Id }, "IX_Customer_Name_Id");

            entity.HasIndex(e => e.AccountNumber, "UQ_Customer_AccountNumber").IsUnique();

            entity.Property(e => e.AccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Customer_IsActive");
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.ToTable("CustomerAddress");

            entity.HasIndex(e => new { e.CustomerId, e.AddressTypeId, e.Id }, "IX_CustomerAddress_CustomerId_AddressTypeId_Id");

            entity.HasIndex(e => e.CustomerId, "UQ_CustomerAddress_CustomerId_DefaultBilling")
                .IsUnique()
                .HasFilter("([IsDefaultBilling]=(1))");

            entity.HasIndex(e => e.CustomerId, "UQ_CustomerAddress_CustomerId_DefaultShipping")
                .IsUnique()
                .HasFilter("([IsDefaultShipping]=(1))");

            entity.HasIndex(e => new { e.CustomerId, e.Id }, "UQ_CustomerAddress_CustomerId_Id").IsUnique();

            entity.Property(e => e.City).HasMaxLength(120);
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.Label).HasMaxLength(120);
            entity.Property(e => e.Line1).HasMaxLength(200);
            entity.Property(e => e.Line2).HasMaxLength(200);
            entity.Property(e => e.PostalCode).HasMaxLength(32);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.State).HasMaxLength(120);

            entity.HasOne(d => d.AddressType).WithMany(p => p.CustomerAddresses)
                .HasForeignKey(d => d.AddressTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerAddress_AddressType");

            entity.HasOne(d => d.Customer).WithOne(p => p.CustomerAddress)
                .HasForeignKey<CustomerAddress>(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerAddress_Customer");
        });

        modelBuilder.Entity<CustomerAddressView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CustomerAddressView");

            entity.Property(e => e.AddressTypeCode).HasMaxLength(32);
            entity.Property(e => e.AddressTypeDisplayName).HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(120);
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CustomerAccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CustomerName).HasMaxLength(120);
            entity.Property(e => e.Label).HasMaxLength(120);
            entity.Property(e => e.Line1).HasMaxLength(200);
            entity.Property(e => e.Line2).HasMaxLength(200);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.PostalCode).HasMaxLength(32);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.State).HasMaxLength(120);
        });

        modelBuilder.Entity<CustomerView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("CustomerView");

            entity.Property(e => e.AccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CreditLimit).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.HasIndex(e => new { e.IsActive, e.Id }, "IX_Product_IsActive_Id");

            entity.HasIndex(e => new { e.Name, e.Id }, "IX_Product_Name_Id");

            entity.HasIndex(e => e.Sku, "UQ_Product_Sku").IsUnique();

            entity.Property(e => e.Category).HasMaxLength(120);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Product_IsActive");
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Sku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.ThumbnailUrl).HasMaxLength(2048);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });

        modelBuilder.Entity<ProductView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ProductView");

            entity.Property(e => e.Category).HasMaxLength(120);
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(120);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.Sku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.ThumbnailUrl).HasMaxLength(2048);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });
        modelBuilder.HasSequence("QuoteNumberSequence");
        modelBuilder.HasSequence("SalesOrderNumberSequence");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
