// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class ApplicationUserView : EntityBase<int>, IApplicationUser
{
    public string Issuer { get; set; } = null!;

    public string Subject { get; set; } = null!;

    public string DisplayName { get; set; } = null!;

    public string? Email { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedByUserId { get; set; }

    public string? CreatedByUserDisplayName { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public string? ModifiedByUserDisplayName { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }
}
