// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class AuditLog
{
    public long Id { get; set; }

    public string ResourceType { get; set; } = null!;

    public string ResourceId { get; set; } = null!;

    public string Action { get; set; } = null!;

    public int UserId { get; set; }

    public DateTimeOffset RecordedAt { get; set; }

    public string CorrelationId { get; set; } = null!;

    public string? PreviousStatusCode { get; set; }

    public string? NewStatusCode { get; set; }

    public string? MetadataJson { get; set; }

    public virtual ApplicationUser User { get; set; } = null!;
}
