// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class CustomerAddressView : EntityBase<int>, ICustomerAddress
{
    public int CustomerId { get; set; }

    public string CustomerAccountNumber { get; set; } = null!;

    public string CustomerName { get; set; } = null!;

    public int AddressTypeId { get; set; }

    public string AddressTypeCode { get; set; } = null!;

    public string AddressTypeDisplayName { get; set; } = null!;

    public string Label { get; set; } = null!;

    public string Line1 { get; set; } = null!;

    public string? Line2 { get; set; }

    public string City { get; set; } = null!;

    public string? State { get; set; }

    public string PostalCode { get; set; } = null!;

    public string Country { get; set; } = null!;

    public bool IsDefaultBilling { get; set; }

    public bool IsDefaultShipping { get; set; }

    public int? CreatedByUserId { get; set; }

    public string? CreatedByUserDisplayName { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public string? ModifiedByUserDisplayName { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public byte[] RowVersion { get; set; } = null!;
}
