// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyRequest : EntityBase<long, IIdempotencyRequest, IdempotencyRequest, IdempotencyRequestView>, IIdempotencyRequest
{
    public int UserId { get; set; }

    public string Operation { get; set; } = null!;

    public byte[] KeyHash { get; set; } = null!;

    public byte[] RequestHash { get; set; } = null!;

    public int StateId { get; set; }

    public string? ResourceType { get; set; }

    public string? ResourceId { get; set; }

    public short? ResponseStatusCode { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public DateTimeOffset? CompletionDate { get; set; }

    public DateTimeOffset ExpirationDate { get; set; }

    public virtual ApplicationUser? CreatedByUser { get; set; }

    public virtual ApplicationUser? ModifiedByUser { get; set; }

    public virtual IdempotencyState State { get; set; } = null!;

    public virtual ApplicationUser User { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
    }

    public override IdempotencyRequest MapFrom(IServiceProvider serviceProvider, IIdempotencyRequest model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<IdempotencyRequestMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override IdempotencyRequestView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<IdempotencyRequestView>();
        serviceProvider.GetRequiredService<IdempotencyRequestMapper>().MapTo(this, view);
        return view;
    }

    partial void ValidateEntity();

    partial void BeforeMap(IIdempotencyRequest model);

    partial void AfterMap(IIdempotencyRequest model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyRequestMapper : EntityMapperBase<long, IIdempotencyRequest, IdempotencyRequest, IdempotencyRequestView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<IIdempotencyRequest, IdempotencyRequest>.NewConfig()
            .Ignore(entity => entity.CreatedByUserId!)
            .Ignore(entity => entity.CreationDate!)
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ModificationDate!)
            .Ignore(entity => entity.ModifiedByUserId!);
    }
}
