// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class IdempotencyRequest
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public string Operation { get; set; } = null!;

    public byte[] KeyHash { get; set; } = null!;

    public byte[] RequestHash { get; set; } = null!;

    public int StateId { get; set; }

    public string? ResourceType { get; set; }

    public string? ResourceId { get; set; }

    public short? ResponseStatusCode { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public DateTimeOffset? CompletionDate { get; set; }

    public DateTimeOffset ExpirationDate { get; set; }

    public virtual ApplicationUser? CreatedByUser { get; set; }

    public virtual ApplicationUser? ModifiedByUser { get; set; }

    public virtual IdempotencyState State { get; set; } = null!;

    public virtual ApplicationUser User { get; set; } = null!;
}
