// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class ProductView : EntityBase<int>, IProduct
{
    public string Sku { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string Category { get; set; } = null!;

    public decimal UnitPrice { get; set; }

    public int StockQuantity { get; set; }

    public string? ThumbnailUrl { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedByUserId { get; set; }

    public string? CreatedByUserDisplayName { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public string? ModifiedByUserDisplayName { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public byte[] RowVersion { get; set; } = null!;
}
