// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class QuoteView : EntityBase<int>, IQuote
{
    public string QuoteNumber { get; set; } = null!;

    public int CustomerId { get; set; }

    public string CustomerAccountNumber { get; set; } = null!;

    public string CustomerName { get; set; } = null!;

    public bool CustomerIsActive { get; set; }

    public int ShippingAddressId { get; set; }

    public string ShippingAddressLabel { get; set; } = null!;

    public string ShippingAddressLine1 { get; set; } = null!;

    public string? ShippingAddressLine2 { get; set; }

    public string ShippingAddressCity { get; set; } = null!;

    public string? ShippingAddressState { get; set; }

    public string ShippingAddressPostalCode { get; set; } = null!;

    public string ShippingAddressCountry { get; set; } = null!;

    public string ShippingAddressTypeCode { get; set; } = null!;

    public string ShippingAddressTypeDisplayName { get; set; } = null!;

    public DateOnly QuoteDate { get; set; }

    public DateOnly ValidUntil { get; set; }

    public int StatusId { get; set; }

    public string StatusCode { get; set; } = null!;

    public string StatusDisplayName { get; set; } = null!;

    public string? Notes { get; set; }

    public string CustomerAccountNumberSnapshot { get; set; } = null!;

    public string CustomerNameSnapshot { get; set; } = null!;

    public string CustomerEmailSnapshot { get; set; } = null!;

    public string? CustomerPhoneSnapshot { get; set; }

    public string ShippingLabelSnapshot { get; set; } = null!;

    public string ShippingLine1Snapshot { get; set; } = null!;

    public string? ShippingLine2Snapshot { get; set; }

    public string ShippingCitySnapshot { get; set; } = null!;

    public string? ShippingStateSnapshot { get; set; }

    public string ShippingPostalCodeSnapshot { get; set; } = null!;

    public string ShippingCountrySnapshot { get; set; } = null!;

    public string ShippingAddressTypeCodeSnapshot { get; set; } = null!;

    public decimal? Subtotal { get; set; }

    public decimal? DiscountTotal { get; set; }

    public decimal? GrandTotal { get; set; }

    public int? SalesOrderId { get; set; }

    public int? CreatedByUserId { get; set; }

    public string? CreatedByUserDisplayName { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public string? ModifiedByUserDisplayName { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public DateTimeOffset? DeletionDate { get; set; }

    public int? DeletedByUserId { get; set; }

    public string? DeletedByUserDisplayName { get; set; }

    public byte[] RowVersion { get; set; } = null!;
}
