// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class QuoteLine : EntityBase<int, IQuoteLine, QuoteLine, QuoteLineView>, IQuoteLine
{
    public int QuoteId { get; set; }

    public int ProductId { get; set; }

    public string SkuSnapshot { get; set; } = null!;

    public string ProductNameSnapshot { get; set; } = null!;

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal DiscountPercent { get; set; }

    public decimal? LineSubtotal { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? LineTotal { get; set; }

    public virtual Product Product { get; set; } = null!;

    public virtual Quote Quote { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
    }

    public override QuoteLine MapFrom(IServiceProvider serviceProvider, IQuoteLine model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<QuoteLineMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override QuoteLineView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<QuoteLineView>();
        serviceProvider.GetRequiredService<QuoteLineMapper>().MapTo(this, view);
        return view;
    }

    partial void ValidateEntity();

    partial void BeforeMap(IQuoteLine model);

    partial void AfterMap(IQuoteLine model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class QuoteLineMapper : EntityMapperBase<int, IQuoteLine, QuoteLine, QuoteLineView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<IQuoteLine, QuoteLine>.NewConfig()
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ProductNameSnapshot!)
            .Ignore(entity => entity.SkuSnapshot!);
    }
}
