// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Mapster;
using Microsoft.Extensions.DependencyInjection;
using Paradigm.Enterprise.Domain.Entities;
using Paradigm.Enterprise.Domain.Mappers;
using Paradigm.Enterprise.Interfaces;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class Quote : EntityBase<int, IQuote, Quote, QuoteView>, IQuote, IAuditableEntity<DateTimeOffset, int>
{
    public string QuoteNumber { get; set; } = null!;

    public int CustomerId { get; set; }

    public int ShippingAddressId { get; set; }

    public DateOnly QuoteDate { get; set; }

    public DateOnly ValidUntil { get; set; }

    public int StatusId { get; set; }

    public string? Notes { get; set; }

    public string CustomerAccountNumberSnapshot { get; set; } = null!;

    public string CustomerNameSnapshot { get; set; } = null!;

    public string CustomerEmailSnapshot { get; set; } = null!;

    public string? CustomerPhoneSnapshot { get; set; }

    public string ShippingLabelSnapshot { get; set; } = null!;

    public string ShippingLine1Snapshot { get; set; } = null!;

    public string? ShippingLine2Snapshot { get; set; }

    public string ShippingCitySnapshot { get; set; } = null!;

    public string? ShippingStateSnapshot { get; set; }

    public string ShippingPostalCodeSnapshot { get; set; } = null!;

    public string ShippingCountrySnapshot { get; set; } = null!;

    public string ShippingAddressTypeCodeSnapshot { get; set; } = null!;

    public int? CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public int? ModifiedByUserId { get; set; }

    public DateTimeOffset? ModificationDate { get; set; }

    public DateTimeOffset? DeletionDate { get; set; }

    public int? DeletedByUserId { get; set; }

    public byte[] RowVersion { get; set; } = null!;

    public virtual ApplicationUser? CreatedByUser { get; set; }

    public virtual Customer Customer { get; set; } = null!;

    public virtual CustomerAddress CustomerAddress { get; set; } = null!;

    public virtual ApplicationUser? DeletedByUser { get; set; }

    public virtual ApplicationUser? ModifiedByUser { get; set; }

    private readonly List<QuoteLine> _quoteLines = [];
    public virtual IList<QuoteLine> QuoteLines => _quoteLines;
    public DomainTracker<QuoteLine> QuoteLinesDomainTracker { get; } = new();

    public virtual ICollection<QuoteStatusHistory> QuoteStatusHistories { get; set; } = new List<QuoteStatusHistory>();

    public virtual SalesOrder? SalesOrder { get; set; }

    public virtual QuoteStatus Status { get; set; } = null!;

    public override void Validate()
    {
        ValidateEntity();
        foreach (var child in QuoteLines)
            child.Validate();
    }

    public override Quote MapFrom(IServiceProvider serviceProvider, IQuote model)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        ArgumentNullException.ThrowIfNull(model);
        BeforeMap(model);
        serviceProvider.GetRequiredService<QuoteMapper>().MapFromInterface(this, model);
        AfterMap(model);
        return this;
    }

    public override QuoteView MapTo(IServiceProvider serviceProvider)
    {
        ArgumentNullException.ThrowIfNull(serviceProvider);
        var view = serviceProvider.GetRequiredService<QuoteView>();
        serviceProvider.GetRequiredService<QuoteMapper>().MapTo(this, view);
        return view;
    }

    public void AddQuoteLines(QuoteLine? entity)
    {
        if (entity is null)
            return;
        _quoteLines.Add(entity);
        QuoteLinesDomainTracker.Add(entity);
    }

    public void RemoveQuoteLines(QuoteLine? entity)
    {
        if (entity is null)
            return;
        _quoteLines.Remove(entity);
        QuoteLinesDomainTracker.Remove(entity);
    }

    partial void ValidateEntity();

    partial void BeforeMap(IQuote model);

    partial void AfterMap(IQuote model);
}

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class QuoteMapper : EntityMapperBase<int, IQuote, Quote, QuoteView>
{
    protected override void RegisterCustomConfigurations()
    {
        if (HasCustomConfigurationRegistered())
            return;

        TypeAdapterConfig<IQuote, Quote>.NewConfig()
            .Ignore(entity => entity.CreatedByUserId!)
            .Ignore(entity => entity.CreationDate!)
            .Ignore(entity => entity.CustomerAccountNumberSnapshot!)
            .Ignore(entity => entity.CustomerEmailSnapshot!)
            .Ignore(entity => entity.CustomerNameSnapshot!)
            .Ignore(entity => entity.CustomerPhoneSnapshot!)
            .Ignore(entity => entity.DeletedByUserId!)
            .Ignore(entity => entity.DeletionDate!)
            .Ignore(entity => entity.Id!)
            .Ignore(entity => entity.ModificationDate!)
            .Ignore(entity => entity.ModifiedByUserId!)
            .Ignore(entity => entity.ShippingAddressTypeCodeSnapshot!)
            .Ignore(entity => entity.ShippingCitySnapshot!)
            .Ignore(entity => entity.ShippingCountrySnapshot!)
            .Ignore(entity => entity.ShippingLabelSnapshot!)
            .Ignore(entity => entity.ShippingLine1Snapshot!)
            .Ignore(entity => entity.ShippingLine2Snapshot!)
            .Ignore(entity => entity.ShippingPostalCodeSnapshot!)
            .Ignore(entity => entity.ShippingStateSnapshot!);
    }
}
