// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Interfaces.Receivables.Entities;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrderLineView : EntityBase<int>, ISalesOrderLine
{
    public int SalesOrderId { get; set; }

    public string OrderNumber { get; set; } = null!;

    public int ProductId { get; set; }

    public string ProductSku { get; set; } = null!;

    public string ProductName { get; set; } = null!;

    public bool ProductIsActive { get; set; }

    public string SkuSnapshot { get; set; } = null!;

    public string ProductNameSnapshot { get; set; } = null!;

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal DiscountPercent { get; set; }

    public decimal? LineSubtotal { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? LineTotal { get; set; }
}
