// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Paradigm.Enterprise.Domain.Entities;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrderStatusHistory : EntityBase<int>
{
    public int SalesOrderId { get; set; }

    public int StatusId { get; set; }

    public int CreatedByUserId { get; set; }

    public DateTimeOffset CreationDate { get; set; }

    public virtual ApplicationUser CreatedByUser { get; set; } = null!;

    public virtual SalesOrder SalesOrder { get; set; } = null!;

    public virtual SalesOrderStatus Status { get; set; } = null!;
}
