// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BeaconAr.Domain.Receivables.Entities;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesOrderPricing
{
    public int SalesOrderId { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? DiscountTotal { get; set; }

    public decimal? GrandTotal { get; set; }
}
