<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Paradigm.Enterprise.Domain" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeaconAr.Interfaces\BeaconAr.Interfaces.csproj" OutputItemType="Analyzer" />
	</ItemGroup>

</Project>
