using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace BeaconAr.Interfaces
{
    [Generator]
    internal sealed class EntityInterfaceGenerator : IIncrementalGenerator
    {
        #region Fields

        private static readonly SymbolDisplayFormat PropertyTypeFormat = new(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                                  SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                                  SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

        #endregion

        #region Public Methods

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<ClassDeclarationSyntax> entities = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is ClassDeclarationSyntax declaration && IsMappedEntityDeclaration(declaration),
                    static (syntaxContext, _) => (ClassDeclarationSyntax)syntaxContext.Node);

            IncrementalValueProvider<(Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right)> source =
                context.CompilationProvider.Combine(entities.Collect());
            context.RegisterSourceOutput(source, static (productionContext, input) =>
                Execute(productionContext, input.Left, input.Right));
        }

        #endregion

        #region Private Methods

        private static void Execute(
            SourceProductionContext context,
            Compilation compilation,
            ImmutableArray<ClassDeclarationSyntax> declarations)
        {
            HashSet<string> emittedNames = new(StringComparer.Ordinal);
            foreach (ClassDeclarationSyntax declaration in declarations)
            {
                INamedTypeSymbol? entity = compilation.GetSemanticModel(declaration.SyntaxTree).GetDeclaredSymbol(declaration) as INamedTypeSymbol;
                if (entity is null || entity.Name.EndsWith("View", StringComparison.Ordinal) ||
                    entity.ContainingNamespace.IsGlobalNamespace)
                {
                    continue;
                }

                string entityNamespace = entity.ContainingNamespace.ToDisplayString();
                if (!entityNamespace.StartsWith("BeaconAr.Domain.", StringComparison.Ordinal))
                {
                    continue;
                }

                string interfaceNamespace = "BeaconAr.Interfaces." + entityNamespace.Substring("BeaconAr.Domain.".Length);
                string hintName = $"{interfaceNamespace}.I{entity.Name}.g.cs";
                if (!emittedNames.Add(hintName))
                {
                    continue;
                }

                IReadOnlyList<IPropertySymbol> properties = entity.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(static property => property.DeclaredAccessibility == Accessibility.Public &&
                                              !property.IsStatic &&
                                              property.GetMethod is not null &&
                                              IsScalar(property.Type))
                    .OrderBy(static property => property.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
                    .ThenBy(static property => property.Name, StringComparer.Ordinal)
                    .ToList();
                INamedTypeSymbol? mappedEntityBase = FindMappedEntityBase(entity);
                if (mappedEntityBase is null)
                {
                    continue;
                }

                string identifierType = mappedEntityBase.TypeArguments[0].ToDisplayString(PropertyTypeFormat);

                StringBuilder output = new();
                output.AppendLine("// <auto-generated/>");
                output.AppendLine("#nullable enable");
                output.AppendLine();
                output.Append("namespace ").Append(interfaceNamespace).AppendLine(";");
                output.AppendLine();
                output.Append("public partial interface I").Append(entity.Name)
                    .Append(" : global::Paradigm.Enterprise.Interfaces.IEntity<").Append(identifierType).AppendLine(">");
                output.AppendLine("{");
                foreach (IPropertySymbol property in properties)
                {
                    output.Append("    ").Append(property.Type.ToDisplayString(PropertyTypeFormat)).Append(' ')
                        .Append(EscapeIdentifier(property.Name)).AppendLine(" { get; }");
                }

                output.AppendLine("}");
                context.AddSource(hintName, output.ToString());
            }
        }

        private static bool IsMappedEntityDeclaration(ClassDeclarationSyntax declaration)
        {
            if (declaration.Identifier.ValueText.EndsWith("View", StringComparison.Ordinal) || declaration.BaseList is null)
            {
                return false;
            }

            return declaration.BaseList.Types.Any(static baseType =>
                baseType.Type is GenericNameSyntax genericName &&
                genericName.Identifier.ValueText == "EntityBase" &&
                genericName.TypeArgumentList.Arguments.Count == 4);
        }

        private static INamedTypeSymbol? FindMappedEntityBase(INamedTypeSymbol entity)
        {
            for (INamedTypeSymbol? candidate = entity.BaseType; candidate is not null; candidate = candidate.BaseType)
            {
                if (candidate.Name == "EntityBase" &&
                    candidate.TypeArguments.Length == 4 &&
                    candidate.ContainingNamespace.ToDisplayString() == "Paradigm.Enterprise.Domain.Entities")
                {
                    return candidate;
                }
            }

            return null;
        }

        private static bool IsScalar(ITypeSymbol type)
        {
            if (type.NullableAnnotation == NullableAnnotation.Annotated && type is INamedTypeSymbol annotated)
            {
                type = annotated;
            }

            if (type.TypeKind == TypeKind.Enum || type.SpecialType != SpecialType.None)
            {
                return true;
            }

            if (type is IArrayTypeSymbol arrayType)
            {
                return arrayType.Rank == 1 && arrayType.ElementType.SpecialType == SpecialType.System_Byte;
            }

            if (type is not INamedTypeSymbol namedType)
            {
                return false;
            }

            if (namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            {
                return IsScalar(namedType.TypeArguments[0]);
            }

            return namedType.ContainingNamespace.ToDisplayString() == "System" &&
                   namedType.Name is "DateOnly" or "DateTime" or "DateTimeOffset" or "Guid" or "TimeOnly" or "TimeSpan";
        }

        private static string EscapeIdentifier(string identifier) =>
            Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(identifier) == Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
                ? identifier
                : "@" + identifier;

        #endregion
    }
}
