// <auto-generated/>
using BeaconAr.Data.Sales.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class AddressSalesReferenceRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new AddressSalesReferenceRow();
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.Id))) instance.Id = GetInt32(reader, nameof(AddressSalesReferenceRow.Id));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(AddressSalesReferenceRow.CustomerId));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.AddressTypeCode))) instance.AddressTypeCode = GetString(reader, nameof(AddressSalesReferenceRow.AddressTypeCode));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.Label))) instance.Label = GetString(reader, nameof(AddressSalesReferenceRow.Label));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.Line1))) instance.Line1 = GetString(reader, nameof(AddressSalesReferenceRow.Line1));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.Line2))) instance.Line2 = GetString(reader, nameof(AddressSalesReferenceRow.Line2));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.City))) instance.City = GetString(reader, nameof(AddressSalesReferenceRow.City));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.State))) instance.State = GetString(reader, nameof(AddressSalesReferenceRow.State));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.PostalCode))) instance.PostalCode = GetString(reader, nameof(AddressSalesReferenceRow.PostalCode));
        if (FieldIsValid(reader, nameof(AddressSalesReferenceRow.Country))) instance.Country = GetString(reader, nameof(AddressSalesReferenceRow.Country));

        return instance;
    }
}