// <auto-generated/>
using BeaconAr.Data.Sales.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class CarrierSalesReferenceRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CarrierSalesReferenceRow();
        if (FieldIsValid(reader, nameof(CarrierSalesReferenceRow.Id))) instance.Id = GetInt32(reader, nameof(CarrierSalesReferenceRow.Id));
        if (FieldIsValid(reader, nameof(CarrierSalesReferenceRow.Name))) instance.Name = GetString(reader, nameof(CarrierSalesReferenceRow.Name));
        if (FieldIsValid(reader, nameof(CarrierSalesReferenceRow.IsActive))) instance.IsActive = GetBoolean(reader, nameof(CarrierSalesReferenceRow.IsActive));

        return instance;
    }
}