// <auto-generated/>
using BeaconAr.Data.Sales.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class CustomerSalesReferenceRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new CustomerSalesReferenceRow();
        if (FieldIsValid(reader, nameof(CustomerSalesReferenceRow.Id))) instance.Id = GetInt32(reader, nameof(CustomerSalesReferenceRow.Id));
        if (FieldIsValid(reader, nameof(CustomerSalesReferenceRow.AccountNumber))) instance.AccountNumber = GetString(reader, nameof(CustomerSalesReferenceRow.AccountNumber));
        if (FieldIsValid(reader, nameof(CustomerSalesReferenceRow.Name))) instance.Name = GetString(reader, nameof(CustomerSalesReferenceRow.Name));
        if (FieldIsValid(reader, nameof(CustomerSalesReferenceRow.Email))) instance.Email = GetString(reader, nameof(CustomerSalesReferenceRow.Email));
        if (FieldIsValid(reader, nameof(CustomerSalesReferenceRow.Phone))) instance.Phone = GetString(reader, nameof(CustomerSalesReferenceRow.Phone));
        if (FieldIsValid(reader, nameof(CustomerSalesReferenceRow.IsActive))) instance.IsActive = GetBoolean(reader, nameof(CustomerSalesReferenceRow.IsActive));

        return instance;
    }
}