// <auto-generated/>
using BeaconAr.Data.Sales.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class ProductSalesReferenceRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new ProductSalesReferenceRow();
        if (FieldIsValid(reader, nameof(ProductSalesReferenceRow.Id))) instance.Id = GetInt32(reader, nameof(ProductSalesReferenceRow.Id));
        if (FieldIsValid(reader, nameof(ProductSalesReferenceRow.Sku))) instance.Sku = GetString(reader, nameof(ProductSalesReferenceRow.Sku));
        if (FieldIsValid(reader, nameof(ProductSalesReferenceRow.Name))) instance.Name = GetString(reader, nameof(ProductSalesReferenceRow.Name));
        if (FieldIsValid(reader, nameof(ProductSalesReferenceRow.IsActive))) instance.IsActive = GetBoolean(reader, nameof(ProductSalesReferenceRow.IsActive));

        return instance;
    }
}