// <auto-generated/>
using BeaconAr.Domain.Sales.Entities;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class QuoteViewDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new QuoteView();
        if (FieldIsValid(reader, nameof(QuoteView.Id))) instance.Id = GetInt32(reader, nameof(QuoteView.Id));
        if (FieldIsValid(reader, nameof(QuoteView.QuoteNumber))) instance.QuoteNumber = GetString(reader, nameof(QuoteView.QuoteNumber));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(QuoteView.CustomerId));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerAccountNumber))) instance.CustomerAccountNumber = GetString(reader, nameof(QuoteView.CustomerAccountNumber));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerName))) instance.CustomerName = GetString(reader, nameof(QuoteView.CustomerName));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerIsActive))) instance.CustomerIsActive = GetBoolean(reader, nameof(QuoteView.CustomerIsActive));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressId))) instance.ShippingAddressId = GetInt32(reader, nameof(QuoteView.ShippingAddressId));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressLabel))) instance.ShippingAddressLabel = GetString(reader, nameof(QuoteView.ShippingAddressLabel));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressLine1))) instance.ShippingAddressLine1 = GetString(reader, nameof(QuoteView.ShippingAddressLine1));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressLine2))) instance.ShippingAddressLine2 = GetString(reader, nameof(QuoteView.ShippingAddressLine2));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressCity))) instance.ShippingAddressCity = GetString(reader, nameof(QuoteView.ShippingAddressCity));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressState))) instance.ShippingAddressState = GetString(reader, nameof(QuoteView.ShippingAddressState));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressPostalCode))) instance.ShippingAddressPostalCode = GetString(reader, nameof(QuoteView.ShippingAddressPostalCode));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressCountry))) instance.ShippingAddressCountry = GetString(reader, nameof(QuoteView.ShippingAddressCountry));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressTypeCode))) instance.ShippingAddressTypeCode = GetString(reader, nameof(QuoteView.ShippingAddressTypeCode));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressTypeDisplayName))) instance.ShippingAddressTypeDisplayName = GetString(reader, nameof(QuoteView.ShippingAddressTypeDisplayName));
        if (FieldIsValid(reader, nameof(QuoteView.QuoteDate))) instance.QuoteDate = DateOnly.FromDateTime(GetDateTime(reader, nameof(QuoteView.QuoteDate)));
        if (FieldIsValid(reader, nameof(QuoteView.ValidUntil))) instance.ValidUntil = DateOnly.FromDateTime(GetDateTime(reader, nameof(QuoteView.ValidUntil)));
        if (FieldIsValid(reader, nameof(QuoteView.StatusId))) instance.StatusId = GetInt32(reader, nameof(QuoteView.StatusId));
        if (FieldIsValid(reader, nameof(QuoteView.StatusCode))) instance.StatusCode = GetString(reader, nameof(QuoteView.StatusCode));
        if (FieldIsValid(reader, nameof(QuoteView.StatusDisplayName))) instance.StatusDisplayName = GetString(reader, nameof(QuoteView.StatusDisplayName));
        if (FieldIsValid(reader, nameof(QuoteView.Notes))) instance.Notes = GetString(reader, nameof(QuoteView.Notes));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerAccountNumberSnapshot))) instance.CustomerAccountNumberSnapshot = GetString(reader, nameof(QuoteView.CustomerAccountNumberSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerNameSnapshot))) instance.CustomerNameSnapshot = GetString(reader, nameof(QuoteView.CustomerNameSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerEmailSnapshot))) instance.CustomerEmailSnapshot = GetString(reader, nameof(QuoteView.CustomerEmailSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.CustomerPhoneSnapshot))) instance.CustomerPhoneSnapshot = GetString(reader, nameof(QuoteView.CustomerPhoneSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingLabelSnapshot))) instance.ShippingLabelSnapshot = GetString(reader, nameof(QuoteView.ShippingLabelSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingLine1Snapshot))) instance.ShippingLine1Snapshot = GetString(reader, nameof(QuoteView.ShippingLine1Snapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingLine2Snapshot))) instance.ShippingLine2Snapshot = GetString(reader, nameof(QuoteView.ShippingLine2Snapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingCitySnapshot))) instance.ShippingCitySnapshot = GetString(reader, nameof(QuoteView.ShippingCitySnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingStateSnapshot))) instance.ShippingStateSnapshot = GetString(reader, nameof(QuoteView.ShippingStateSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingPostalCodeSnapshot))) instance.ShippingPostalCodeSnapshot = GetString(reader, nameof(QuoteView.ShippingPostalCodeSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingCountrySnapshot))) instance.ShippingCountrySnapshot = GetString(reader, nameof(QuoteView.ShippingCountrySnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.ShippingAddressTypeCodeSnapshot))) instance.ShippingAddressTypeCodeSnapshot = GetString(reader, nameof(QuoteView.ShippingAddressTypeCodeSnapshot));
        if (FieldIsValid(reader, nameof(QuoteView.Subtotal))) instance.Subtotal = GetDecimal(reader, nameof(QuoteView.Subtotal));
        if (FieldIsValid(reader, nameof(QuoteView.DiscountTotal))) instance.DiscountTotal = GetDecimal(reader, nameof(QuoteView.DiscountTotal));
        if (FieldIsValid(reader, nameof(QuoteView.GrandTotal))) instance.GrandTotal = GetDecimal(reader, nameof(QuoteView.GrandTotal));
        if (FieldIsValid(reader, nameof(QuoteView.SalesOrderId))) instance.SalesOrderId = GetInt32(reader, nameof(QuoteView.SalesOrderId));
        if (FieldIsValid(reader, nameof(QuoteView.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(QuoteView.CreatedByUserId));
        if (FieldIsValid(reader, nameof(QuoteView.CreatedByUserDisplayName))) instance.CreatedByUserDisplayName = GetString(reader, nameof(QuoteView.CreatedByUserDisplayName));
        if (FieldIsValid(reader, nameof(QuoteView.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(QuoteView.CreationDate));
        if (FieldIsValid(reader, nameof(QuoteView.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(QuoteView.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(QuoteView.ModifiedByUserDisplayName))) instance.ModifiedByUserDisplayName = GetString(reader, nameof(QuoteView.ModifiedByUserDisplayName));
        if (FieldIsValid(reader, nameof(QuoteView.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(QuoteView.ModificationDate));
        if (FieldIsValid(reader, nameof(QuoteView.DeletionDate))) instance.DeletionDate = GetDateTimeOffset(reader, nameof(QuoteView.DeletionDate));
        if (FieldIsValid(reader, nameof(QuoteView.DeletedByUserId))) instance.DeletedByUserId = GetInt32(reader, nameof(QuoteView.DeletedByUserId));
        if (FieldIsValid(reader, nameof(QuoteView.DeletedByUserDisplayName))) instance.DeletedByUserDisplayName = GetString(reader, nameof(QuoteView.DeletedByUserDisplayName));
        if (FieldIsValid(reader, nameof(QuoteView.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(QuoteView.RowVersion));

        return instance;
    }
}