// <auto-generated/>
using BeaconAr.Data.Sales.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class SalesOrderSearchRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new SalesOrderSearchRow();
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.Id))) instance.Id = GetInt32(reader, nameof(SalesOrderSearchRow.Id));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.OrderNumber))) instance.OrderNumber = GetString(reader, nameof(SalesOrderSearchRow.OrderNumber));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.SourceQuoteId))) instance.SourceQuoteId = GetInt32(reader, nameof(SalesOrderSearchRow.SourceQuoteId));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(SalesOrderSearchRow.CustomerId));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CustomerAccountNumberSnapshot))) instance.CustomerAccountNumberSnapshot = GetString(reader, nameof(SalesOrderSearchRow.CustomerAccountNumberSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CustomerNameSnapshot))) instance.CustomerNameSnapshot = GetString(reader, nameof(SalesOrderSearchRow.CustomerNameSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.StatusId))) instance.StatusId = GetInt32(reader, nameof(SalesOrderSearchRow.StatusId));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.RequestedShipDate))) instance.RequestedShipDate = GetDateTime(reader, nameof(SalesOrderSearchRow.RequestedShipDate));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CarrierId))) instance.CarrierId = GetInt32(reader, nameof(SalesOrderSearchRow.CarrierId));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CarrierName))) instance.CarrierName = GetString(reader, nameof(SalesOrderSearchRow.CarrierName));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.TrackingNumber))) instance.TrackingNumber = GetString(reader, nameof(SalesOrderSearchRow.TrackingNumber));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.Subtotal))) instance.Subtotal = GetDecimal(reader, nameof(SalesOrderSearchRow.Subtotal));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.DiscountTotal))) instance.DiscountTotal = GetDecimal(reader, nameof(SalesOrderSearchRow.DiscountTotal));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.GrandTotal))) instance.GrandTotal = GetDecimal(reader, nameof(SalesOrderSearchRow.GrandTotal));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(SalesOrderSearchRow.CreatedByUserId));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(SalesOrderSearchRow.CreationDate));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(SalesOrderSearchRow.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(SalesOrderSearchRow.ModificationDate));
        if (FieldIsValid(reader, nameof(SalesOrderSearchRow.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(SalesOrderSearchRow.RowVersion));

        return instance;
    }
}