// <auto-generated/>
using BeaconAr.Domain.Sales.Entities;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Sales.Mappers.DataReaders;

internal partial class SalesOrderViewDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new SalesOrderView();
        if (FieldIsValid(reader, nameof(SalesOrderView.Id))) instance.Id = GetInt32(reader, nameof(SalesOrderView.Id));
        if (FieldIsValid(reader, nameof(SalesOrderView.OrderNumber))) instance.OrderNumber = GetString(reader, nameof(SalesOrderView.OrderNumber));
        if (FieldIsValid(reader, nameof(SalesOrderView.SourceQuoteId))) instance.SourceQuoteId = GetInt32(reader, nameof(SalesOrderView.SourceQuoteId));
        if (FieldIsValid(reader, nameof(SalesOrderView.SourceQuoteNumber))) instance.SourceQuoteNumber = GetString(reader, nameof(SalesOrderView.SourceQuoteNumber));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerId))) instance.CustomerId = GetInt32(reader, nameof(SalesOrderView.CustomerId));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerAccountNumber))) instance.CustomerAccountNumber = GetString(reader, nameof(SalesOrderView.CustomerAccountNumber));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerName))) instance.CustomerName = GetString(reader, nameof(SalesOrderView.CustomerName));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerIsActive))) instance.CustomerIsActive = GetBoolean(reader, nameof(SalesOrderView.CustomerIsActive));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressId))) instance.ShippingAddressId = GetInt32(reader, nameof(SalesOrderView.ShippingAddressId));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressLabel))) instance.ShippingAddressLabel = GetString(reader, nameof(SalesOrderView.ShippingAddressLabel));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressLine1))) instance.ShippingAddressLine1 = GetString(reader, nameof(SalesOrderView.ShippingAddressLine1));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressLine2))) instance.ShippingAddressLine2 = GetString(reader, nameof(SalesOrderView.ShippingAddressLine2));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressCity))) instance.ShippingAddressCity = GetString(reader, nameof(SalesOrderView.ShippingAddressCity));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressState))) instance.ShippingAddressState = GetString(reader, nameof(SalesOrderView.ShippingAddressState));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressPostalCode))) instance.ShippingAddressPostalCode = GetString(reader, nameof(SalesOrderView.ShippingAddressPostalCode));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressCountry))) instance.ShippingAddressCountry = GetString(reader, nameof(SalesOrderView.ShippingAddressCountry));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressTypeCode))) instance.ShippingAddressTypeCode = GetString(reader, nameof(SalesOrderView.ShippingAddressTypeCode));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressTypeDisplayName))) instance.ShippingAddressTypeDisplayName = GetString(reader, nameof(SalesOrderView.ShippingAddressTypeDisplayName));
        if (FieldIsValid(reader, nameof(SalesOrderView.StatusId))) instance.StatusId = GetInt32(reader, nameof(SalesOrderView.StatusId));
        if (FieldIsValid(reader, nameof(SalesOrderView.StatusCode))) instance.StatusCode = GetString(reader, nameof(SalesOrderView.StatusCode));
        if (FieldIsValid(reader, nameof(SalesOrderView.StatusDisplayName))) instance.StatusDisplayName = GetString(reader, nameof(SalesOrderView.StatusDisplayName));
        if (FieldIsValid(reader, nameof(SalesOrderView.RequestedShipDate))) instance.RequestedShipDate = DateOnly.FromDateTime(GetDateTime(reader, nameof(SalesOrderView.RequestedShipDate)));
        if (FieldIsValid(reader, nameof(SalesOrderView.CarrierId))) instance.CarrierId = GetInt32(reader, nameof(SalesOrderView.CarrierId));
        if (FieldIsValid(reader, nameof(SalesOrderView.CarrierCode))) instance.CarrierCode = GetString(reader, nameof(SalesOrderView.CarrierCode));
        if (FieldIsValid(reader, nameof(SalesOrderView.CarrierName))) instance.CarrierName = GetString(reader, nameof(SalesOrderView.CarrierName));
        if (FieldIsValid(reader, nameof(SalesOrderView.CarrierServiceLevel))) instance.CarrierServiceLevel = GetString(reader, nameof(SalesOrderView.CarrierServiceLevel));
        if (FieldIsValid(reader, nameof(SalesOrderView.TrackingNumber))) instance.TrackingNumber = GetString(reader, nameof(SalesOrderView.TrackingNumber));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerAccountNumberSnapshot))) instance.CustomerAccountNumberSnapshot = GetString(reader, nameof(SalesOrderView.CustomerAccountNumberSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerNameSnapshot))) instance.CustomerNameSnapshot = GetString(reader, nameof(SalesOrderView.CustomerNameSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerEmailSnapshot))) instance.CustomerEmailSnapshot = GetString(reader, nameof(SalesOrderView.CustomerEmailSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.CustomerPhoneSnapshot))) instance.CustomerPhoneSnapshot = GetString(reader, nameof(SalesOrderView.CustomerPhoneSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingLabelSnapshot))) instance.ShippingLabelSnapshot = GetString(reader, nameof(SalesOrderView.ShippingLabelSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingLine1Snapshot))) instance.ShippingLine1Snapshot = GetString(reader, nameof(SalesOrderView.ShippingLine1Snapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingLine2Snapshot))) instance.ShippingLine2Snapshot = GetString(reader, nameof(SalesOrderView.ShippingLine2Snapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingCitySnapshot))) instance.ShippingCitySnapshot = GetString(reader, nameof(SalesOrderView.ShippingCitySnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingStateSnapshot))) instance.ShippingStateSnapshot = GetString(reader, nameof(SalesOrderView.ShippingStateSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingPostalCodeSnapshot))) instance.ShippingPostalCodeSnapshot = GetString(reader, nameof(SalesOrderView.ShippingPostalCodeSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingCountrySnapshot))) instance.ShippingCountrySnapshot = GetString(reader, nameof(SalesOrderView.ShippingCountrySnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.ShippingAddressTypeCodeSnapshot))) instance.ShippingAddressTypeCodeSnapshot = GetString(reader, nameof(SalesOrderView.ShippingAddressTypeCodeSnapshot));
        if (FieldIsValid(reader, nameof(SalesOrderView.Subtotal))) instance.Subtotal = GetDecimal(reader, nameof(SalesOrderView.Subtotal));
        if (FieldIsValid(reader, nameof(SalesOrderView.DiscountTotal))) instance.DiscountTotal = GetDecimal(reader, nameof(SalesOrderView.DiscountTotal));
        if (FieldIsValid(reader, nameof(SalesOrderView.GrandTotal))) instance.GrandTotal = GetDecimal(reader, nameof(SalesOrderView.GrandTotal));
        if (FieldIsValid(reader, nameof(SalesOrderView.CreatedByUserId))) instance.CreatedByUserId = GetInt32(reader, nameof(SalesOrderView.CreatedByUserId));
        if (FieldIsValid(reader, nameof(SalesOrderView.CreatedByUserDisplayName))) instance.CreatedByUserDisplayName = GetString(reader, nameof(SalesOrderView.CreatedByUserDisplayName));
        if (FieldIsValid(reader, nameof(SalesOrderView.CreationDate))) instance.CreationDate = GetDateTimeOffset(reader, nameof(SalesOrderView.CreationDate));
        if (FieldIsValid(reader, nameof(SalesOrderView.ModifiedByUserId))) instance.ModifiedByUserId = GetInt32(reader, nameof(SalesOrderView.ModifiedByUserId));
        if (FieldIsValid(reader, nameof(SalesOrderView.ModifiedByUserDisplayName))) instance.ModifiedByUserDisplayName = GetString(reader, nameof(SalesOrderView.ModifiedByUserDisplayName));
        if (FieldIsValid(reader, nameof(SalesOrderView.ModificationDate))) instance.ModificationDate = GetDateTimeOffset(reader, nameof(SalesOrderView.ModificationDate));
        if (FieldIsValid(reader, nameof(SalesOrderView.DeletionDate))) instance.DeletionDate = GetDateTimeOffset(reader, nameof(SalesOrderView.DeletionDate));
        if (FieldIsValid(reader, nameof(SalesOrderView.DeletedByUserId))) instance.DeletedByUserId = GetInt32(reader, nameof(SalesOrderView.DeletedByUserId));
        if (FieldIsValid(reader, nameof(SalesOrderView.DeletedByUserDisplayName))) instance.DeletedByUserDisplayName = GetString(reader, nameof(SalesOrderView.DeletedByUserDisplayName));
        if (FieldIsValid(reader, nameof(SalesOrderView.RowVersion))) instance.RowVersion = GetBytes(reader, nameof(SalesOrderView.RowVersion));

        return instance;
    }
}