// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;

namespace BeaconAr.Data.Access.Mappers;

public static class AccessStoredProcedureMappersRegisterer
{
    public static void RegisterMappers()
    {
        RegisterDataReaderMappers();
        RegisterSqlParameterMappers();
    }

    private static void RegisterDataReaderMappers()
    {

    }

    private static void RegisterSqlParameterMappers()
    {
        SqlParameterMapperFactory.RegisterMapper<Data.Access.StoredProcedures.GetOrCreateApplicationUserParameters>(() => new SqlParameters.GetOrCreateApplicationUserParametersMapper());

    }
}