// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;

namespace BeaconAr.Data.Mappers;

public static class StoreProcedureMappersRegisterer
{
    public static void RegisterMappers()
    {
        RegisterDataReaderMappers();
        RegisterSqlParameterMappers();
    }

    private static void RegisterDataReaderMappers()
    {
        DataReaderMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.AddressSearchRow>(() => new DataReaders.AddressSearchRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CarrierSearchRow>(() => new DataReaders.CarrierSearchRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CustomerSearchRow>(() => new DataReaders.CustomerSearchRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.ProductSearchRow>(() => new DataReaders.ProductSearchRowDataReaderMapper());

    }

    private static void RegisterSqlParameterMappers()
    {
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.AddressSearchParameters>(() => new SqlParameters.AddressSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CarrierSearchParameters>(() => new SqlParameters.CarrierSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CustomerSearchParameters>(() => new SqlParameters.CustomerSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.ProductSearchParameters>(() => new SqlParameters.ProductSearchParametersMapper());

    }
}