// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;

namespace BeaconAr.Data.Mappers;

public static class StoreProcedureMappersRegisterer
{
    public static void RegisterMappers()
    {
        RegisterDataReaderMappers();
        RegisterSqlParameterMappers();
    }

    private static void RegisterDataReaderMappers()
    {
        DataReaderMapperFactory.RegisterMapper<Data.Reporting.StoredProcedures.DashboardRow>(() => new DataReaders.DashboardRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.QuoteSearchRow>(() => new DataReaders.QuoteSearchRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.SalesOrderSearchRow>(() => new DataReaders.SalesOrderSearchRowDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.Receivables.Entities.CarrierView>(() => new DataReaders.CarrierViewDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.Receivables.Entities.CustomerAddressView>(() => new DataReaders.CustomerAddressViewDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.Receivables.Entities.CustomerView>(() => new DataReaders.CustomerViewDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.Receivables.Entities.ProductView>(() => new DataReaders.ProductViewDataReaderMapper());

    }

    private static void RegisterSqlParameterMappers()
    {
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.AddressSearchParameters>(() => new SqlParameters.AddressSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CarrierSearchParameters>(() => new SqlParameters.CarrierSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CustomerSearchParameters>(() => new SqlParameters.CustomerSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.ProductSearchParameters>(() => new SqlParameters.ProductSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Reporting.StoredProcedures.DashboardParameters>(() => new SqlParameters.DashboardParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.QuoteSearchParameters>(() => new SqlParameters.QuoteSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.Sales.StoredProcedures.SalesOrderSearchParameters>(() => new SqlParameters.SalesOrderSearchParametersMapper());

    }
}