// <auto-generated/>
using BeaconAr.Data.Operations.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;
using System.Data;

namespace BeaconAr.Data.Operations.Mappers.DataReaders;

internal partial class DashboardRowDataReaderMapper : DataReaderMapperBase
{
    public override object Map(IDataReader reader)
    {
        LoadReaderFields(reader);

        var instance = new DashboardRow();
        if (FieldIsValid(reader, nameof(DashboardRow.Products))) instance.Products = GetInt64(reader, nameof(DashboardRow.Products));
        if (FieldIsValid(reader, nameof(DashboardRow.Customers))) instance.Customers = GetInt64(reader, nameof(DashboardRow.Customers));
        if (FieldIsValid(reader, nameof(DashboardRow.Carriers))) instance.Carriers = GetInt64(reader, nameof(DashboardRow.Carriers));
        if (FieldIsValid(reader, nameof(DashboardRow.OpenQuotes))) instance.OpenQuotes = GetInt64(reader, nameof(DashboardRow.OpenQuotes));
        if (FieldIsValid(reader, nameof(DashboardRow.ActiveOrders))) instance.ActiveOrders = GetInt64(reader, nameof(DashboardRow.ActiveOrders));
        if (FieldIsValid(reader, nameof(DashboardRow.AsOf))) instance.AsOf = GetDateTimeOffset(reader, nameof(DashboardRow.AsOf));

        return instance;
    }
}