<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Paradigm.Enterprise.Domain" Version="$(ParadigmEnterpriseVersion)" />
    <PackageReference Include="Paradigm.Enterprise.Interfaces" Version="$(ParadigmEnterpriseVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExampleApp.Interfaces\ExampleApp.Interfaces.csproj" />
  </ItemGroup>

</Project>
