// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures;
using Paradigm.Enterprise.Data.StoredProcedures.Mappers;

namespace BeaconAr.Data.MasterData.Mappers;

public static class MasterDataStoredProcedureMappersRegisterer
{
    public static void RegisterMappers()
    {
        RegisterDataReaderMappers();
        RegisterSqlParameterMappers();
    }

    private static void RegisterDataReaderMappers()
    {
        DataReaderMapperFactory.RegisterMapper<Domain.MasterData.Entities.CarrierView>(() => new DataReaders.CarrierViewDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.MasterData.Entities.CustomerAddressView>(() => new DataReaders.CustomerAddressViewDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.MasterData.Entities.CustomerView>(() => new DataReaders.CustomerViewDataReaderMapper());
        DataReaderMapperFactory.RegisterMapper<Domain.MasterData.Entities.ProductView>(() => new DataReaders.ProductViewDataReaderMapper());

    }

    private static void RegisterSqlParameterMappers()
    {
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.AddressSearchParameters>(() => new SqlParameters.AddressSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CarrierSearchParameters>(() => new SqlParameters.CarrierSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.CustomerSearchParameters>(() => new SqlParameters.CustomerSearchParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.HasAddressReferencesParameters>(() => new SqlParameters.HasAddressReferencesParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.HasCarrierReferencesParameters>(() => new SqlParameters.HasCarrierReferencesParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.HasCustomerReferencesParameters>(() => new SqlParameters.HasCustomerReferencesParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.HasProductReferencesParameters>(() => new SqlParameters.HasProductReferencesParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.LockCustomerForAddressMutationParameters>(() => new SqlParameters.LockCustomerForAddressMutationParametersMapper());
        SqlParameterMapperFactory.RegisterMapper<Data.MasterData.StoredProcedures.ProductSearchParameters>(() => new SqlParameters.ProductSearchParametersMapper());

    }
}