<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Paradigm.Enterprise.Providers" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BeaconAr.Data\BeaconAr.Data.csproj" />
	</ItemGroup>

</Project>
