// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Domain.Access.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;

namespace BeaconAr.Data.Access.Context;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class AccessDbContext : DbContextBase<int>
{
    public AccessDbContext(IServiceProvider serviceProvider, DbContextOptions<AccessDbContext> options)
        : base(serviceProvider, options)
    {
    }

    public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }

    public virtual DbSet<ApplicationUserView> ApplicationUserViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<ApplicationUser>(entity =>
        {
            entity.ToTable("ApplicationUser");

            entity.HasIndex(e => e.Email, "IX_ApplicationUser_Email").HasFilter("([Email] IS NOT NULL)");

            entity.HasIndex(e => new { e.Issuer, e.Subject }, "UQ_ApplicationUser_Issuer_Subject").IsUnique();

            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_ApplicationUser_IsActive");
            entity.Property(e => e.Issuer)
                .HasMaxLength(400)
                .UseCollation("Latin1_General_100_BIN2");
            entity.Property(e => e.Subject)
                .HasMaxLength(200)
                .UseCollation("Latin1_General_100_BIN2");

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.InverseCreatedByUser).HasForeignKey(d => d.CreatedByUserId);

            entity.HasOne(d => d.ModifiedByUser).WithMany(p => p.InverseModifiedByUser).HasForeignKey(d => d.ModifiedByUserId);
        });

        modelBuilder.Entity<ApplicationUserView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ApplicationUserView");

            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.DisplayName).HasMaxLength(200);
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.Issuer)
                .HasMaxLength(400)
                .UseCollation("Latin1_General_100_BIN2");
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Subject)
                .HasMaxLength(200)
                .UseCollation("Latin1_General_100_BIN2");
        });
        modelBuilder.HasSequence("QuoteNumberSequence");
        modelBuilder.HasSequence("SalesOrderNumberSequence");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
