// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Operations.StoredProcedures;

namespace BeaconAr.Data.Operations.Mappers.SqlParameters;

internal partial class LockIdempotencyRequestParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is LockIdempotencyRequestParameters instance)) return;

        AddSqlParameter(nameof(LockIdempotencyRequestParameters.UserId), instance.UserId);
        AddSqlParameter(nameof(LockIdempotencyRequestParameters.Operation), instance.Operation);
        AddSqlParameter(nameof(LockIdempotencyRequestParameters.KeyHash), instance.KeyHash);

    }
}