// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using BeaconAr.Domain.Sales.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;

namespace BeaconAr.Data.Sales.Context;

[System.CodeDom.Compiler.GeneratedCode("EFCorePowerTools", "10.1.1386")]
public partial class SalesDbContext : DbContextBase<int>
{
    public SalesDbContext(IServiceProvider serviceProvider, DbContextOptions<SalesDbContext> options)
        : base(serviceProvider, options)
    {
    }

    public virtual DbSet<Quote> Quotes { get; set; }

    public virtual DbSet<QuoteLine> QuoteLines { get; set; }

    public virtual DbSet<QuoteLineView> QuoteLineViews { get; set; }

    public virtual DbSet<QuotePricingView> QuotePricingViews { get; set; }

    public virtual DbSet<QuoteStatus> QuoteStatuses { get; set; }

    public virtual DbSet<QuoteStatusHistory> QuoteStatusHistories { get; set; }

    public virtual DbSet<QuoteView> QuoteViews { get; set; }

    public virtual DbSet<SalesOrder> SalesOrders { get; set; }

    public virtual DbSet<SalesOrderLine> SalesOrderLines { get; set; }

    public virtual DbSet<SalesOrderLineView> SalesOrderLineViews { get; set; }

    public virtual DbSet<SalesOrderPricingView> SalesOrderPricingViews { get; set; }

    public virtual DbSet<SalesOrderStatus> SalesOrderStatuses { get; set; }

    public virtual DbSet<SalesOrderStatusHistory> SalesOrderStatusHistories { get; set; }

    public virtual DbSet<SalesOrderView> SalesOrderViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<Quote>(entity =>
        {
            entity.ToTable("Quote");

            entity.HasIndex(e => new { e.CustomerId, e.Id }, "IX_Quote_CustomerId_Id");

            entity.HasIndex(e => new { e.StatusId, e.QuoteDate, e.Id }, "IX_Quote_StatusId_QuoteDate_Id");

            entity.HasIndex(e => new { e.ValidUntil, e.Id }, "IX_Quote_ValidUntil_Id");

            entity.HasIndex(e => e.QuoteNumber, "UQ_Quote_QuoteNumber").IsUnique();

            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QuoteNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);

            entity.HasOne(d => d.Status).WithMany(p => p.Quotes)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Quote_QuoteStatus");
        });

        modelBuilder.Entity<QuoteLine>(entity =>
        {
            entity.ToTable("QuoteLine");

            entity.HasIndex(e => new { e.QuoteId, e.Id }, "IX_QuoteLine_QuoteId_Id");

            entity.HasIndex(e => new { e.QuoteId, e.ProductId }, "UQ_QuoteLine_QuoteId_ProductId").IsUnique();

            entity.Property(e => e.DiscountAmount)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))-round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");

            entity.HasOne(d => d.Quote).WithMany(p => p.QuoteLines)
                .HasForeignKey(d => d.QuoteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteLine_Quote");
        });

        modelBuilder.Entity<QuoteLineView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("QuoteLineView");

            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ProductName).HasMaxLength(120);
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.ProductSku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.QuoteNumber).HasMaxLength(20);
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });

        modelBuilder.Entity<QuotePricingView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("QuotePricingView");

            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
        });

        modelBuilder.Entity<QuoteStatus>(entity =>
        {
            entity.ToTable("QuoteStatus");

            entity.HasIndex(e => e.Code, "UQ_QuoteStatus_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_QuoteStatus_IsActive");
        });

        modelBuilder.Entity<QuoteStatusHistory>(entity =>
        {
            entity.ToTable("QuoteStatusHistory");

            entity.HasIndex(e => new { e.QuoteId, e.CreationDate, e.Id }, "IX_QuoteStatusHistory_QuoteId_CreationDate_Id");

            entity.HasOne(d => d.Quote).WithMany(p => p.QuoteStatusHistories)
                .HasForeignKey(d => d.QuoteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteStatusHistory_Quote");

            entity.HasOne(d => d.Status).WithMany(p => p.QuoteStatusHistories)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuoteStatusHistory_QuoteStatus");
        });

        modelBuilder.Entity<QuoteView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("QuoteView");

            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CustomerAccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerName).HasMaxLength(120);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.DeletedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.Notes).HasMaxLength(1000);
            entity.Property(e => e.QuoteNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressCity).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressCountry)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingAddressLabel).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressLine1).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressLine2).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressPostalCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressState).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressTypeCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeDisplayName).HasMaxLength(100);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);
            entity.Property(e => e.StatusCode).HasMaxLength(32);
            entity.Property(e => e.StatusDisplayName).HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
        });

        modelBuilder.Entity<SalesOrder>(entity =>
        {
            entity.ToTable("SalesOrder");

            entity.HasIndex(e => new { e.CustomerId, e.Id }, "IX_SalesOrder_CustomerId_Id");

            entity.HasIndex(e => new { e.RequestedShipDate, e.Id }, "IX_SalesOrder_RequestedShipDate_Id");

            entity.HasIndex(e => new { e.StatusId, e.Id }, "IX_SalesOrder_StatusId_Id");

            entity.HasIndex(e => e.TrackingNumber, "IX_SalesOrder_TrackingNumber").HasFilter("([TrackingNumber] IS NOT NULL)");

            entity.HasIndex(e => e.OrderNumber, "UQ_SalesOrder_OrderNumber").IsUnique();

            entity.HasIndex(e => e.SourceQuoteId, "UQ_SalesOrder_SourceQuoteId")
                .IsUnique()
                .HasFilter("([SourceQuoteId] IS NOT NULL)");

            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.OrderNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);
            entity.Property(e => e.TrackingNumber).HasMaxLength(200);

            entity.HasOne(d => d.SourceQuote).WithOne(p => p.SalesOrder)
                .HasForeignKey<SalesOrder>(d => d.SourceQuoteId)
                .HasConstraintName("FK_SalesOrder_Quote");

            entity.HasOne(d => d.Status).WithMany(p => p.SalesOrders)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrder_SalesOrderStatus");
        });

        modelBuilder.Entity<SalesOrderLine>(entity =>
        {
            entity.ToTable("SalesOrderLine");

            entity.HasIndex(e => new { e.SalesOrderId, e.Id }, "IX_SalesOrderLine_SalesOrderId_Id");

            entity.HasIndex(e => new { e.SalesOrderId, e.ProductId }, "UQ_SalesOrderLine_SalesOrderId_ProductId").IsUnique();

            entity.Property(e => e.DiscountAmount)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal)
                .HasComputedColumnSql("(CONVERT([decimal](19,2),round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))-round((round(CONVERT([decimal](38,6),[Quantity])*[UnitPrice],(2))*[DiscountPercent])/(100),(2))))", true)
                .HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesOrderLines)
                .HasForeignKey(d => d.SalesOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderLine_SalesOrder");
        });

        modelBuilder.Entity<SalesOrderLineView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SalesOrderLineView");

            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.DiscountPercent).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.LineSubtotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.LineTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.OrderNumber).HasMaxLength(20);
            entity.Property(e => e.ProductName).HasMaxLength(120);
            entity.Property(e => e.ProductNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.ProductSku)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.SkuSnapshot).HasMaxLength(32);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(19, 4)");
        });

        modelBuilder.Entity<SalesOrderPricingView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SalesOrderPricingView");

            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
        });

        modelBuilder.Entity<SalesOrderStatus>(entity =>
        {
            entity.ToTable("SalesOrderStatus");

            entity.HasIndex(e => e.Code, "UQ_SalesOrderStatus_Code").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(32);
            entity.Property(e => e.DisplayName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_SalesOrderStatus_IsActive");
        });

        modelBuilder.Entity<SalesOrderStatusHistory>(entity =>
        {
            entity.ToTable("SalesOrderStatusHistory");

            entity.HasIndex(e => new { e.SalesOrderId, e.CreationDate, e.Id }, "IX_SalesOrderStatusHistory_SalesOrderId_CreationDate_Id");

            entity.HasOne(d => d.SalesOrder).WithMany(p => p.SalesOrderStatusHistories)
                .HasForeignKey(d => d.SalesOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderStatusHistory_SalesOrder");

            entity.HasOne(d => d.Status).WithMany(p => p.SalesOrderStatusHistories)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SalesOrderStatusHistory_SalesOrderStatus");
        });

        modelBuilder.Entity<SalesOrderView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SalesOrderView");

            entity.Property(e => e.CarrierCode)
                .HasMaxLength(32)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CarrierName).HasMaxLength(120);
            entity.Property(e => e.CarrierServiceLevel).HasMaxLength(120);
            entity.Property(e => e.CreatedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.CustomerAccountNumber)
                .HasMaxLength(50)
                .UseCollation("Latin1_General_100_CI_AS_SC");
            entity.Property(e => e.CustomerAccountNumberSnapshot).HasMaxLength(50);
            entity.Property(e => e.CustomerEmailSnapshot).HasMaxLength(320);
            entity.Property(e => e.CustomerName).HasMaxLength(120);
            entity.Property(e => e.CustomerNameSnapshot).HasMaxLength(120);
            entity.Property(e => e.CustomerPhoneSnapshot).HasMaxLength(50);
            entity.Property(e => e.DeletedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.DiscountTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.GrandTotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.ModifiedByUserDisplayName).HasMaxLength(200);
            entity.Property(e => e.OrderNumber).HasMaxLength(20);
            entity.Property(e => e.RowVersion)
                .IsRowVersion()
                .IsConcurrencyToken();
            entity.Property(e => e.ShippingAddressCity).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressCountry)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingAddressLabel).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressLine1).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressLine2).HasMaxLength(200);
            entity.Property(e => e.ShippingAddressPostalCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressState).HasMaxLength(120);
            entity.Property(e => e.ShippingAddressTypeCode).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingAddressTypeDisplayName).HasMaxLength(100);
            entity.Property(e => e.ShippingCitySnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingCountrySnapshot)
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.ShippingLabelSnapshot).HasMaxLength(120);
            entity.Property(e => e.ShippingLine1Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingLine2Snapshot).HasMaxLength(200);
            entity.Property(e => e.ShippingPostalCodeSnapshot).HasMaxLength(32);
            entity.Property(e => e.ShippingStateSnapshot).HasMaxLength(120);
            entity.Property(e => e.SourceQuoteNumber).HasMaxLength(20);
            entity.Property(e => e.StatusCode).HasMaxLength(32);
            entity.Property(e => e.StatusDisplayName).HasMaxLength(100);
            entity.Property(e => e.Subtotal).HasColumnType("decimal(19, 2)");
            entity.Property(e => e.TrackingNumber).HasMaxLength(200);
        });
        modelBuilder.HasSequence("QuoteNumberSequence");
        modelBuilder.HasSequence("SalesOrderNumberSequence");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
