using System.Xml.Linq;
using BeaconAr.CodeGenerator;
using BeaconAr.Data.Access.Context;
using BeaconAr.Data.MasterData.Context;
using BeaconAr.Data.Operations.Context;
using BeaconAr.Data.Sales.Context;
using BeaconAr.Domain.Access.Entities;
using BeaconAr.Domain.MasterData.Entities;
using BeaconAr.Domain.Operations.Entities;
using BeaconAr.Domain.Sales.Entities;
using BeaconAr.Interfaces.Access.Entities;
using BeaconAr.Interfaces.MasterData.Entities;
using BeaconAr.Interfaces.Operations.Entities;
using BeaconAr.Interfaces.Sales.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;
using Paradigm.Enterprise.Data.Repositories;
using Paradigm.Enterprise.Domain.Repositories;
using Paradigm.Enterprise.Providers;
using System.Reflection;

namespace BeaconAr.Architecture.Tests;

[TestClass]
public sealed class EstablishedLayerBoundaryTests
{
    #region Nested Types

    private sealed class EmptyServiceProvider : IServiceProvider
    {
        public static EmptyServiceProvider Instance { get; } = new();

        public object? GetService(Type serviceType) => null;
    }

    private sealed class AuditMetadataFixture
    {
        public int Id { get; set; }
    }

    #endregion

    #region Public Methods

    [TestMethod]
    public void ProjectReferencesFollowTheInwardDependencyGraph()
    {
        var root = FindExampleRoot();
        AssertReferences(root, "BeaconAr.Domain", "BeaconAr.Interfaces", "BeaconAr.InterfaceGenerator");
        AssertReferences(root, "BeaconAr.Data", "BeaconAr.Domain");
        AssertReferences(root, "BeaconAr.Providers", "BeaconAr.Data");
        AssertReferences(root, "BeaconAr.WebApi", "BeaconAr.Data", "BeaconAr.Domain", "BeaconAr.Providers", "BeaconAr.ServiceDefaults");
    }

    [TestMethod]
    public void DomainDoesNotReferenceHostOrConcreteDatabasePackages()
    {
        var root = FindExampleRoot();
        var projectText = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Domain", "BeaconAr.Domain.csproj"));
        Assert.IsFalse(projectText.Contains("Microsoft.AspNetCore", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("SqlServer", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("BeaconAr.WebApi", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("BeaconAr.AppHost", StringComparison.Ordinal));
    }

    [TestMethod]
    public void DatabaseFirstTemplatesUseCurrentParadigmGenericContracts()
    {
        var root = FindExampleRoot();
        var contextTemplate = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "DbContext.t4"));
        var entityTemplate = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "EntityType.t4"));
        var interfaceGenerator = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.InterfaceGenerator", "EntityInterfaceGenerator.cs"));
        var provenance = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "PROVENANCE.md"));

        StringAssert.Contains(contextTemplate, "Model.GetEntityTypes()");
        StringAssert.Contains(contextTemplate, "entityType.FindProperty(\"CreationDate\")");
        StringAssert.Contains(contextTemplate, "entityType.FindProperty(\"ModificationDate\")");
        StringAssert.Contains(contextTemplate, "entityType.FindProperty(\"CreatedByUserId\")");
        StringAssert.Contains(contextTemplate, "entityType.FindProperty(\"ModifiedByUserId\")");
        StringAssert.Contains(contextTemplate, "DbContextBase<<#= auditActorIdTypeName #>>");
        Assert.IsFalse(contextTemplate.Contains("DbContextBase<int>", StringComparison.Ordinal));
        StringAssert.Contains(entityTemplate, "EntityBase<{idTypeName}, I");
        StringAssert.Contains(entityTemplate, "IAuditableEntity<DateTimeOffset, {auditActorIdTypeName}>");
        StringAssert.Contains(entityTemplate, "createdByUserIdClrType != modifiedByUserIdClrType");
        StringAssert.Contains(entityTemplate, "audit actor identifier types must match");
        Assert.IsFalse(entityTemplate.Contains("aggregateNavigations", StringComparison.Ordinal));
        Assert.IsFalse(entityTemplate.Contains("DomainTracker<", StringComparison.Ordinal));
        StringAssert.Contains(contextTemplate, "This file has been auto generated by EF Core Power Tools");
        StringAssert.Contains(entityTemplate, "This file has been auto generated by EF Core Power Tools");
        StringAssert.Contains(interfaceGenerator, "FindMappedEntityBase");
        StringAssert.Contains(interfaceGenerator, "Paradigm.Enterprise.Interfaces.IEntity<");
        StringAssert.Contains(provenance, "522906b9151d566a5dddd2609b66da36726368a7");
        StringAssert.Contains(provenance, "0EE9962D4D4757EB4DD7C3234597577A511EFD8610341078ED4C3408251BB8BE");
        StringAssert.Contains(provenance, "70E703CC0E043B0C8441A1B8B9E126FD961E69E352DCE31F27D2E3B2AAC78049");
        foreach (string applicationSpecificToken in new[] { "publicEntityViewNames", "BeaconAr", "Quote", "SalesOrder", "CustomerAddress" })
        {
            Assert.IsFalse(entityTemplate.Contains(applicationSpecificToken, StringComparison.Ordinal), applicationSpecificToken);
            Assert.IsFalse(contextTemplate.Contains(applicationSpecificToken, StringComparison.Ordinal), applicationSpecificToken);
        }
    }

    [TestMethod]
    public void GeneratedPersistenceBoundaryRepresentsTheFoundationSchema()
    {
        var root = FindExampleRoot();
        string domainRoot = Path.Combine(root, "src", "BeaconAr.Domain");
        string[] capabilities = ["Access", "MasterData", "Operations", "Sales"];
        var entityFiles = capabilities.SelectMany(capability =>
                Directory.GetFiles(Path.Combine(domainRoot, capability, "Entities"), "*.cs", SearchOption.TopDirectoryOnly))
            .Where(path => File.ReadLines(path).First().StartsWith("// <auto-generated>", StringComparison.Ordinal))
            .ToArray();
        string context = string.Join(Environment.NewLine, capabilities.Select(capability => File.ReadAllText(Path.Combine(
            root, "src", "BeaconAr.Data", capability, "Context", $"{capability}DbContext.cs"))));

        Assert.HasCount(31, entityFiles);
        Assert.AreEqual(31, CountOccurrences(context, "DbSet<"));
        Assert.AreEqual(12, CountOccurrences(context, ".IsRowVersion()"));
        Assert.AreEqual(14, CountOccurrences(context, ".HasNoKey()"));
        Assert.IsFalse(context.Contains(".HasForeignKey(d => new { d.CustomerId, d.ShippingAddressId })", StringComparison.Ordinal));
        StringAssert.Contains(context, ".HasComputedColumnSql(");
        Assert.IsFalse(context.Contains("Server=", StringComparison.OrdinalIgnoreCase));
        Assert.IsTrue(entityFiles.All(path => File.ReadLines(path).First() ==
            "// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>"));
    }

    [TestMethod]
    public void EntityAndViewPairsShareGeneratedScalarContracts()
    {
        AssertSharedContract<IApplicationUser, ApplicationUser, ApplicationUserView>();
        AssertSharedContract<ICarrier, Carrier, CarrierView>();
        AssertSharedContract<ICustomer, Customer, CustomerView>();
        AssertSharedContract<ICustomerAddress, CustomerAddress, CustomerAddressView>();
        AssertSharedContract<IProduct, Product, ProductView>();
        AssertSharedContract<IQuote, Quote, QuoteView>();
        AssertSharedContract<IQuoteLine, QuoteLine, QuoteLineView>();
        AssertSharedContract<ISalesOrder, SalesOrder, SalesOrderView>();
        AssertSharedContract<ISalesOrderLine, SalesOrderLine, SalesOrderLineView>();
        AssertSharedContract<IAuditLog, AuditLog, AuditLogView>();
        AssertSharedContract<IIdempotencyRequest, IdempotencyRequest, IdempotencyRequestView>();
        AssertSharedContract<IIdempotencyState, IdempotencyState, IdempotencyStateView>();
    }

    [TestMethod]
    public void AggregateTrackersRespectDomainPartialOwnership()
    {
        var root = FindExampleRoot();
        var quoteBehavior = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Domain", "Sales", "Entities", "Quote.Behavior.cs"));
        var orderBehavior = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Domain", "Sales", "Entities", "SalesOrder.Behavior.cs"));

        StringAssert.Contains(quoteBehavior, "QuoteLinesDomainTracker");
        StringAssert.Contains(orderBehavior, "SalesOrderLinesDomainTracker");
        Assert.IsNotNull(typeof(Quote).GetProperty("QuoteLinesDomainTracker"));
        Assert.IsNotNull(typeof(SalesOrder).GetProperty("SalesOrderLinesDomainTracker"));
        Assert.IsNull(typeof(Product).GetProperty("QuoteLinesDomainTracker"));
        Assert.IsNull(typeof(ApplicationUser).GetProperty("QuoteCreatedByUsersDomainTracker"));
    }

    [TestMethod]
    public void GeneratedViewsAreKeylessDatabaseProjectionsAndContextUsesParadigmBase()
    {
        using var access = new AccessDbContext(EmptyServiceProvider.Instance, Options<AccessDbContext>());
        using var masterData = new MasterDataDbContext(EmptyServiceProvider.Instance, Options<MasterDataDbContext>());
        using var operations = new OperationsDbContext(EmptyServiceProvider.Instance, Options<OperationsDbContext>());
        using var sales = new SalesDbContext(EmptyServiceProvider.Instance, Options<SalesDbContext>());
        (Type View, DbContext Context)[] generatedViews =
        [
            (typeof(ApplicationUserView), access),
            (typeof(CarrierView), masterData), (typeof(CustomerView), masterData), (typeof(CustomerAddressView), masterData),
            (typeof(ProductView), masterData), (typeof(AuditLogView), operations),
            (typeof(IdempotencyRequestView), operations), (typeof(IdempotencyStateView), operations),
            (typeof(QuoteView), sales), (typeof(QuoteLineView), sales), (typeof(SalesOrderView), sales),
            (typeof(SalesOrderLineView), sales), (typeof(QuotePricingView), sales), (typeof(SalesOrderPricingView), sales),
        ];
        foreach ((Type viewType, DbContext context) in generatedViews)
        {
            var metadata = context.Model.FindEntityType(viewType);
            Assert.IsNotNull(metadata, viewType.Name);
            Assert.IsNull(metadata.FindPrimaryKey(), viewType.Name);
            Assert.AreEqual(viewType.Name, metadata.GetViewName(), viewType.Name);
        }

        foreach (DbContext context in new DbContext[] { access, masterData, operations, sales })
            Assert.IsInstanceOfType<DbContextBase<int>>(context);
        AssertContextConstructor<AccessDbContext>();
        AssertContextConstructor<MasterDataDbContext>();
        AssertContextConstructor<OperationsDbContext>();
        AssertContextConstructor<SalesDbContext>();
        Assert.AreEqual(typeof(long), typeof(AuditLogView).GetProperty("Id")?.PropertyType);
        Assert.AreEqual(typeof(long), typeof(IdempotencyRequestView).GetProperty("Id")?.PropertyType);
        Assert.IsTrue(typeof(Paradigm.Enterprise.Interfaces.IEntity<long>).IsAssignableFrom(typeof(IAuditLog)));
        Assert.IsTrue(typeof(Paradigm.Enterprise.Interfaces.IEntity<long>).IsAssignableFrom(typeof(IIdempotencyRequest)));
    }

    [TestMethod]
    public void OperationsPersistenceViewsStayOutsideTheHttpContract()
    {
        string root = FindExampleRoot();
        string controllerSource = string.Join(Environment.NewLine,
            Directory.GetFiles(Path.Combine(root, "src", "BeaconAr.WebApi", "Controllers"), "*.cs", SearchOption.AllDirectories)
                .Select(File.ReadAllText));
        string serializerSource = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.WebApi", "Serialization", "BeaconArApiJsonContext.cs"));
        string[] forbidden =
        [
            nameof(AuditLogView), nameof(IdempotencyRequestView), nameof(IdempotencyStateView),
            nameof(IdempotencyRequestView.KeyHash), nameof(IdempotencyRequestView.RequestHash), nameof(AuditLogView.MetadataJson),
        ];

        foreach (string name in forbidden)
        {
            Assert.IsFalse(controllerSource.Contains(name, StringComparison.Ordinal), name);
            Assert.IsFalse(serializerSource.Contains(name, StringComparison.Ordinal), name);
        }
    }

    [TestMethod]
    public void AuditIdentifierTemplateRulesCoverIntLongAndMismatchedMetadata()
    {
        Assert.AreEqual(typeof(int), ResolveAuditActorIdType(typeof(int), typeof(int)));
        Assert.AreEqual(typeof(long), ResolveAuditActorIdType(typeof(long), typeof(long)));
        Assert.ThrowsExactly<InvalidOperationException>(() => ResolveAuditActorIdType(typeof(int), typeof(long)));
        Assert.IsFalse(typeof(Paradigm.Enterprise.Interfaces.IAuditableEntity<int>).IsAssignableFrom(typeof(AuditLog)));
    }

    [TestMethod]
    public void CustomerAddressOwnershipMetadataIsOneToMany()
    {
        using var context = new MasterDataDbContext(EmptyServiceProvider.Instance, Options<MasterDataDbContext>());

        var entityType = context.Model.FindEntityType(typeof(CustomerAddress));
        Assert.IsNotNull(entityType);
        var relationship = entityType.GetForeignKeys().Single(foreignKey => foreignKey.GetConstraintName() == "FK_CustomerAddress_Customer");
        Assert.IsFalse(relationship.IsUnique);
        Assert.IsNotNull(relationship.PrincipalToDependent);
        Assert.IsTrue(relationship.PrincipalToDependent.IsCollection);
        Assert.AreEqual("CustomerAddresses", relationship.PrincipalToDependent.Name);
        foreach (var indexName in new[] { "UQ_CustomerAddress_CustomerId_DefaultBilling", "UQ_CustomerAddress_CustomerId_DefaultShipping" })
        {
            var filteredIndex = entityType.GetIndexes().Single(index => index.GetDatabaseName() == indexName);
            Assert.IsTrue(filteredIndex.IsUnique);
            Assert.IsFalse(string.IsNullOrWhiteSpace(filteredIndex.GetFilter()));
        }

        var customer = new Customer();
        context.AddRange(
            new CustomerAddress { Customer = customer },
            new CustomerAddress { Customer = customer });
        var addresses = relationship.PrincipalToDependent.PropertyInfo?.GetValue(customer) as ICollection<CustomerAddress>;
        Assert.IsNotNull(addresses);
        Assert.HasCount(2, addresses);
    }

    [TestMethod]
    public void FoundationGeneratorRejectsUnknownTargetsAndHasNoDeferredProxyConfiguration()
    {
        var root = FindExampleRoot();
        var settings = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.CodeGenerator", "appsettings.json"));

        Assert.Throws<ArgumentException>(() => GenerationTargets.Parse(["proxy"]));
        Assert.IsFalse(settings.Contains("proxiesGenerator", StringComparison.Ordinal));
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.CodeGenerator", "Generators", "ProxiesGenerator.cs")));
    }

    [TestMethod]
    public void WebApiPreservesOpenTelemetryLoggingProvider()
    {
        var root = FindExampleRoot();
        var program = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.WebApi", "Program.cs"));

        Assert.IsFalse(program.Contains("ClearProviders", StringComparison.Ordinal));
    }

    [TestMethod]
    public void ApplicationRepositoriesAndProvidersFollowDiscoveryNames()
    {
        Type[] repositoryTypes = typeof(BeaconAr.Data.MasterData.Repositories.ProductRepository).Assembly.GetTypes()
            .Where(type => type.IsPublic && !type.IsAbstract && typeof(IRepository).IsAssignableFrom(type))
            .ToArray();
        Type[] providerTypes = typeof(BeaconAr.Providers.MasterData.ProductProvider).Assembly.GetTypes()
            .Where(type => type.IsPublic && !type.IsAbstract && typeof(IProvider).IsAssignableFrom(type))
            .ToArray();

        Assert.HasCount(17, repositoryTypes);
        Assert.HasCount(10, providerTypes);
        foreach (Type implementation in repositoryTypes.Concat(providerTypes))
        {
            Type[] exactInterfaces = implementation.GetInterfaces()
                .Where(contract => contract.Name == $"I{implementation.Name}")
                .ToArray();
            Assert.HasCount(1, exactInterfaces, implementation.FullName);
        }
    }

    [TestMethod]
    public void MasterDataCrudUsesOfficialTypedBasesAndGeneratedViews()
    {
        Assert.IsTrue(typeof(IEditRepository<Product, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.IProductRepository)));
        Assert.IsTrue(typeof(IEditRepository<Customer, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.ICustomerRepository)));
        Assert.IsTrue(typeof(IEditRepository<CustomerAddress, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.IAddressRepository)));
        Assert.IsTrue(typeof(IEditRepository<Carrier, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.ICarrierRepository)));

        Assert.AreEqual(typeof(EditRepositoryBase<Product, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.ProductRepository).BaseType);
        Assert.AreEqual(typeof(EditRepositoryBase<Customer, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.CustomerRepository).BaseType);
        Assert.AreEqual(typeof(EditRepositoryBase<CustomerAddress, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.AddressRepository).BaseType);
        Assert.AreEqual(typeof(EditRepositoryBase<Carrier, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.CarrierRepository).BaseType);

        Assert.AreEqual(typeof(ReadRepositoryBase<ProductView, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.ProductViewRepository).BaseType);
        Assert.AreEqual(typeof(ReadRepositoryBase<CustomerView, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.CustomerViewRepository).BaseType);
        Assert.AreEqual(typeof(ReadRepositoryBase<CustomerAddressView, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.AddressViewRepository).BaseType);
        Assert.AreEqual(typeof(ReadRepositoryBase<CarrierView, MasterDataDbContext, int>), typeof(BeaconAr.Data.MasterData.Repositories.CarrierViewRepository).BaseType);

        Assert.IsTrue(typeof(IEditProvider<ProductView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.IProductProvider)));
        Assert.IsTrue(typeof(IEditProvider<CustomerView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.ICustomerProvider)));
        Assert.IsTrue(typeof(IEditProvider<CustomerAddressView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.IAddressProvider)));
        Assert.IsTrue(typeof(IEditProvider<CarrierView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.ICarrierProvider)));

        Assert.AreEqual(
            typeof(EditProviderBase<IProduct, Product, ProductView, BeaconAr.Domain.MasterData.Repositories.IProductRepository,
                BeaconAr.Domain.MasterData.Repositories.IProductViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.ProductProvider).BaseType);
        Assert.AreEqual(
            typeof(EditProviderBase<ICustomer, Customer, CustomerView, BeaconAr.Domain.MasterData.Repositories.ICustomerRepository,
                BeaconAr.Domain.MasterData.Repositories.ICustomerViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.CustomerProvider).BaseType);
        Assert.AreEqual(
            typeof(EditProviderBase<ICustomerAddress, CustomerAddress, CustomerAddressView,
                BeaconAr.Domain.MasterData.Repositories.IAddressRepository,
                BeaconAr.Domain.MasterData.Repositories.IAddressViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.AddressProvider).BaseType);
        Assert.AreEqual(
            typeof(EditProviderBase<ICarrier, Carrier, CarrierView, BeaconAr.Domain.MasterData.Repositories.ICarrierRepository,
                BeaconAr.Domain.MasterData.Repositories.ICarrierViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.CarrierProvider).BaseType);
    }

    [TestMethod]
    public void MasterDataRepositoriesAndProvidersUseGeneratedViewsWithoutCompatibilityDtos()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data", "MasterData", "Repositories");
        string providerRoot = Path.Combine(root, "src", "BeaconAr.Providers", "MasterData");
        var boundaries = new[]
        {
            ("Product", "ProductViews"),
            ("Customer", "CustomerViews"),
            ("Address", "CustomerAddressViews"),
            ("Carrier", "CarrierViews"),
        };

        foreach ((string name, string dbSet) in boundaries)
        {
            string repository = File.ReadAllText(Path.Combine(dataRoot, $"{name}ViewRepository.cs"));
            StringAssert.Contains(repository, $"EntityContext.{dbSet}.AsNoTracking()");
            Assert.IsFalse(repository.Contains($"{name}Dto", StringComparison.Ordinal));

            string provider = File.ReadAllText(Path.Combine(providerRoot, $"{name}Provider.cs"));
            Assert.IsFalse(provider.Contains("ToDto(", StringComparison.Ordinal));
            Assert.IsFalse(provider.Contains($"{name}Dto", StringComparison.Ordinal));
        }

        foreach (string repositoryPath in Directory.GetFiles(dataRoot, "*Repository.cs", SearchOption.TopDirectoryOnly))
        {
            string repository = File.ReadAllText(repositoryPath);
            Assert.IsFalse(repository.Contains("CommitChangesAsync", StringComparison.Ordinal), repositoryPath);
        }
    }

    [TestMethod]
    public void ProvidersDoNotReintroduceLocalProviderBaseClasses()
    {
        string root = FindExampleRoot();
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.Providers", "MasterData", "MasterDataProviderBase.cs")));
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.Providers", "Sales", "SalesProviderBase.cs")));
        Assert.AreEqual(typeof(object), typeof(BeaconAr.Providers.Sales.QuoteProvider).BaseType);
        Assert.AreEqual(typeof(object), typeof(BeaconAr.Providers.Sales.SalesOrderProvider).BaseType);
        Assert.AreEqual(typeof(object), typeof(BeaconAr.Providers.Sales.QuoteConversionProvider).BaseType);
    }

    [TestMethod]
    public void ProvidersDoNotClassifyConcreteDatabaseDriverExceptions()
    {
        string root = FindExampleRoot();
        string providerRoot = Path.Combine(root, "src", "BeaconAr.Providers");
        foreach (string path in Directory.GetFiles(providerRoot, "*.cs", SearchOption.AllDirectories))
        {
            string source = File.ReadAllText(path);
            Assert.IsFalse(source.Contains("Microsoft.Data.SqlClient", StringComparison.Ordinal), path);
            Assert.IsFalse(source.Contains("Microsoft.EntityFrameworkCore", StringComparison.Ordinal), path);
        }

        string classifier = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "Operations",
            "IdempotencyPersistenceErrorClassifier.cs"));
        StringAssert.Contains(classifier, "UQ_IdempotencyRequest_UserId_Operation_KeyHash");
    }

    [TestMethod]
    public void OfficialMasterDataMutationsRemainExplicitlyGuardedUntilTheTransportConcurrencyContractExists()
    {
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.ProductProvider, ProductView>();
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.CustomerProvider, CustomerView>();
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.AddressProvider, CustomerAddressView>();
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.CarrierProvider, CarrierView>();
    }

    [TestMethod]
    public void MasterDataSearchesMaterializeGeneratedViewsInOneProcedureRoundTrip()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data", "MasterData", "Repositories");
        string databaseRoot = Path.Combine(root, "src", "database", "routines", "MasterData");
        var boundaries = new[]
        {
            ("Product", "ProductView", "CreatedByUserDisplayName"),
            ("Customer", "CustomerView", "CreatedByUserDisplayName"),
            ("Address", "CustomerAddressView", "CustomerAccountNumber"),
            ("Carrier", "CarrierView", "CreatedByUserDisplayName"),
        };

        foreach ((string name, string view, string expandedField) in boundaries)
        {
            string repository = File.ReadAllText(Path.Combine(dataRoot, $"{name}ViewRepository.cs"));
            StringAssert.Contains(repository, "GetSearchPaginatedFunction");
            Assert.IsFalse(repository.Contains("Dictionary<", StringComparison.Ordinal));
            Assert.IsFalse(repository.Contains("ids.Contains", StringComparison.Ordinal));

            string procedure = File.ReadAllText(Path.Combine(databaseRoot, $"Search{name}.sql"));
            StringAssert.Contains(procedure, $"[dbo].[{view}]");
            StringAssert.Contains(procedure, expandedField);
        }
    }

    [TestMethod]
    public void MasterDataProcedureViewMappersHaveOneGeneratedOwner()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data");
        string generatedMapperRoot = Path.Combine(dataRoot, "MasterData", "Mappers", "DataReaders");
        string registerer = File.ReadAllText(Path.Combine(dataRoot, "MasterData", "Mappers", "MasterDataStoredProcedureMappersRegisterer.cs"));
        var boundaries = new[]
        {
            (Procedure: "Product", View: "ProductView", ObsoleteRow: "ProductSearchRow"),
            (Procedure: "Customer", View: "CustomerView", ObsoleteRow: "CustomerSearchRow"),
            (Procedure: "Address", View: "CustomerAddressView", ObsoleteRow: "AddressSearchRow"),
            (Procedure: "Carrier", View: "CarrierView", ObsoleteRow: "CarrierSearchRow"),
        };

        foreach ((string procedure, string view, string obsoleteRow) in boundaries)
        {
            string wrapper = File.ReadAllText(Path.Combine(
                dataRoot, "MasterData", "StoredProcedures", $"Search{procedure}Procedure.cs"));
            StringAssert.Contains(wrapper, $"List<{view}>");
            Assert.IsFalse(File.Exists(Path.Combine(
                dataRoot, "MasterData", "StoredProcedures", $"{obsoleteRow}.cs")));

            string generatedMapper = File.ReadAllText(Path.Combine(generatedMapperRoot, $"{view}DataReaderMapper.cs"));
            StringAssert.StartsWith(generatedMapper, "// <auto-generated/>");
            StringAssert.Contains(generatedMapper, $"internal partial class {view}DataReaderMapper");
            StringAssert.Contains(registerer,
                $"DataReaderMapperFactory.RegisterMapper<Domain.MasterData.Entities.{view}>(() => new DataReaders.{view}DataReaderMapper());");
            Assert.IsFalse(registerer.Contains(obsoleteRow, StringComparison.Ordinal));
        }

        Assert.IsFalse(Directory.Exists(Path.Combine(dataRoot, "Mappers")), "The obsolete top-level mapper bundle must not return.");

        string generatorRoot = Path.Combine(root, "src", "BeaconAr.CodeGenerator");
        string generator = File.ReadAllText(Path.Combine(generatorRoot, "Generators", "StoredProcedureMapperGenerator.cs"));
        string configuration = File.ReadAllText(Path.Combine(generatorRoot, "appsettings.json"));
        StringAssert.Contains(generator, "using var output = new AtomicOutputDirectory(Path.Combine(outputPath, capabilityGroup.Key, \"Mappers\"))");
        StringAssert.Contains(generator, "OrderBy(static type => type.FullName ?? type.Name, StringComparer.Ordinal)");
        StringAssert.Contains(configuration, "../BeaconAr.Data");
        Assert.AreEqual(1, CountOccurrences(configuration, "dataReaderMapperGenerator"));
    }

    [TestMethod]
    public void WorkflowCoordinatorIsScopedAndConstructorInjected()
    {
        string root = FindExampleRoot();
        string program = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.WebApi", "Program.cs"));
        StringAssert.Contains(program, "AddScoped<SalesWorkflowCoordinator>()");

        Type coordinator = typeof(BeaconAr.Providers.Sales.SalesWorkflowCoordinator);
        Assert.IsTrue(coordinator.IsPublic);
        Assert.AreEqual(1, coordinator.GetConstructors(BindingFlags.Public | BindingFlags.Instance).Length);
        Assert.AreEqual(0, coordinator.GetProperties(BindingFlags.Public | BindingFlags.Instance |
            BindingFlags.Static | BindingFlags.DeclaredOnly).Length);
        Assert.AreEqual(0, coordinator.GetMethods(BindingFlags.Public | BindingFlags.Instance |
            BindingFlags.Static | BindingFlags.DeclaredOnly).Length);

        foreach (string propertyName in new[]
                 {
                     "ErrorClassifier", "PersistenceSession", "UnitOfWork", "UserId", "UtcNow",
                 })
        {
            PropertyInfo? property = coordinator.GetProperty(propertyName,
                BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            Assert.IsNotNull(property, propertyName);
            Assert.IsTrue(property.GetMethod?.IsAssembly, propertyName);
        }

        foreach (string methodName in new[]
                 {
                     "ExecuteAsync", "EnsureVersion", "AddAudit", "NotFound", "InvalidReference",
                 })
        {
            MethodInfo? method = coordinator.GetMethods(BindingFlags.NonPublic | BindingFlags.Instance |
                    BindingFlags.Static | BindingFlags.DeclaredOnly)
                .SingleOrDefault(candidate => candidate.Name == methodName);
            Assert.IsNotNull(method, methodName);
            Assert.IsTrue(method.IsAssembly, methodName);
        }

        foreach (Type provider in new[]
                 {
                     typeof(BeaconAr.Providers.Sales.QuoteProvider),
                     typeof(BeaconAr.Providers.Sales.SalesOrderProvider),
                     typeof(BeaconAr.Providers.Sales.QuoteConversionProvider),
                 })
        {
            Assert.IsTrue(provider.GetConstructors().Single().GetParameters().Any(parameter => parameter.ParameterType == coordinator));
            string source = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Providers", "Sales", $"{provider.Name}.cs"));
            Assert.IsFalse(source.Contains("new SalesWorkflowCoordinator", StringComparison.Ordinal));
        }
    }

    [TestMethod]
    public void DatabaseProjectFoldersAndVisualStudioIdentityStayAligned()
    {
        const string projectGuid = "A09E027B-4428-49A6-9A92-C43CF35D9206";
        string root = FindExampleRoot();
        string project = File.ReadAllText(Path.Combine(root, "src", "database", "BeaconAr.Database.sqlproj"));
        XDocument document = XDocument.Parse(project);
        Assert.AreEqual($"{{{projectGuid}}}", document.Descendants("ProjectGuid").Single().Value.ToUpperInvariant());
        Assert.AreEqual("True", document.Descendants("TargetDatabaseSet").Single().Value);
        StringAssert.Contains(project, "<Folder Include=\"tables\\MasterData\\\" />");
        StringAssert.Contains(project, "<Folder Include=\"views\\MasterData\\\" />");
        StringAssert.Contains(project, "<Folder Include=\"routines\\MasterData\\\" />");
    }

    [TestMethod]
    public void SolutionUsesTheCanonicalResponsibilityBasedLayout()
    {
        string root = FindExampleRoot();
        string solutionPath = Path.Combine(root, "BeaconAr.slnx");
        XDocument solution = XDocument.Load(solutionPath);
        string[] expectedFolders =
        [
            "/00.SolutionItems/",
            "/01.Shared/",
            "/02.Modules/",
            "/03.Hosts/",
            "/04.Tools/",
            "/05.Tests/",
        ];
        string[] expectedSolutionItems =
        [
            ".config/dotnet-tools.json",
            ".env.example",
            ".gitattributes",
            ".gitignore",
            "aspire.config.json",
            "Directory.Build.props",
            "Directory.Packages.props",
            "global.json",
        ];
        Dictionary<string, string> expectedProjects = new(StringComparer.OrdinalIgnoreCase)
        {
            ["src/BeaconAr.ServiceDefaults/BeaconAr.ServiceDefaults.csproj"] = "/01.Shared/",
            ["src/BeaconAr.Interfaces/BeaconAr.Interfaces.csproj"] = "/02.Modules/",
            ["src/BeaconAr.Domain/BeaconAr.Domain.csproj"] = "/02.Modules/",
            ["src/BeaconAr.Data/BeaconAr.Data.csproj"] = "/02.Modules/",
            ["src/BeaconAr.Providers/BeaconAr.Providers.csproj"] = "/02.Modules/",
            ["src/database/BeaconAr.Database.sqlproj"] = "/02.Modules/",
            ["src/BeaconAr.WebApi/BeaconAr.WebApi.csproj"] = "/03.Hosts/",
            ["src/BeaconAr.AppHost/BeaconAr.AppHost.csproj"] = "/03.Hosts/",
            ["src/BeaconAr.CodeGenerator/BeaconAr.CodeGenerator.csproj"] = "/04.Tools/",
            ["src/BeaconAr.DatabaseBootstrap/BeaconAr.DatabaseBootstrap.csproj"] = "/04.Tools/",
            ["src/BeaconAr.InterfaceGenerator/BeaconAr.InterfaceGenerator.csproj"] = "/04.Tools/",
            ["tests/BeaconAr.Domain.Tests/BeaconAr.Domain.Tests.csproj"] = "/05.Tests/",
            ["tests/BeaconAr.Architecture.Tests/BeaconAr.Architecture.Tests.csproj"] = "/05.Tests/",
            ["tests/BeaconAr.Database.IntegrationTests/BeaconAr.Database.IntegrationTests.csproj"] = "/05.Tests/",
            ["tests/BeaconAr.DatabaseBootstrap.Tests/BeaconAr.DatabaseBootstrap.Tests.csproj"] = "/05.Tests/",
            ["tests/BeaconAr.Providers.Tests/BeaconAr.Providers.Tests.csproj"] = "/05.Tests/",
            ["tests/BeaconAr.WebApi.Tests/BeaconAr.WebApi.Tests.csproj"] = "/05.Tests/",
        };

        XElement solutionRoot = solution.Root ?? throw new AssertFailedException("BeaconAr.slnx has no root element.");
        XElement[] folders = solutionRoot.Descendants("Folder").ToArray();
        CollectionAssert.AreEquivalent(expectedFolders, folders.Select(folder => (string?)folder.Attribute("Name")).ToArray(),
            "BeaconAr.slnx must contain exactly the six canonical solution folders.");
        Assert.IsTrue(folders.All(folder => folder.Parent == solutionRoot),
            "Canonical solution folders must be direct children of the solution root.");

        XElement solutionItems = folders.Single(folder => (string?)folder.Attribute("Name") == "/00.SolutionItems/");
        string[] actualSolutionItems = solutionItems.Elements("File")
            .Select(file => ((string?)file.Attribute("Path") ?? string.Empty).Replace('\\', '/'))
            .ToArray();
        CollectionAssert.AreEquivalent(expectedSolutionItems, actualSolutionItems,
            "00.SolutionItems must expose the example's checked-in governing configuration.");
        Assert.AreEqual(expectedSolutionItems.Length, solutionRoot.Descendants("File").Count(),
            "Configuration files must not appear outside 00.SolutionItems.");
        foreach (string solutionItem in expectedSolutionItems)
        {
            Assert.IsTrue(File.Exists(Path.Combine(root, solutionItem.Replace('/', Path.DirectorySeparatorChar))),
                $"Solution item '{solutionItem}' does not resolve from the example root.");
        }

        XElement[] projectElements = solutionRoot.Descendants("Project").ToArray();
        Assert.AreEqual(expectedProjects.Count, projectElements.Length,
            "BeaconAr.slnx must contain every existing project exactly once.");
        string[] projectPaths = projectElements
            .Select(project => ((string?)project.Attribute("Path") ?? string.Empty).Replace('\\', '/'))
            .ToArray();
        string[] duplicateProjectPaths = projectPaths
            .GroupBy(path => path, StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToArray();
        Assert.AreEqual(0, duplicateProjectPaths.Length,
            $"Solution projects must be unique. Duplicates: {string.Join(", ", duplicateProjectPaths)}");

        Dictionary<string, string> actualProjects = projectElements.ToDictionary(
            project => ((string?)project.Attribute("Path") ?? string.Empty).Replace('\\', '/'),
            project => (string?)project.Parent?.Attribute("Name") ?? string.Empty,
            StringComparer.OrdinalIgnoreCase);
        CollectionAssert.AreEquivalent(expectedProjects.Keys.ToArray(), actualProjects.Keys.ToArray(),
            "BeaconAr.slnx project membership differs from the canonical inventory.");
        foreach ((string projectPath, string expectedFolder) in expectedProjects)
        {
            Assert.AreEqual(expectedFolder, actualProjects[projectPath], true,
                $"Project '{projectPath}' is assigned to the wrong solution folder.");
            Assert.IsTrue(File.Exists(Path.Combine(root, projectPath.Replace('/', Path.DirectorySeparatorChar))),
                $"Solution project '{projectPath}' does not resolve from the example root.");
        }

        Assert.AreEqual("/02.Modules/", actualProjects["src/database/BeaconAr.Database.sqlproj"],
            "The SQL Server schema belongs to 02.Modules, not the tools folder.");
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.sln")),
            "The legacy solution must stay retired so solution definitions cannot drift.");
    }

    [TestMethod]
    public void MasterDataContractsDoNotLeakInfrastructureOrPersistenceEntities()
    {
        Type[] contracts = typeof(BeaconAr.Domain.MasterData.Contracts.ProductCreateRequest).Assembly.GetTypes()
            .Where(type => type.Namespace?.StartsWith("BeaconAr.Domain.MasterData", StringComparison.Ordinal) == true)
            .ToArray();
        foreach (Type contract in contracts)
        {
            IEnumerable<Type> exposedTypes = contract.GetMethods().SelectMany(method =>
                method.GetParameters().Select(parameter => parameter.ParameterType).Append(method.ReturnType));
            Assert.IsFalse(exposedTypes.Any(type => type == typeof(IQueryable) ||
                type.Namespace?.StartsWith("Microsoft.EntityFrameworkCore", StringComparison.Ordinal) == true ||
                type.Namespace?.StartsWith("Microsoft.Data.SqlClient", StringComparison.Ordinal) == true), contract.FullName);
        }

        Type persistenceNamespaceMarker = typeof(Product);
        foreach (Type provider in typeof(BeaconAr.Providers.MasterData.ProductProvider).Assembly.GetTypes()
                     .Where(type => type.IsPublic && typeof(IProvider).IsAssignableFrom(type)))
        {
            Assert.IsFalse(provider.GetMethods().Any(method => method.ReturnType == persistenceNamespaceMarker ||
                method.GetParameters().Any(parameter => parameter.ParameterType == persistenceNamespaceMarker)), provider.FullName);
        }
    }

    [TestMethod]
    public void SalesWorkflowBoundariesStayTransportNeutralAndAggregateOwned()
    {
        Type[] providers = typeof(BeaconAr.Providers.Sales.QuoteProvider).Assembly.GetTypes()
            .Where(type => type.Namespace?.StartsWith("BeaconAr.Providers.Sales", StringComparison.Ordinal) == true)
            .ToArray();
        Assert.IsFalse(providers.Any(type => type.GetMethods().Any(method =>
            method.ReturnType.Namespace?.StartsWith("Microsoft.AspNetCore", StringComparison.Ordinal) == true ||
            method.GetParameters().Any(parameter =>
                parameter.ParameterType.Namespace?.StartsWith("Microsoft.AspNetCore", StringComparison.Ordinal) == true))));

        Type[] repositories = typeof(BeaconAr.Data.Sales.Repositories.QuoteRepository).Assembly.GetTypes()
            .Where(type => typeof(IRepository).IsAssignableFrom(type) && type.IsPublic)
            .ToArray();
        Assert.IsFalse(repositories.Any(type => type.Name.Contains("LineRepository", StringComparison.Ordinal) ||
            type.Name.Contains("StatusHistoryRepository", StringComparison.Ordinal)));

        Type[] providerContracts = typeof(BeaconAr.Providers.Sales.IQuoteProvider).Assembly.GetTypes()
            .Where(type => type.IsInterface && type.Namespace?.StartsWith("BeaconAr.Providers.Sales", StringComparison.Ordinal) == true)
            .ToArray();
        Assert.IsFalse(providerContracts.SelectMany(type => type.GetMethods()).Any(method =>
            method.ReturnType == typeof(Quote) || method.ReturnType == typeof(SalesOrder) ||
            method.GetParameters().Any(parameter => parameter.ParameterType == typeof(Quote) ||
                parameter.ParameterType == typeof(SalesOrder))));
    }

    [TestMethod]
    public void SalesDatabaseRoutinesDeclareBoundedConsistentContracts()
    {
        string root = FindExampleRoot();
        string quoteSearch = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Sales", "SearchQuote.sql"));
        string orderSearch = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Sales", "SearchSalesOrder.sql"));
        string dashboard = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Operations", "GetDashboardSummary.sql"));

        foreach (string search in new[] { quoteSearch, orderSearch })
        {
            StringAssert.Contains(search, "SELECT COUNT(1)");
            StringAssert.Contains(search, "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
            StringAssert.Contains(search, "BEGIN TRANSACTION");
            StringAssert.Contains(search, "COMMIT TRANSACTION");
            StringAssert.Contains(search, "ROLLBACK TRANSACTION");
            StringAssert.Contains(search, "OFFSET ((CONVERT(BIGINT, @PageNumber) - 1) * @PageSize)");
            StringAssert.Contains(search, "[DeletionDate] IS NULL");
            StringAssert.Contains(search, "THROW 50002");
            Assert.IsFalse(search.Contains("EXEC(", StringComparison.OrdinalIgnoreCase));
            Assert.IsFalse(search.Contains("sp_executesql", StringComparison.OrdinalIgnoreCase));
        }

        StringAssert.Contains(dashboard, "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
        StringAssert.Contains(dashboard, "COUNT_BIG");
        StringAssert.Contains(dashboard, "SYSUTCDATETIME()");
        StringAssert.Contains(dashboard, "IF XACT_STATE() <> 0 ROLLBACK TRANSACTION");
    }

    #endregion

    #region Private Methods

    private static DbContextOptions<TContext> Options<TContext>() where TContext : DbContext =>
        new DbContextOptionsBuilder<TContext>()
            .UseSqlServer("Server=metadata-only;Initial Catalog=BeaconAr;Integrated Security=True;Encrypt=True")
            .Options;

    private static void AssertContextConstructor<TContext>() where TContext : DbContext =>
        Assert.IsNotNull(typeof(TContext).GetConstructor([typeof(IServiceProvider), typeof(DbContextOptions<TContext>)]));

    private static void AssertReferences(string root, string project, params string[] expected)
    {
        var document = XDocument.Load(Path.Combine(root, "src", project, $"{project}.csproj"));
        var references = document.Descendants("ProjectReference")
            .Select(static item => Path.GetFileNameWithoutExtension(item.Attribute("Include")?.Value))
            .Where(static item => item is not null)
            .ToArray();
        CollectionAssert.AreEquivalent(expected, references!);
    }

    private static Type ResolveAuditActorIdType(Type createdByUserIdType, Type modifiedByUserIdType)
    {
        var modelBuilder = new ModelBuilder();
        var fixture = modelBuilder.Entity<AuditMetadataFixture>();
        fixture.Property(createdByUserIdType, "CreatedByUserId");
        fixture.Property(modifiedByUserIdType, "ModifiedByUserId");
        Type[] actorIdTypes = modelBuilder.Model.GetEntityTypes()
            .SelectMany(entityType => new[]
            {
                entityType.FindProperty("CreatedByUserId")?.ClrType,
                entityType.FindProperty("ModifiedByUserId")?.ClrType,
            })
            .Where(static type => type is not null)
            .Select(static type => Nullable.GetUnderlyingType(type!) ?? type!)
            .Distinct()
            .ToArray();

        return actorIdTypes.Length == 1
            ? actorIdTypes[0]
            : throw new InvalidOperationException("Audit actor identifier metadata must resolve to one type.");
    }

    private static void AssertSharedContract<TContract, TEntity, TView>()
        where TEntity : TContract
        where TView : TContract
    {
        var nullability = new NullabilityInfoContext();
        PropertyInfo[] entityProperties = typeof(TEntity)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Where(static property => IsScalar(property.PropertyType))
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .ToArray();
        PropertyInfo[] contractProperties = typeof(TContract)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .ToArray();

        CollectionAssert.AreEqual(
            entityProperties.Select(static property => property.Name).ToArray(),
            contractProperties.Select(static property => property.Name).ToArray(),
            $"{typeof(TContract).Name} must declare the exact scalar surface of {typeof(TEntity).Name}.");

        foreach (PropertyInfo contractProperty in contractProperties)
        {
            var entityProperty = typeof(TEntity).GetProperty(contractProperty.Name);
            var viewProperty = typeof(TView).GetProperty(contractProperty.Name);
            Assert.IsNotNull(entityProperty, $"{typeof(TEntity).Name}.{contractProperty.Name}");
            Assert.IsNotNull(viewProperty, $"{typeof(TView).Name}.{contractProperty.Name}");
            Assert.IsNotNull(contractProperty.GetMethod, $"{typeof(TContract).Name}.{contractProperty.Name} getter");
            Assert.IsNull(contractProperty.SetMethod, $"{typeof(TContract).Name}.{contractProperty.Name} must be getter-only.");
            Assert.AreEqual(contractProperty.PropertyType, entityProperty.PropertyType, contractProperty.Name);
            Assert.AreEqual(contractProperty.PropertyType, viewProperty.PropertyType, contractProperty.Name);
            NullabilityState contractNullability = nullability.Create(contractProperty).ReadState;
            Assert.AreEqual(contractNullability, nullability.Create(entityProperty).ReadState,
                $"Entity nullability differs for {typeof(TContract).Name}.{contractProperty.Name}.");
            Assert.AreEqual(contractNullability, nullability.Create(viewProperty).ReadState,
                $"View nullability differs for {typeof(TContract).Name}.{contractProperty.Name}.");
        }
    }

    private static void AssertOfficialMutationsAreDeclared<TProvider, TView>()
    {
        Type provider = typeof(TProvider);
        Type view = typeof(TView);
        Type list = typeof(List<>).MakeGenericType(view);
        Type enumerableView = typeof(IEnumerable<>).MakeGenericType(view);
        Type enumerableId = typeof(IEnumerable<int>);
        var operations = new[]
        {
            ("AddAsync", new[] { view }),
            ("AddAsync", new[] { list }),
            ("UpdateAsync", new[] { view }),
            ("UpdateAsync", new[] { list }),
            ("SaveAsync", new[] { view }),
            ("SaveAsync", new[] { enumerableView }),
            ("DeleteAsync", new[] { typeof(int) }),
            ("DeleteAsync", new[] { enumerableId }),
        };

        foreach ((string name, Type[] parameters) in operations)
        {
            MethodInfo? method = provider.GetMethod(name, parameters);
            Assert.IsNotNull(method, $"{provider.Name}.{name}");
            Assert.AreEqual(provider, method.DeclaringType, $"{provider.Name}.{name} must explicitly guard the official overload.");
        }
    }

    private static bool IsScalar(Type type)
    {
        Type scalarType = Nullable.GetUnderlyingType(type) ?? type;
        return scalarType.IsEnum ||
               scalarType.IsPrimitive ||
               scalarType == typeof(string) ||
               scalarType == typeof(decimal) ||
               scalarType == typeof(DateOnly) ||
               scalarType == typeof(DateTime) ||
               scalarType == typeof(DateTimeOffset) ||
               scalarType == typeof(Guid) ||
               scalarType == typeof(TimeOnly) ||
               scalarType == typeof(TimeSpan) ||
               scalarType == typeof(byte[]);
    }

    private static int CountOccurrences(string text, string value) =>
        (text.Length - text.Replace(value, string.Empty, StringComparison.Ordinal).Length) / value.Length;

    private static string FindExampleRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "aspire.config.json")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new DirectoryNotFoundException("Beacon AR example root not found.");
    }

    #endregion
}
