using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Reflection;
using System.Text.Json;
using BeaconAr.Data.Access.Context;
using BeaconAr.Data.MasterData.Context;
using BeaconAr.Data.Operations.Context;
using BeaconAr.Data.Sales.Context;
using BeaconAr.Domain.Access.Entities;
using BeaconAr.Domain.MasterData.Entities;
using BeaconAr.Domain.Operations.Entities;
using BeaconAr.Domain.Sales.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace BeaconAr.Architecture.Tests;

[TestClass]
public sealed class GeneratedPersistenceTests
{
    #region Public Methods

    [TestMethod]
    public void FourConfigsOwnTheCompleteDisjointPersistenceInventory()
    {
        string dataRoot = Path.Combine(FindExampleRoot(), "src", "BeaconAr.Data");
        Dictionary<string, string[]> expected = new(StringComparer.Ordinal)
        {
            ["Access"] = ["[dbo].[ApplicationUser]", "[dbo].[ApplicationUserView]"],
            ["MasterData"] = ["[dbo].[AddressType]", "[dbo].[Carrier]", "[dbo].[Customer]", "[dbo].[CustomerAddress]", "[dbo].[Product]", "[dbo].[CarrierView]", "[dbo].[CustomerView]", "[dbo].[CustomerAddressView]", "[dbo].[ProductView]"],
            ["Operations"] = ["[dbo].[AuditLog]", "[dbo].[IdempotencyRequest]", "[dbo].[IdempotencyState]", "[dbo].[AuditLogView]", "[dbo].[IdempotencyRequestView]", "[dbo].[IdempotencyStateView]"],
            ["Sales"] = ["[dbo].[Quote]", "[dbo].[QuoteLine]", "[dbo].[QuoteStatus]", "[dbo].[QuoteStatusHistory]", "[dbo].[SalesOrder]", "[dbo].[SalesOrderLine]", "[dbo].[SalesOrderStatus]", "[dbo].[SalesOrderStatusHistory]", "[dbo].[QuoteView]", "[dbo].[QuoteLineView]", "[dbo].[QuotePricingView]", "[dbo].[SalesOrderView]", "[dbo].[SalesOrderLineView]", "[dbo].[SalesOrderPricingView]"],
        };
        var all = new List<string>();
        foreach ((string capability, string[] objects) in expected)
        {
            string config = Path.Combine(dataRoot, $"efcpt-{capability.ToLowerInvariant()}-config.json");
            using JsonDocument document = JsonDocument.Parse(File.ReadAllText(config));
            string[] actual = document.RootElement.GetProperty("tables").EnumerateArray()
                .Concat(document.RootElement.GetProperty("views").EnumerateArray())
                .Select(item => item.GetProperty("name").GetString()!).ToArray();
            CollectionAssert.AreEqual(objects, actual, capability);
            all.AddRange(actual);
        }
        Assert.HasCount(17, all.Where(name => !name.EndsWith("View]", StringComparison.Ordinal)).ToArray());
        Assert.HasCount(14, all.Where(name => name.EndsWith("View]", StringComparison.Ordinal)).ToArray());
        Assert.HasCount(31, all.Distinct(StringComparer.Ordinal).ToArray());
    }

    [TestMethod]
    public void GeneratedFilesTypesAndInterfacesHaveExactCapabilityOwnership()
    {
        Dictionary<string, string[]> files = GeneratedFileManifest();
        string root = FindExampleRoot();
        Assembly domain = typeof(Product).Assembly;
        foreach ((string capability, string[] names) in files)
        {
            string entityRoot = Path.Combine(root, "src", "BeaconAr.Domain", capability, "Entities");
            string[] actual = Directory.GetFiles(entityRoot, "*.cs")
                .Where(path => File.ReadLines(path).First().StartsWith("// <auto-generated>", StringComparison.Ordinal))
                .Select(Path.GetFileNameWithoutExtension).Order(StringComparer.Ordinal).ToArray()!;
            CollectionAssert.AreEqual(names.Order(StringComparer.Ordinal).ToArray(), actual, capability);
            foreach (string name in names)
                Assert.IsNotNull(domain.GetType($"BeaconAr.Domain.{capability}.Entities.{name}"), $"{capability}.{name}");
        }

        string[] expectedInterfaces =
        [
            "BeaconAr.Interfaces.Access.Entities.IApplicationUser",
            "BeaconAr.Interfaces.MasterData.Entities.ICarrier", "BeaconAr.Interfaces.MasterData.Entities.ICustomer",
            "BeaconAr.Interfaces.MasterData.Entities.ICustomerAddress", "BeaconAr.Interfaces.MasterData.Entities.IProduct",
            "BeaconAr.Interfaces.Operations.Entities.IAuditLog", "BeaconAr.Interfaces.Operations.Entities.IIdempotencyRequest",
            "BeaconAr.Interfaces.Operations.Entities.IIdempotencyState", "BeaconAr.Interfaces.Sales.Entities.IQuote",
            "BeaconAr.Interfaces.Sales.Entities.IQuoteLine", "BeaconAr.Interfaces.Sales.Entities.ISalesOrder",
            "BeaconAr.Interfaces.Sales.Entities.ISalesOrderLine",
        ];
        Assembly interfaces = typeof(BeaconAr.Interfaces.Access.Entities.IApplicationUser).Assembly;
        string[] actualInterfaces = interfaces.GetTypes().Where(type => type.IsInterface && type.Namespace?.StartsWith("BeaconAr.Interfaces.", StringComparison.Ordinal) == true && type.Namespace.EndsWith(".Entities", StringComparison.Ordinal))
            .Select(type => type.FullName!).Order(StringComparer.Ordinal).ToArray();
        CollectionAssert.AreEqual(expectedInterfaces.Order(StringComparer.Ordinal).ToArray(), actualInterfaces);
    }

    [TestMethod]
    public void GeneratedTypesAndContextsCarryOwnershipMetadata()
    {
        Type[] contexts = [typeof(AccessDbContext), typeof(MasterDataDbContext), typeof(OperationsDbContext), typeof(SalesDbContext)];
        Type[] generatedDomainTypes = typeof(Product).Assembly.GetTypes()
            .Where(type => type.IsPublic && type.GetCustomAttribute<GeneratedCodeAttribute>()?.Tool == "EFCorePowerTools")
            .ToArray();
        Assert.HasCount(43, generatedDomainTypes);

        foreach (Type type in generatedDomainTypes.Concat(contexts))
        {
            GeneratedCodeAttribute? attribute = type.GetCustomAttribute<GeneratedCodeAttribute>();
            Assert.IsNotNull(attribute, type.FullName);
            Assert.AreEqual("10.1.1386", attribute.Version, type.FullName);
        }
    }

    [TestMethod]
    public void ContextsOwnOnlyTheirCapabilityAndCrossContextNavigationsAreAbsent()
    {
        Assert.IsNotNull(typeof(AccessDbContext).GetProperty(nameof(AccessDbContext.ApplicationUsers)));
        Assert.IsNull(typeof(AccessDbContext).GetProperty("Customers"));
        Assert.IsNotNull(typeof(MasterDataDbContext).GetProperty(nameof(MasterDataDbContext.Customers)));
        Assert.IsNull(typeof(MasterDataDbContext).GetProperty("Quotes"));
        Assert.IsNotNull(typeof(OperationsDbContext).GetProperty(nameof(OperationsDbContext.AuditLogs)));
        Assert.IsNull(typeof(OperationsDbContext).GetProperty("ApplicationUsers"));
        Assert.IsNotNull(typeof(SalesDbContext).GetProperty(nameof(SalesDbContext.Quotes)));
        Assert.IsNull(typeof(SalesDbContext).GetProperty("Products"));

        Assert.IsNull(typeof(Quote).GetProperty("Customer"));
        Assert.IsNull(typeof(SalesOrder).GetProperty("Carrier"));
        Assert.IsNull(typeof(AuditLog).GetProperty("User"));
        Assert.IsNull(typeof(Product).GetProperty("QuoteLines"));
        Assert.IsNotNull(typeof(Quote).GetProperty(nameof(Quote.QuoteLines)));
        Assert.IsNotNull(typeof(IdempotencyRequest).GetProperty(nameof(IdempotencyRequest.State)));
        Assert.IsNotNull(typeof(CustomerAddress).GetProperty(nameof(CustomerAddress.Customer)));
    }

    [TestMethod]
    public void ContextNavigationMatrixIsExact()
    {
        Dictionary<Type, string[]> expected = new()
        {
            [typeof(ApplicationUser)] = ["CreatedByUser", "InverseCreatedByUser", "InverseModifiedByUser", "ModifiedByUser"],
            [typeof(AddressType)] = ["CustomerAddresses"], [typeof(Customer)] = ["CustomerAddresses"],
            [typeof(CustomerAddress)] = ["AddressType", "Customer"], [typeof(IdempotencyRequest)] = ["State"],
            [typeof(IdempotencyState)] = ["IdempotencyRequests"],
            [typeof(Quote)] = ["QuoteLines", "QuoteStatusHistories", "SalesOrder", "Status"],
            [typeof(QuoteLine)] = ["Quote"], [typeof(QuoteStatus)] = ["Quotes", "QuoteStatusHistories"],
            [typeof(QuoteStatusHistory)] = ["Quote", "Status"],
            [typeof(SalesOrder)] = ["SalesOrderLines", "SalesOrderStatusHistories", "SourceQuote", "Status"],
            [typeof(SalesOrderLine)] = ["SalesOrder"], [typeof(SalesOrderStatus)] = ["SalesOrders", "SalesOrderStatusHistories"],
            [typeof(SalesOrderStatusHistory)] = ["SalesOrder", "Status"],
        };
        DbContext[] contexts = [Create<AccessDbContext>(), Create<MasterDataDbContext>(), Create<OperationsDbContext>(), Create<SalesDbContext>()];
        try
        {
            Dictionary<Type, string[]> actual = contexts.SelectMany(context => context.Model.GetEntityTypes())
                .Where(entity => !entity.ClrType.Name.EndsWith("View", StringComparison.Ordinal))
                .ToDictionary(entity => entity.ClrType, entity => entity.GetNavigations().Select(navigation => navigation.Name).Order(StringComparer.Ordinal).ToArray());
            foreach ((Type type, string[] navigations) in expected)
                CollectionAssert.AreEqual(navigations.Order(StringComparer.Ordinal).ToArray(), actual[type], type.FullName);
            foreach ((Type type, string[] navigations) in actual.Where(pair => !expected.ContainsKey(pair.Key)))
                Assert.HasCount(0, navigations, type.FullName);
        }
        finally
        {
            foreach (DbContext context in contexts)
                context.Dispose();
        }
    }

    [TestMethod]
    public void MapperInventoryRegistrationDeterminismAndFailureRecoveryAreExact()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data");
        string[] expected = MapperManifest();
        CollectionAssert.AreEqual(expected, MapperPaths(dataRoot));
        foreach (string capability in new[] { "Access", "MasterData", "Operations", "Sales" })
        {
            string mapperRoot = Path.Combine(dataRoot, capability, "Mappers");
            string registrar = File.ReadAllText(Path.Combine(mapperRoot, $"{capability}StoredProcedureMappersRegisterer.cs"));
            foreach (string mapper in expected.Where(path => path.StartsWith($"{capability}/Mappers/", StringComparison.Ordinal) && !path.EndsWith("Registerer.cs", StringComparison.Ordinal)))
                StringAssert.Contains(registrar, $"new {(mapper.Contains("/DataReaders/", StringComparison.Ordinal) ? "DataReaders" : "SqlParameters")}.{Path.GetFileNameWithoutExtension(mapper)}()");
        }
        string module = File.ReadAllText(Path.Combine(dataRoot, "StoredProcedureMapperRegistration.cs"));
        foreach (string capability in new[] { "Access", "MasterData", "Operations", "Sales" })
            StringAssert.Contains(module, $"{capability}StoredProcedureMappersRegisterer.RegisterMappers()");
        Assert.IsFalse(Directory.Exists(Path.Combine(dataRoot, "Mappers")));

        string[] before = HashFiles(dataRoot, expected);
        RunProcess(root, "dotnet", "run", "--project", "src/BeaconAr.CodeGenerator/BeaconAr.CodeGenerator.csproj", "--configuration", "Release", "--no-build", "--", "mappers");
        string[] first = HashFiles(dataRoot, expected);
        RunProcess(root, "dotnet", "run", "--project", "src/BeaconAr.CodeGenerator/BeaconAr.CodeGenerator.csproj", "--configuration", "Release", "--no-build", "--", "mappers");
        CollectionAssert.AreEqual(first, HashFiles(dataRoot, expected));
        CollectionAssert.AreEqual(before, first);

        string target = Path.Combine(dataRoot, "Access", "Mappers");
        string[] targetBefore = Directory.GetFiles(target, "*", SearchOption.AllDirectories).Select(path => $"{path}|{Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(path)))}").Order(StringComparer.Ordinal).ToArray();
        using (var output = new BeaconAr.CodeGenerator.AtomicOutputDirectory(target))
            File.WriteAllText(Path.Combine(output.Path, "InjectedFailure.cs"), "failure");
        string[] targetAfter = Directory.GetFiles(target, "*", SearchOption.AllDirectories).Select(path => $"{path}|{Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(path)))}").Order(StringComparer.Ordinal).ToArray();
        CollectionAssert.AreEqual(targetBefore, targetAfter);
        Assert.HasCount(0, Directory.GetDirectories(Path.GetDirectoryName(target)!, ".Mappers.staging-*"));
    }

    [TestMethod]
    public void PersistenceRecoveryFixtureExercisesAllProtectedBoundaries()
    {
        string root = FindExampleRoot();
        RunProcess(root, "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "./build/regenerate-persistence.ps1", "-TestFailureRecovery", "-TestRedaction");
    }

    [TestMethod]
    public void GeneratedAndBehaviorPartialsAreCoLocatedWithoutUnexpectedGeneratedFiles()
    {
        string domainRoot = Path.Combine(FindExampleRoot(), "src", "BeaconAr.Domain");
        string[] capabilities = ["Access", "MasterData", "Operations", "Sales"];
        Assert.AreEqual(31, capabilities.Sum(capability => Directory.GetFiles(
            Path.Combine(domainRoot, capability, "Entities"), "*.cs").Count(path => !path.EndsWith(".Behavior.cs", StringComparison.Ordinal))));
        Assert.AreEqual(13, capabilities.Sum(capability => Directory.GetFiles(
            Path.Combine(domainRoot, capability, "Entities"), "*.Behavior.cs").Length));
    }

    [TestMethod]
    public void EveryViewIsKeylessInItsOwningContext()
    {
        DbContext[] contexts =
        [
            Create<AccessDbContext>(), Create<MasterDataDbContext>(), Create<OperationsDbContext>(), Create<SalesDbContext>(),
        ];
        try
        {
            foreach (DbContext context in contexts)
            {
                foreach (var entityType in context.Model.GetEntityTypes().Where(type => type.ClrType.Name.EndsWith("View", StringComparison.Ordinal)))
                    Assert.IsNull(entityType.FindPrimaryKey(), entityType.ClrType.FullName);
            }
        }
        finally
        {
            foreach (DbContext context in contexts)
                context.Dispose();
        }
    }

    #endregion

    #region Private Methods

    private static Dictionary<string, string[]> GeneratedFileManifest() => new(StringComparer.Ordinal)
    {
        ["Access"] = ["ApplicationUser", "ApplicationUserView"],
        ["MasterData"] = ["AddressType", "Carrier", "CarrierView", "Customer", "CustomerAddress", "CustomerAddressView", "CustomerView", "Product", "ProductView"],
        ["Operations"] = ["AuditLog", "AuditLogView", "IdempotencyRequest", "IdempotencyRequestView", "IdempotencyState", "IdempotencyStateView"],
        ["Sales"] = ["Quote", "QuoteLine", "QuoteLineView", "QuotePricingView", "QuoteStatus", "QuoteStatusHistory", "QuoteView", "SalesOrder", "SalesOrderLine", "SalesOrderLineView", "SalesOrderPricingView", "SalesOrderStatus", "SalesOrderStatusHistory", "SalesOrderView"],
    };

    private static string[] MapperManifest() =>
    [
        "Access/Mappers/AccessStoredProcedureMappersRegisterer.cs", "Access/Mappers/SqlParameters/GetOrCreateApplicationUserParametersMapper.cs",
        "MasterData/Mappers/DataReaders/CarrierViewDataReaderMapper.cs", "MasterData/Mappers/DataReaders/CustomerAddressViewDataReaderMapper.cs", "MasterData/Mappers/DataReaders/CustomerViewDataReaderMapper.cs", "MasterData/Mappers/DataReaders/ProductViewDataReaderMapper.cs",
        "MasterData/Mappers/MasterDataStoredProcedureMappersRegisterer.cs", "MasterData/Mappers/SqlParameters/AddressSearchParametersMapper.cs", "MasterData/Mappers/SqlParameters/CarrierSearchParametersMapper.cs", "MasterData/Mappers/SqlParameters/CustomerSearchParametersMapper.cs", "MasterData/Mappers/SqlParameters/HasAddressReferencesParametersMapper.cs", "MasterData/Mappers/SqlParameters/HasCarrierReferencesParametersMapper.cs", "MasterData/Mappers/SqlParameters/HasCustomerReferencesParametersMapper.cs", "MasterData/Mappers/SqlParameters/HasProductReferencesParametersMapper.cs", "MasterData/Mappers/SqlParameters/LockCustomerForAddressMutationParametersMapper.cs", "MasterData/Mappers/SqlParameters/ProductSearchParametersMapper.cs",
        "Operations/Mappers/DataReaders/DashboardRowDataReaderMapper.cs", "Operations/Mappers/OperationsStoredProcedureMappersRegisterer.cs", "Operations/Mappers/SqlParameters/DashboardParametersMapper.cs", "Operations/Mappers/SqlParameters/LockIdempotencyRequestParametersMapper.cs",
        "Sales/Mappers/DataReaders/AddressSalesReferenceRowDataReaderMapper.cs", "Sales/Mappers/DataReaders/CarrierSalesReferenceRowDataReaderMapper.cs", "Sales/Mappers/DataReaders/CustomerSalesReferenceRowDataReaderMapper.cs", "Sales/Mappers/DataReaders/ProductSalesReferenceRowDataReaderMapper.cs", "Sales/Mappers/DataReaders/QuoteViewDataReaderMapper.cs", "Sales/Mappers/DataReaders/SalesOrderViewDataReaderMapper.cs", "Sales/Mappers/SalesStoredProcedureMappersRegisterer.cs", "Sales/Mappers/SqlParameters/AllocateQuoteNumberParametersMapper.cs", "Sales/Mappers/SqlParameters/AllocateSalesOrderNumberParametersMapper.cs", "Sales/Mappers/SqlParameters/GetAddressSalesReferenceForUpdateParametersMapper.cs", "Sales/Mappers/SqlParameters/GetCarrierSalesReferenceForUpdateParametersMapper.cs", "Sales/Mappers/SqlParameters/GetCustomerSalesReferenceForUpdateParametersMapper.cs", "Sales/Mappers/SqlParameters/GetProductSalesReferenceForUpdateParametersMapper.cs", "Sales/Mappers/SqlParameters/LockQuoteForConversionParametersMapper.cs", "Sales/Mappers/SqlParameters/QuoteSearchParametersMapper.cs", "Sales/Mappers/SqlParameters/SalesOrderSearchParametersMapper.cs",
    ];

    private static string[] MapperPaths(string dataRoot) => Directory.GetFiles(dataRoot, "*.cs", SearchOption.AllDirectories)
        .Where(path => path.Contains($"{Path.DirectorySeparatorChar}Mappers{Path.DirectorySeparatorChar}", StringComparison.Ordinal))
        .Select(path => Path.GetRelativePath(dataRoot, path).Replace('\\', '/')).Order(StringComparer.Ordinal).ToArray();

    private static string[] HashFiles(string dataRoot, IEnumerable<string> paths) => paths
        .Select(path => $"{path}|{Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(Path.Combine(dataRoot, path))))}")
        .Order(StringComparer.Ordinal).ToArray();

    private static void RunProcess(string workingDirectory, string fileName, params string[] arguments)
    {
        using var process = Process.Start(new ProcessStartInfo(fileName, arguments)
        {
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        }) ?? throw new InvalidOperationException($"Could not start {fileName}.");
        string output = process.StandardOutput.ReadToEnd();
        string error = process.StandardError.ReadToEnd();
        Assert.IsTrue(process.WaitForExit(120_000), $"{fileName} timed out.");
        Assert.AreEqual(0, process.ExitCode, $"{fileName} failed:{Environment.NewLine}{output}{Environment.NewLine}{error}");
    }

    private static TContext Create<TContext>() where TContext : DbContext
    {
        var services = new Microsoft.Extensions.DependencyInjection.ServiceCollection().BuildServiceProvider();
        return (TContext)Activator.CreateInstance(typeof(TContext), services,
            new DbContextOptionsBuilder<TContext>().UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=BeaconArMetadata;Trusted_Connection=True").Options)!;
    }

    private static string FindExampleRoot()
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "BeaconAr.slnx")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new DirectoryNotFoundException("Beacon AR example root was not found.");
    }

    #endregion
}
