using System.Xml.Linq;
using BeaconAr.CodeGenerator;
using BeaconAr.Data.Receivables;
using BeaconAr.Domain.Receivables.Generated;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Domain.Repositories;
using Paradigm.Enterprise.Providers;

namespace BeaconAr.Architecture.Tests;

[TestClass]
public sealed class LayerBoundaryTests
{
    #region Nested Types

    private sealed class EmptyServiceProvider : IServiceProvider
    {
        public static EmptyServiceProvider Instance { get; } = new();

        public object? GetService(Type serviceType) => null;
    }

    #endregion

    #region Public Methods

    [TestMethod]
    public void ProjectReferencesFollowTheInwardDependencyGraph()
    {
        var root = FindExampleRoot();
        AssertReferences(root, "BeaconAr.Domain", "BeaconAr.Interfaces");
        AssertReferences(root, "BeaconAr.Data", "BeaconAr.Domain");
        AssertReferences(root, "BeaconAr.Providers", "BeaconAr.Data");
        AssertReferences(root, "BeaconAr.WebApi", "BeaconAr.Data", "BeaconAr.Domain", "BeaconAr.Providers", "BeaconAr.ServiceDefaults");
    }

    [TestMethod]
    public void DomainDoesNotReferenceHostOrConcreteDatabasePackages()
    {
        var root = FindExampleRoot();
        var projectText = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Domain", "BeaconAr.Domain.csproj"));
        Assert.IsFalse(projectText.Contains("Microsoft.AspNetCore", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("SqlServer", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("BeaconAr.WebApi", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("BeaconAr.AppHost", StringComparison.Ordinal));
    }

    [TestMethod]
    public void DatabaseFirstTemplatesUseCurrentParadigmGenericContracts()
    {
        var root = FindExampleRoot();
        var contextTemplate = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "DbContext.t4"));
        var entityTemplate = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "EntityType.t4"));
        var interfaceGenerator = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Interfaces", "EntityInterfaceGenerator.cs"));

        StringAssert.Contains(contextTemplate, "DbContextBase<int>");
        StringAssert.Contains(entityTemplate, "EntityBase<int>");
        StringAssert.Contains(entityTemplate, "IAuditableEntity<DateTimeOffset, int>");
        StringAssert.Contains(contextTemplate, "// <auto-generated/>");
        StringAssert.Contains(entityTemplate, "// <auto-generated/>");
        StringAssert.Contains(interfaceGenerator, "Paradigm.Enterprise.Interfaces.IEntity<int>");
    }

    [TestMethod]
    public void GeneratedPersistenceBoundaryRepresentsTheFoundationSchema()
    {
        var root = FindExampleRoot();
        var entityDirectory = Path.Combine(root, "src", "BeaconAr.Domain", "Receivables", "Generated");
        var entityFiles = Directory.GetFiles(entityDirectory, "*.cs", SearchOption.TopDirectoryOnly);
        var context = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "Receivables", "Generated", "ReceivablesDbContext.cs"));

        Assert.HasCount(19, entityFiles);
        Assert.AreEqual(19, CountOccurrences(context, "DbSet<"));
        Assert.AreEqual(6, CountOccurrences(context, ".IsRowVersion()"));
        Assert.AreEqual(2, CountOccurrences(context, ".HasNoKey()"));
        StringAssert.Contains(context, ".HasForeignKey(d => new { d.CustomerId, d.ShippingAddressId })");
        StringAssert.Contains(context, ".HasComputedColumnSql(");
        Assert.IsFalse(context.Contains("Server=", StringComparison.OrdinalIgnoreCase));
        Assert.IsTrue(entityFiles.All(path => File.ReadLines(path).First() == "// <auto-generated/>"));
    }

    [TestMethod]
    public void CustomerAddressOwnershipMetadataIsOneToMany()
    {
        var options = new DbContextOptionsBuilder<ReceivablesDbContext>()
            .UseSqlServer("Server=metadata-only;Initial Catalog=BeaconAr;Integrated Security=True;Encrypt=True")
            .Options;
        using var context = new ReceivablesDbContext(EmptyServiceProvider.Instance, options);

        var entityType = context.Model.FindEntityType(typeof(CustomerAddress));
        Assert.IsNotNull(entityType);
        var relationship = entityType.GetForeignKeys().Single(foreignKey => foreignKey.GetConstraintName() == "FK_CustomerAddress_Customer");
        Assert.IsFalse(relationship.IsUnique);
        Assert.IsNotNull(relationship.PrincipalToDependent);
        Assert.IsTrue(relationship.PrincipalToDependent.IsCollection);
        Assert.AreEqual("CustomerAddresses", relationship.PrincipalToDependent.Name);
        foreach (var indexName in new[] { "UQ_CustomerAddress_CustomerId_DefaultBilling", "UQ_CustomerAddress_CustomerId_DefaultShipping" })
        {
            var filteredIndex = entityType.GetIndexes().Single(index => index.GetDatabaseName() == indexName);
            Assert.IsTrue(filteredIndex.IsUnique);
            Assert.IsFalse(string.IsNullOrWhiteSpace(filteredIndex.GetFilter()));
        }

        var customer = new Customer();
        context.AddRange(
            new CustomerAddress { Customer = customer },
            new CustomerAddress { Customer = customer });
        var addresses = relationship.PrincipalToDependent.PropertyInfo?.GetValue(customer) as ICollection<CustomerAddress>;
        Assert.IsNotNull(addresses);
        Assert.HasCount(2, addresses);
    }

    [TestMethod]
    public void FoundationGeneratorRejectsUnknownTargetsAndHasNoDeferredProxyConfiguration()
    {
        var root = FindExampleRoot();
        var settings = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.CodeGenerator", "appsettings.json"));

        Assert.Throws<ArgumentException>(() => GenerationTargets.Parse(["proxy"]));
        Assert.IsFalse(settings.Contains("proxiesGenerator", StringComparison.Ordinal));
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.CodeGenerator", "Generators", "ProxiesGenerator.cs")));
    }

    [TestMethod]
    public void WebApiPreservesOpenTelemetryLoggingProvider()
    {
        var root = FindExampleRoot();
        var program = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.WebApi", "Program.cs"));

        Assert.IsFalse(program.Contains("ClearProviders", StringComparison.Ordinal));
    }

    [TestMethod]
    public void ApplicationRepositoriesAndProvidersFollowDiscoveryNames()
    {
        Type[] repositoryTypes = typeof(BeaconAr.Data.MasterData.ProductRepository).Assembly.GetTypes()
            .Where(type => type.IsPublic && !type.IsAbstract && typeof(IRepository).IsAssignableFrom(type))
            .ToArray();
        Type[] providerTypes = typeof(BeaconAr.Providers.MasterData.ProductProvider).Assembly.GetTypes()
            .Where(type => type.IsPublic && !type.IsAbstract && typeof(IProvider).IsAssignableFrom(type))
            .ToArray();

        Assert.HasCount(17, repositoryTypes);
        Assert.HasCount(10, providerTypes);
        foreach (Type implementation in repositoryTypes.Concat(providerTypes))
        {
            Type[] exactInterfaces = implementation.GetInterfaces()
                .Where(contract => contract.Name == $"I{implementation.Name}")
                .ToArray();
            Assert.HasCount(1, exactInterfaces, implementation.FullName);
        }
    }

    [TestMethod]
    public void MasterDataContractsDoNotLeakInfrastructureOrPersistenceEntities()
    {
        Type[] contracts = typeof(BeaconAr.Domain.MasterData.Contracts.ProductDto).Assembly.GetTypes()
            .Where(type => type.Namespace?.StartsWith("BeaconAr.Domain.MasterData", StringComparison.Ordinal) == true)
            .ToArray();
        foreach (Type contract in contracts)
        {
            IEnumerable<Type> exposedTypes = contract.GetMethods().SelectMany(method =>
                method.GetParameters().Select(parameter => parameter.ParameterType).Append(method.ReturnType));
            Assert.IsFalse(exposedTypes.Any(type => type == typeof(IQueryable) ||
                type.Namespace?.StartsWith("Microsoft.EntityFrameworkCore", StringComparison.Ordinal) == true ||
                type.Namespace?.StartsWith("Microsoft.Data.SqlClient", StringComparison.Ordinal) == true), contract.FullName);
        }

        Type persistenceNamespaceMarker = typeof(Product);
        foreach (Type provider in typeof(BeaconAr.Providers.MasterData.ProductProvider).Assembly.GetTypes()
                     .Where(type => type.IsPublic && typeof(IProvider).IsAssignableFrom(type)))
        {
            Assert.IsFalse(provider.GetMethods().Any(method => method.ReturnType == persistenceNamespaceMarker ||
                method.GetParameters().Any(parameter => parameter.ParameterType == persistenceNamespaceMarker)), provider.FullName);
        }
    }

    [TestMethod]
    public void SalesWorkflowBoundariesStayTransportNeutralAndAggregateOwned()
    {
        Type[] providers = typeof(BeaconAr.Providers.Sales.QuoteProvider).Assembly.GetTypes()
            .Where(type => type.Namespace?.StartsWith("BeaconAr.Providers.Sales", StringComparison.Ordinal) == true)
            .ToArray();
        Assert.IsFalse(providers.Any(type => type.GetMethods().Any(method =>
            method.ReturnType.Namespace?.StartsWith("Microsoft.AspNetCore", StringComparison.Ordinal) == true ||
            method.GetParameters().Any(parameter =>
                parameter.ParameterType.Namespace?.StartsWith("Microsoft.AspNetCore", StringComparison.Ordinal) == true))));

        Type[] repositories = typeof(BeaconAr.Data.Sales.QuoteRepository).Assembly.GetTypes()
            .Where(type => typeof(IRepository).IsAssignableFrom(type) && type.IsPublic)
            .ToArray();
        Assert.IsFalse(repositories.Any(type => type.Name.Contains("LineRepository", StringComparison.Ordinal) ||
            type.Name.Contains("StatusHistoryRepository", StringComparison.Ordinal)));

        Type[] providerContracts = typeof(BeaconAr.Providers.Sales.IQuoteProvider).Assembly.GetTypes()
            .Where(type => type.IsInterface && type.Namespace?.StartsWith("BeaconAr.Providers.Sales", StringComparison.Ordinal) == true)
            .ToArray();
        Assert.IsFalse(providerContracts.SelectMany(type => type.GetMethods()).Any(method =>
            method.ReturnType == typeof(Quote) || method.ReturnType == typeof(SalesOrder) ||
            method.GetParameters().Any(parameter => parameter.ParameterType == typeof(Quote) ||
                parameter.ParameterType == typeof(SalesOrder))));
    }

    [TestMethod]
    public void SalesDatabaseRoutinesDeclareBoundedConsistentContracts()
    {
        string root = FindExampleRoot();
        string quoteSearch = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Sales", "SearchQuote.sql"));
        string orderSearch = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Sales", "SearchSalesOrder.sql"));
        string dashboard = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Reporting", "GetDashboardSummary.sql"));

        foreach (string search in new[] { quoteSearch, orderSearch })
        {
            StringAssert.Contains(search, "SELECT COUNT(1)");
            StringAssert.Contains(search, "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
            StringAssert.Contains(search, "BEGIN TRANSACTION");
            StringAssert.Contains(search, "COMMIT TRANSACTION");
            StringAssert.Contains(search, "ROLLBACK TRANSACTION");
            StringAssert.Contains(search, "OFFSET ((CONVERT(BIGINT, @PageNumber) - 1) * @PageSize)");
            StringAssert.Contains(search, "[DeletionDate] IS NULL");
            StringAssert.Contains(search, "THROW 50002");
            Assert.IsFalse(search.Contains("EXEC(", StringComparison.OrdinalIgnoreCase));
            Assert.IsFalse(search.Contains("sp_executesql", StringComparison.OrdinalIgnoreCase));
        }

        StringAssert.Contains(dashboard, "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
        StringAssert.Contains(dashboard, "COUNT_BIG");
        StringAssert.Contains(dashboard, "SYSUTCDATETIME()");
        StringAssert.Contains(dashboard, "IF XACT_STATE() <> 0 ROLLBACK TRANSACTION");
    }

    #endregion

    #region Private Methods

    private static void AssertReferences(string root, string project, params string[] expected)
    {
        var document = XDocument.Load(Path.Combine(root, "src", project, $"{project}.csproj"));
        var references = document.Descendants("ProjectReference")
            .Select(static item => Path.GetFileNameWithoutExtension(item.Attribute("Include")?.Value))
            .Where(static item => item is not null)
            .ToArray();
        CollectionAssert.AreEquivalent(expected, references!);
    }

    private static int CountOccurrences(string text, string value) =>
        (text.Length - text.Replace(value, string.Empty, StringComparison.Ordinal).Length) / value.Length;

    private static string FindExampleRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "aspire.config.json")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new DirectoryNotFoundException("Beacon AR example root not found.");
    }

    #endregion
}
