using System.Xml.Linq;
using BeaconAr.CodeGenerator;
using BeaconAr.Data.Receivables.Context;
using BeaconAr.Domain.Receivables.Entities;
using BeaconAr.Interfaces.Receivables.Entities;
using Microsoft.EntityFrameworkCore;
using Paradigm.Enterprise.Data.Context;
using Paradigm.Enterprise.Data.Repositories;
using Paradigm.Enterprise.Domain.Repositories;
using Paradigm.Enterprise.Providers;
using System.Reflection;

namespace BeaconAr.Architecture.Tests;

[TestClass]
public sealed class LayerBoundaryTests
{
    #region Nested Types

    private sealed class EmptyServiceProvider : IServiceProvider
    {
        public static EmptyServiceProvider Instance { get; } = new();

        public object? GetService(Type serviceType) => null;
    }

    #endregion

    #region Public Methods

    [TestMethod]
    public void ProjectReferencesFollowTheInwardDependencyGraph()
    {
        var root = FindExampleRoot();
        AssertReferences(root, "BeaconAr.Domain", "BeaconAr.Interfaces");
        AssertReferences(root, "BeaconAr.Data", "BeaconAr.Domain");
        AssertReferences(root, "BeaconAr.Providers", "BeaconAr.Data");
        AssertReferences(root, "BeaconAr.WebApi", "BeaconAr.Data", "BeaconAr.Domain", "BeaconAr.Providers", "BeaconAr.ServiceDefaults");
    }

    [TestMethod]
    public void DomainDoesNotReferenceHostOrConcreteDatabasePackages()
    {
        var root = FindExampleRoot();
        var projectText = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Domain", "BeaconAr.Domain.csproj"));
        Assert.IsFalse(projectText.Contains("Microsoft.AspNetCore", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("SqlServer", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("BeaconAr.WebApi", StringComparison.Ordinal));
        Assert.IsFalse(projectText.Contains("BeaconAr.AppHost", StringComparison.Ordinal));
    }

    [TestMethod]
    public void DatabaseFirstTemplatesUseCurrentParadigmGenericContracts()
    {
        var root = FindExampleRoot();
        var contextTemplate = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "DbContext.t4"));
        var entityTemplate = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "CodeTemplates", "EFCore", "EntityType.t4"));
        var interfaceGenerator = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Interfaces", "EntityInterfaceGenerator.cs"));

        StringAssert.Contains(contextTemplate, "DbContextBase<int>");
        StringAssert.Contains(entityTemplate, "EntityBase<int, I");
        StringAssert.Contains(entityTemplate, "IAuditableEntity<DateTimeOffset, int>");
        StringAssert.Contains(contextTemplate, "This file has been auto generated by EF Core Power Tools");
        StringAssert.Contains(entityTemplate, "This file has been auto generated by EF Core Power Tools");
        StringAssert.Contains(interfaceGenerator, "Paradigm.Enterprise.Interfaces.IEntity<int>");
    }

    [TestMethod]
    public void GeneratedPersistenceBoundaryRepresentsTheFoundationSchema()
    {
        var root = FindExampleRoot();
        var entityDirectory = Path.Combine(root, "src", "BeaconAr.Domain", "Receivables", "Entities");
        var entityFiles = Directory.GetFiles(entityDirectory, "*.cs", SearchOption.TopDirectoryOnly);
        var context = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "Receivables", "Context", "ReceivablesDbContext.cs"));

        Assert.HasCount(28, entityFiles);
        Assert.AreEqual(28, CountOccurrences(context, "DbSet<"));
        Assert.AreEqual(12, CountOccurrences(context, ".IsRowVersion()"));
        Assert.AreEqual(11, CountOccurrences(context, ".HasNoKey()"));
        StringAssert.Contains(context, ".HasForeignKey(d => new { d.CustomerId, d.ShippingAddressId })");
        StringAssert.Contains(context, ".HasComputedColumnSql(");
        Assert.IsFalse(context.Contains("Server=", StringComparison.OrdinalIgnoreCase));
        Assert.IsTrue(entityFiles.All(path => File.ReadLines(path).First() ==
            "// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>"));
    }

    [TestMethod]
    public void EntityAndViewPairsShareGeneratedScalarContracts()
    {
        AssertSharedContract<IApplicationUser, ApplicationUser, ApplicationUserView>();
        AssertSharedContract<ICarrier, Carrier, CarrierView>();
        AssertSharedContract<ICustomer, Customer, CustomerView>();
        AssertSharedContract<ICustomerAddress, CustomerAddress, CustomerAddressView>();
        AssertSharedContract<IProduct, Product, ProductView>();
        AssertSharedContract<IQuote, Quote, QuoteView>();
        AssertSharedContract<IQuoteLine, QuoteLine, QuoteLineView>();
        AssertSharedContract<ISalesOrder, SalesOrder, SalesOrderView>();
        AssertSharedContract<ISalesOrderLine, SalesOrderLine, SalesOrderLineView>();
    }

    [TestMethod]
    public void GeneratedCollectionTrackersRespectAggregateOwnership()
    {
        Assert.IsNotNull(typeof(Quote).GetProperty("QuoteLinesDomainTracker"));
        Assert.IsNotNull(typeof(SalesOrder).GetProperty("SalesOrderLinesDomainTracker"));
        Assert.IsNull(typeof(Product).GetProperty("QuoteLinesDomainTracker"));
        Assert.IsNull(typeof(ApplicationUser).GetProperty("QuoteCreatedByUsersDomainTracker"));
    }

    [TestMethod]
    public void GeneratedViewsAreKeylessDatabaseProjectionsAndContextUsesParadigmBase()
    {
        var options = new DbContextOptionsBuilder<ReceivablesDbContext>()
            .UseSqlServer("Server=metadata-only;Initial Catalog=BeaconAr;Integrated Security=True;Encrypt=True")
            .Options;
        using var context = new ReceivablesDbContext(EmptyServiceProvider.Instance, options);

        Type[] publicViews =
        [
            typeof(ApplicationUserView), typeof(CarrierView), typeof(CustomerView), typeof(CustomerAddressView),
            typeof(ProductView), typeof(QuoteView), typeof(QuoteLineView), typeof(SalesOrderView), typeof(SalesOrderLineView),
        ];
        foreach (Type viewType in publicViews)
        {
            var metadata = context.Model.FindEntityType(viewType);
            Assert.IsNotNull(metadata, viewType.Name);
            Assert.IsNull(metadata.FindPrimaryKey(), viewType.Name);
            Assert.AreEqual(viewType.Name, metadata.GetViewName(), viewType.Name);
        }

        Assert.IsInstanceOfType<DbContextBase<int>>(context);
        Assert.IsNotNull(typeof(ReceivablesDbContext).GetConstructor(
            [typeof(IServiceProvider), typeof(DbContextOptions<ReceivablesDbContext>)]));
    }

    [TestMethod]
    public void CustomerAddressOwnershipMetadataIsOneToMany()
    {
        var options = new DbContextOptionsBuilder<ReceivablesDbContext>()
            .UseSqlServer("Server=metadata-only;Initial Catalog=BeaconAr;Integrated Security=True;Encrypt=True")
            .Options;
        using var context = new ReceivablesDbContext(EmptyServiceProvider.Instance, options);

        var entityType = context.Model.FindEntityType(typeof(CustomerAddress));
        Assert.IsNotNull(entityType);
        var relationship = entityType.GetForeignKeys().Single(foreignKey => foreignKey.GetConstraintName() == "FK_CustomerAddress_Customer");
        Assert.IsFalse(relationship.IsUnique);
        Assert.IsNotNull(relationship.PrincipalToDependent);
        Assert.IsTrue(relationship.PrincipalToDependent.IsCollection);
        Assert.AreEqual("CustomerAddresses", relationship.PrincipalToDependent.Name);
        foreach (var indexName in new[] { "UQ_CustomerAddress_CustomerId_DefaultBilling", "UQ_CustomerAddress_CustomerId_DefaultShipping" })
        {
            var filteredIndex = entityType.GetIndexes().Single(index => index.GetDatabaseName() == indexName);
            Assert.IsTrue(filteredIndex.IsUnique);
            Assert.IsFalse(string.IsNullOrWhiteSpace(filteredIndex.GetFilter()));
        }

        var customer = new Customer();
        context.AddRange(
            new CustomerAddress { Customer = customer },
            new CustomerAddress { Customer = customer });
        var addresses = relationship.PrincipalToDependent.PropertyInfo?.GetValue(customer) as ICollection<CustomerAddress>;
        Assert.IsNotNull(addresses);
        Assert.HasCount(2, addresses);
    }

    [TestMethod]
    public void FoundationGeneratorRejectsUnknownTargetsAndHasNoDeferredProxyConfiguration()
    {
        var root = FindExampleRoot();
        var settings = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.CodeGenerator", "appsettings.json"));

        Assert.Throws<ArgumentException>(() => GenerationTargets.Parse(["proxy"]));
        Assert.IsFalse(settings.Contains("proxiesGenerator", StringComparison.Ordinal));
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.CodeGenerator", "Generators", "ProxiesGenerator.cs")));
    }

    [TestMethod]
    public void WebApiPreservesOpenTelemetryLoggingProvider()
    {
        var root = FindExampleRoot();
        var program = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.WebApi", "Program.cs"));

        Assert.IsFalse(program.Contains("ClearProviders", StringComparison.Ordinal));
    }

    [TestMethod]
    public void ApplicationRepositoriesAndProvidersFollowDiscoveryNames()
    {
        Type[] repositoryTypes = typeof(BeaconAr.Data.MasterData.ProductRepository).Assembly.GetTypes()
            .Where(type => type.IsPublic && !type.IsAbstract && typeof(IRepository).IsAssignableFrom(type))
            .ToArray();
        Type[] providerTypes = typeof(BeaconAr.Providers.MasterData.ProductProvider).Assembly.GetTypes()
            .Where(type => type.IsPublic && !type.IsAbstract && typeof(IProvider).IsAssignableFrom(type))
            .ToArray();

        Assert.HasCount(17, repositoryTypes);
        Assert.HasCount(10, providerTypes);
        foreach (Type implementation in repositoryTypes.Concat(providerTypes))
        {
            Type[] exactInterfaces = implementation.GetInterfaces()
                .Where(contract => contract.Name == $"I{implementation.Name}")
                .ToArray();
            Assert.HasCount(1, exactInterfaces, implementation.FullName);
        }
    }

    [TestMethod]
    public void MasterDataCrudUsesOfficialTypedBasesAndGeneratedViews()
    {
        Assert.IsTrue(typeof(IEditRepository<Product, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.IProductRepository)));
        Assert.IsTrue(typeof(IEditRepository<Customer, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.ICustomerRepository)));
        Assert.IsTrue(typeof(IEditRepository<CustomerAddress, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.IAddressRepository)));
        Assert.IsTrue(typeof(IEditRepository<Carrier, int>).IsAssignableFrom(typeof(BeaconAr.Domain.MasterData.Repositories.ICarrierRepository)));

        Assert.AreEqual(typeof(EditRepositoryBase<Product, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.ProductRepository).BaseType);
        Assert.AreEqual(typeof(EditRepositoryBase<Customer, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.CustomerRepository).BaseType);
        Assert.AreEqual(typeof(EditRepositoryBase<CustomerAddress, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.AddressRepository).BaseType);
        Assert.AreEqual(typeof(EditRepositoryBase<Carrier, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.CarrierRepository).BaseType);

        Assert.AreEqual(typeof(ReadRepositoryBase<ProductView, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.ProductViewRepository).BaseType);
        Assert.AreEqual(typeof(ReadRepositoryBase<CustomerView, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.CustomerViewRepository).BaseType);
        Assert.AreEqual(typeof(ReadRepositoryBase<CustomerAddressView, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.AddressViewRepository).BaseType);
        Assert.AreEqual(typeof(ReadRepositoryBase<CarrierView, ReceivablesDbContext, int>), typeof(BeaconAr.Data.MasterData.CarrierViewRepository).BaseType);

        Assert.IsTrue(typeof(IEditProvider<ProductView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.IProductProvider)));
        Assert.IsTrue(typeof(IEditProvider<CustomerView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.ICustomerProvider)));
        Assert.IsTrue(typeof(IEditProvider<CustomerAddressView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.IAddressProvider)));
        Assert.IsTrue(typeof(IEditProvider<CarrierView, int>).IsAssignableFrom(typeof(BeaconAr.Providers.MasterData.ICarrierProvider)));

        Assert.AreEqual(
            typeof(EditProviderBase<IProduct, Product, ProductView, BeaconAr.Domain.MasterData.Repositories.IProductRepository,
                BeaconAr.Domain.MasterData.Repositories.IProductViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.ProductProvider).BaseType);
        Assert.AreEqual(
            typeof(EditProviderBase<ICustomer, Customer, CustomerView, BeaconAr.Domain.MasterData.Repositories.ICustomerRepository,
                BeaconAr.Domain.MasterData.Repositories.ICustomerViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.CustomerProvider).BaseType);
        Assert.AreEqual(
            typeof(EditProviderBase<ICustomerAddress, CustomerAddress, CustomerAddressView,
                BeaconAr.Domain.MasterData.Repositories.IAddressRepository,
                BeaconAr.Domain.MasterData.Repositories.IAddressViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.AddressProvider).BaseType);
        Assert.AreEqual(
            typeof(EditProviderBase<ICarrier, Carrier, CarrierView, BeaconAr.Domain.MasterData.Repositories.ICarrierRepository,
                BeaconAr.Domain.MasterData.Repositories.ICarrierViewRepository, int>),
            typeof(BeaconAr.Providers.MasterData.CarrierProvider).BaseType);
    }

    [TestMethod]
    public void MasterDataRepositoriesAndProvidersUseGeneratedViewsWithoutCompatibilityDtos()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data", "MasterData");
        string providerRoot = Path.Combine(root, "src", "BeaconAr.Providers", "MasterData");
        var boundaries = new[]
        {
            ("Product", "ProductViews"),
            ("Customer", "CustomerViews"),
            ("Address", "CustomerAddressViews"),
            ("Carrier", "CarrierViews"),
        };

        foreach ((string name, string dbSet) in boundaries)
        {
            string repository = File.ReadAllText(Path.Combine(dataRoot, $"{name}ViewRepository.cs"));
            StringAssert.Contains(repository, $"EntityContext.{dbSet}.AsNoTracking()");
            Assert.IsFalse(repository.Contains($"{name}Dto", StringComparison.Ordinal));

            string provider = File.ReadAllText(Path.Combine(providerRoot, $"{name}Provider.cs"));
            Assert.IsFalse(provider.Contains("ToDto(", StringComparison.Ordinal));
            Assert.IsFalse(provider.Contains($"{name}Dto", StringComparison.Ordinal));
        }

        foreach (string repositoryPath in Directory.GetFiles(dataRoot, "*Repository.cs", SearchOption.TopDirectoryOnly))
        {
            string repository = File.ReadAllText(repositoryPath);
            Assert.IsFalse(repository.Contains("CommitChangesAsync", StringComparison.Ordinal), repositoryPath);
        }
    }

    [TestMethod]
    public void ProvidersDoNotReintroduceLocalProviderBaseClasses()
    {
        string root = FindExampleRoot();
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.Providers", "MasterData", "MasterDataProviderBase.cs")));
        Assert.IsFalse(File.Exists(Path.Combine(root, "src", "BeaconAr.Providers", "Sales", "SalesProviderBase.cs")));
        Assert.AreEqual(typeof(object), typeof(BeaconAr.Providers.Sales.QuoteProvider).BaseType);
        Assert.AreEqual(typeof(object), typeof(BeaconAr.Providers.Sales.SalesOrderProvider).BaseType);
        Assert.AreEqual(typeof(object), typeof(BeaconAr.Providers.Sales.QuoteConversionProvider).BaseType);
    }

    [TestMethod]
    public void ProvidersDoNotClassifyConcreteDatabaseDriverExceptions()
    {
        string root = FindExampleRoot();
        string providerRoot = Path.Combine(root, "src", "BeaconAr.Providers");
        foreach (string path in Directory.GetFiles(providerRoot, "*.cs", SearchOption.AllDirectories))
        {
            string source = File.ReadAllText(path);
            Assert.IsFalse(source.Contains("Microsoft.Data.SqlClient", StringComparison.Ordinal), path);
            Assert.IsFalse(source.Contains("Microsoft.EntityFrameworkCore", StringComparison.Ordinal), path);
        }

        string classifier = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Data", "Operations",
            "IdempotencyPersistenceErrorClassifier.cs"));
        StringAssert.Contains(classifier, "UQ_IdempotencyRequest_UserId_Operation_KeyHash");
    }

    [TestMethod]
    public void OfficialMasterDataMutationsRemainExplicitlyGuardedUntilTheTransportConcurrencyContractExists()
    {
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.ProductProvider, ProductView>();
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.CustomerProvider, CustomerView>();
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.AddressProvider, CustomerAddressView>();
        AssertOfficialMutationsAreDeclared<BeaconAr.Providers.MasterData.CarrierProvider, CarrierView>();
    }

    [TestMethod]
    public void MasterDataSearchesMaterializeGeneratedViewsInOneProcedureRoundTrip()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data", "MasterData");
        string databaseRoot = Path.Combine(root, "src", "database", "routines", "MasterData");
        var boundaries = new[]
        {
            ("Product", "ProductView", "CreatedByUserDisplayName"),
            ("Customer", "CustomerView", "CreatedByUserDisplayName"),
            ("Address", "CustomerAddressView", "CustomerAccountNumber"),
            ("Carrier", "CarrierView", "CreatedByUserDisplayName"),
        };

        foreach ((string name, string view, string expandedField) in boundaries)
        {
            string repository = File.ReadAllText(Path.Combine(dataRoot, $"{name}ViewRepository.cs"));
            StringAssert.Contains(repository, "GetSearchPaginatedFunction");
            Assert.IsFalse(repository.Contains("Dictionary<", StringComparison.Ordinal));
            Assert.IsFalse(repository.Contains("ids.Contains", StringComparison.Ordinal));

            string procedure = File.ReadAllText(Path.Combine(databaseRoot, $"Search{name}.sql"));
            StringAssert.Contains(procedure, $"[dbo].[{view}]");
            StringAssert.Contains(procedure, expandedField);
        }
    }

    [TestMethod]
    public void MasterDataProcedureViewMappersHaveOneGeneratedOwner()
    {
        string root = FindExampleRoot();
        string dataRoot = Path.Combine(root, "src", "BeaconAr.Data");
        string generatedMapperRoot = Path.Combine(dataRoot, "Mappers", "DataReaders");
        string registerer = File.ReadAllText(Path.Combine(dataRoot, "Mappers", "StoreProcedureMappersRegisterer.cs"));
        var boundaries = new[]
        {
            (Procedure: "Product", View: "ProductView", ObsoleteRow: "ProductSearchRow"),
            (Procedure: "Customer", View: "CustomerView", ObsoleteRow: "CustomerSearchRow"),
            (Procedure: "Address", View: "CustomerAddressView", ObsoleteRow: "AddressSearchRow"),
            (Procedure: "Carrier", View: "CarrierView", ObsoleteRow: "CarrierSearchRow"),
        };

        foreach ((string procedure, string view, string obsoleteRow) in boundaries)
        {
            string wrapper = File.ReadAllText(Path.Combine(
                dataRoot, "MasterData", "StoredProcedures", $"Search{procedure}Procedure.cs"));
            StringAssert.Contains(wrapper, $"List<{view}>");
            Assert.IsFalse(File.Exists(Path.Combine(
                dataRoot, "MasterData", "StoredProcedures", $"{obsoleteRow}.cs")));

            string generatedMapper = File.ReadAllText(Path.Combine(generatedMapperRoot, $"{view}DataReaderMapper.cs"));
            StringAssert.StartsWith(generatedMapper, "// <auto-generated/>");
            StringAssert.Contains(generatedMapper, $"internal partial class {view}DataReaderMapper");
            StringAssert.Contains(registerer,
                $"DataReaderMapperFactory.RegisterMapper<Domain.Receivables.Entities.{view}>(() => new DataReaders.{view}DataReaderMapper());");
            Assert.IsFalse(registerer.Contains(obsoleteRow, StringComparison.Ordinal));
        }

        string parallelMapperRoot = Path.Combine(dataRoot, "MasterData", "Mappers");
        Assert.IsFalse(Directory.Exists(parallelMapperRoot) &&
            Directory.EnumerateFiles(parallelMapperRoot, "*.cs", SearchOption.AllDirectories).Any());

        string generatorRoot = Path.Combine(root, "src", "BeaconAr.CodeGenerator");
        string generator = File.ReadAllText(Path.Combine(generatorRoot, "Generators", "StoredProcedureMapperGenerator.cs"));
        string configuration = File.ReadAllText(Path.Combine(generatorRoot, "appsettings.json"));
        StringAssert.Contains(generator, "using var output = new AtomicOutputDirectory(outputPath)");
        StringAssert.Contains(generator, "OrderBy(static type => type.FullName ?? type.Name, StringComparer.Ordinal)");
        StringAssert.Contains(configuration, "../BeaconAr.Data/Mappers");
        Assert.AreEqual(1, CountOccurrences(configuration, "dataReaderMapperGenerator"));
    }

    [TestMethod]
    public void WorkflowCoordinatorIsScopedAndConstructorInjected()
    {
        string root = FindExampleRoot();
        string program = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.WebApi", "Program.cs"));
        StringAssert.Contains(program, "AddScoped<SalesWorkflowCoordinator>()");

        Type coordinator = typeof(BeaconAr.Providers.Sales.SalesWorkflowCoordinator);
        Assert.IsTrue(coordinator.IsPublic);
        Assert.AreEqual(1, coordinator.GetConstructors(BindingFlags.Public | BindingFlags.Instance).Length);
        Assert.AreEqual(0, coordinator.GetProperties(BindingFlags.Public | BindingFlags.Instance |
            BindingFlags.Static | BindingFlags.DeclaredOnly).Length);
        Assert.AreEqual(0, coordinator.GetMethods(BindingFlags.Public | BindingFlags.Instance |
            BindingFlags.Static | BindingFlags.DeclaredOnly).Length);

        foreach (string propertyName in new[]
                 {
                     "ErrorClassifier", "PersistenceSession", "UnitOfWork", "UserId", "UtcNow",
                 })
        {
            PropertyInfo? property = coordinator.GetProperty(propertyName,
                BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            Assert.IsNotNull(property, propertyName);
            Assert.IsTrue(property.GetMethod?.IsAssembly, propertyName);
        }

        foreach (string methodName in new[]
                 {
                     "ExecuteAsync", "EnsureVersion", "AddAudit", "NotFound", "InvalidReference",
                 })
        {
            MethodInfo? method = coordinator.GetMethods(BindingFlags.NonPublic | BindingFlags.Instance |
                    BindingFlags.Static | BindingFlags.DeclaredOnly)
                .SingleOrDefault(candidate => candidate.Name == methodName);
            Assert.IsNotNull(method, methodName);
            Assert.IsTrue(method.IsAssembly, methodName);
        }

        foreach (Type provider in new[]
                 {
                     typeof(BeaconAr.Providers.Sales.QuoteProvider),
                     typeof(BeaconAr.Providers.Sales.SalesOrderProvider),
                     typeof(BeaconAr.Providers.Sales.QuoteConversionProvider),
                 })
        {
            Assert.IsTrue(provider.GetConstructors().Single().GetParameters().Any(parameter => parameter.ParameterType == coordinator));
            string source = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.Providers", "Sales", $"{provider.Name}.cs"));
            Assert.IsFalse(source.Contains("new SalesWorkflowCoordinator", StringComparison.Ordinal));
        }
    }

    [TestMethod]
    public void DatabaseProjectFoldersAndVisualStudioIdentityStayAligned()
    {
        const string projectGuid = "A09E027B-4428-49A6-9A92-C43CF35D9206";
        string root = FindExampleRoot();
        string project = File.ReadAllText(Path.Combine(root, "src", "database", "BeaconAr.Database.sqlproj"));
        XDocument document = XDocument.Parse(project);
        Assert.AreEqual($"{{{projectGuid}}}", document.Descendants("ProjectGuid").Single().Value.ToUpperInvariant());
        Assert.AreEqual("True", document.Descendants("TargetDatabaseSet").Single().Value);
        StringAssert.Contains(project, "<Folder Include=\"tables\\MasterData\\\" />");
        StringAssert.Contains(project, "<Folder Include=\"views\\MasterData\\\" />");
        StringAssert.Contains(project, "<Folder Include=\"routines\\MasterData\\\" />");

        string solution = File.ReadAllText(Path.Combine(root, "src", "BeaconAr.sln")).ToUpperInvariant();
        Assert.AreEqual(14, solution.Split(projectGuid, StringSplitOptions.None).Length - 1);
        Assert.IsFalse(solution.Contains("36012A89-DEB7-49AF-AA8F-2C0B1C3289BF", StringComparison.Ordinal));
    }

    [TestMethod]
    public void MasterDataContractsDoNotLeakInfrastructureOrPersistenceEntities()
    {
        Type[] contracts = typeof(BeaconAr.Domain.MasterData.Contracts.ProductCreateRequest).Assembly.GetTypes()
            .Where(type => type.Namespace?.StartsWith("BeaconAr.Domain.MasterData", StringComparison.Ordinal) == true)
            .ToArray();
        foreach (Type contract in contracts)
        {
            IEnumerable<Type> exposedTypes = contract.GetMethods().SelectMany(method =>
                method.GetParameters().Select(parameter => parameter.ParameterType).Append(method.ReturnType));
            Assert.IsFalse(exposedTypes.Any(type => type == typeof(IQueryable) ||
                type.Namespace?.StartsWith("Microsoft.EntityFrameworkCore", StringComparison.Ordinal) == true ||
                type.Namespace?.StartsWith("Microsoft.Data.SqlClient", StringComparison.Ordinal) == true), contract.FullName);
        }

        Type persistenceNamespaceMarker = typeof(Product);
        foreach (Type provider in typeof(BeaconAr.Providers.MasterData.ProductProvider).Assembly.GetTypes()
                     .Where(type => type.IsPublic && typeof(IProvider).IsAssignableFrom(type)))
        {
            Assert.IsFalse(provider.GetMethods().Any(method => method.ReturnType == persistenceNamespaceMarker ||
                method.GetParameters().Any(parameter => parameter.ParameterType == persistenceNamespaceMarker)), provider.FullName);
        }
    }

    [TestMethod]
    public void SalesWorkflowBoundariesStayTransportNeutralAndAggregateOwned()
    {
        Type[] providers = typeof(BeaconAr.Providers.Sales.QuoteProvider).Assembly.GetTypes()
            .Where(type => type.Namespace?.StartsWith("BeaconAr.Providers.Sales", StringComparison.Ordinal) == true)
            .ToArray();
        Assert.IsFalse(providers.Any(type => type.GetMethods().Any(method =>
            method.ReturnType.Namespace?.StartsWith("Microsoft.AspNetCore", StringComparison.Ordinal) == true ||
            method.GetParameters().Any(parameter =>
                parameter.ParameterType.Namespace?.StartsWith("Microsoft.AspNetCore", StringComparison.Ordinal) == true))));

        Type[] repositories = typeof(BeaconAr.Data.Sales.QuoteRepository).Assembly.GetTypes()
            .Where(type => typeof(IRepository).IsAssignableFrom(type) && type.IsPublic)
            .ToArray();
        Assert.IsFalse(repositories.Any(type => type.Name.Contains("LineRepository", StringComparison.Ordinal) ||
            type.Name.Contains("StatusHistoryRepository", StringComparison.Ordinal)));

        Type[] providerContracts = typeof(BeaconAr.Providers.Sales.IQuoteProvider).Assembly.GetTypes()
            .Where(type => type.IsInterface && type.Namespace?.StartsWith("BeaconAr.Providers.Sales", StringComparison.Ordinal) == true)
            .ToArray();
        Assert.IsFalse(providerContracts.SelectMany(type => type.GetMethods()).Any(method =>
            method.ReturnType == typeof(Quote) || method.ReturnType == typeof(SalesOrder) ||
            method.GetParameters().Any(parameter => parameter.ParameterType == typeof(Quote) ||
                parameter.ParameterType == typeof(SalesOrder))));
    }

    [TestMethod]
    public void SalesDatabaseRoutinesDeclareBoundedConsistentContracts()
    {
        string root = FindExampleRoot();
        string quoteSearch = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Sales", "SearchQuote.sql"));
        string orderSearch = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Sales", "SearchSalesOrder.sql"));
        string dashboard = File.ReadAllText(Path.Combine(root, "src", "database", "routines", "Reporting", "GetDashboardSummary.sql"));

        foreach (string search in new[] { quoteSearch, orderSearch })
        {
            StringAssert.Contains(search, "SELECT COUNT(1)");
            StringAssert.Contains(search, "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
            StringAssert.Contains(search, "BEGIN TRANSACTION");
            StringAssert.Contains(search, "COMMIT TRANSACTION");
            StringAssert.Contains(search, "ROLLBACK TRANSACTION");
            StringAssert.Contains(search, "OFFSET ((CONVERT(BIGINT, @PageNumber) - 1) * @PageSize)");
            StringAssert.Contains(search, "[DeletionDate] IS NULL");
            StringAssert.Contains(search, "THROW 50002");
            Assert.IsFalse(search.Contains("EXEC(", StringComparison.OrdinalIgnoreCase));
            Assert.IsFalse(search.Contains("sp_executesql", StringComparison.OrdinalIgnoreCase));
        }

        StringAssert.Contains(dashboard, "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
        StringAssert.Contains(dashboard, "COUNT_BIG");
        StringAssert.Contains(dashboard, "SYSUTCDATETIME()");
        StringAssert.Contains(dashboard, "IF XACT_STATE() <> 0 ROLLBACK TRANSACTION");
    }

    #endregion

    #region Private Methods

    private static void AssertReferences(string root, string project, params string[] expected)
    {
        var document = XDocument.Load(Path.Combine(root, "src", project, $"{project}.csproj"));
        var references = document.Descendants("ProjectReference")
            .Select(static item => Path.GetFileNameWithoutExtension(item.Attribute("Include")?.Value))
            .Where(static item => item is not null)
            .ToArray();
        CollectionAssert.AreEquivalent(expected, references!);
    }

    private static void AssertSharedContract<TContract, TEntity, TView>()
        where TEntity : TContract
        where TView : TContract
    {
        var nullability = new NullabilityInfoContext();
        PropertyInfo[] entityProperties = typeof(TEntity)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Where(static property => IsScalar(property.PropertyType))
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .ToArray();
        PropertyInfo[] contractProperties = typeof(TContract)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .ToArray();

        CollectionAssert.AreEqual(
            entityProperties.Select(static property => property.Name).ToArray(),
            contractProperties.Select(static property => property.Name).ToArray(),
            $"{typeof(TContract).Name} must declare the exact scalar surface of {typeof(TEntity).Name}.");

        foreach (PropertyInfo contractProperty in contractProperties)
        {
            var entityProperty = typeof(TEntity).GetProperty(contractProperty.Name);
            var viewProperty = typeof(TView).GetProperty(contractProperty.Name);
            Assert.IsNotNull(entityProperty, $"{typeof(TEntity).Name}.{contractProperty.Name}");
            Assert.IsNotNull(viewProperty, $"{typeof(TView).Name}.{contractProperty.Name}");
            Assert.IsNotNull(contractProperty.GetMethod, $"{typeof(TContract).Name}.{contractProperty.Name} getter");
            Assert.IsNull(contractProperty.SetMethod, $"{typeof(TContract).Name}.{contractProperty.Name} must be getter-only.");
            Assert.AreEqual(contractProperty.PropertyType, entityProperty.PropertyType, contractProperty.Name);
            Assert.AreEqual(contractProperty.PropertyType, viewProperty.PropertyType, contractProperty.Name);
            NullabilityState contractNullability = nullability.Create(contractProperty).ReadState;
            Assert.AreEqual(contractNullability, nullability.Create(entityProperty).ReadState,
                $"Entity nullability differs for {typeof(TContract).Name}.{contractProperty.Name}.");
            Assert.AreEqual(contractNullability, nullability.Create(viewProperty).ReadState,
                $"View nullability differs for {typeof(TContract).Name}.{contractProperty.Name}.");
        }
    }

    private static void AssertOfficialMutationsAreDeclared<TProvider, TView>()
    {
        Type provider = typeof(TProvider);
        Type view = typeof(TView);
        Type list = typeof(List<>).MakeGenericType(view);
        Type enumerableView = typeof(IEnumerable<>).MakeGenericType(view);
        Type enumerableId = typeof(IEnumerable<int>);
        var operations = new[]
        {
            ("AddAsync", new[] { view }),
            ("AddAsync", new[] { list }),
            ("UpdateAsync", new[] { view }),
            ("UpdateAsync", new[] { list }),
            ("SaveAsync", new[] { view }),
            ("SaveAsync", new[] { enumerableView }),
            ("DeleteAsync", new[] { typeof(int) }),
            ("DeleteAsync", new[] { enumerableId }),
        };

        foreach ((string name, Type[] parameters) in operations)
        {
            MethodInfo? method = provider.GetMethod(name, parameters);
            Assert.IsNotNull(method, $"{provider.Name}.{name}");
            Assert.AreEqual(provider, method.DeclaringType, $"{provider.Name}.{name} must explicitly guard the official overload.");
        }
    }

    private static bool IsScalar(Type type)
    {
        Type scalarType = Nullable.GetUnderlyingType(type) ?? type;
        return scalarType.IsEnum ||
               scalarType.IsPrimitive ||
               scalarType == typeof(string) ||
               scalarType == typeof(decimal) ||
               scalarType == typeof(DateOnly) ||
               scalarType == typeof(DateTime) ||
               scalarType == typeof(DateTimeOffset) ||
               scalarType == typeof(Guid) ||
               scalarType == typeof(TimeOnly) ||
               scalarType == typeof(TimeSpan) ||
               scalarType == typeof(byte[]);
    }

    private static int CountOccurrences(string text, string value) =>
        (text.Length - text.Replace(value, string.Empty, StringComparison.Ordinal).Length) / value.Length;

    private static string FindExampleRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "aspire.config.json")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new DirectoryNotFoundException("Beacon AR example root not found.");
    }

    #endregion
}
