// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.MasterData.StoredProcedures;

namespace BeaconAr.Data.Mappers.SqlParameters;

internal partial class AddressSearchParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is AddressSearchParameters instance)) return;

        AddSqlParameter(nameof(AddressSearchParameters.Search), instance.Search);
        AddSqlParameter(nameof(AddressSearchParameters.CustomerId), instance.CustomerId);
        AddSqlParameter(nameof(AddressSearchParameters.Type), instance.Type);
        AddSqlParameter(nameof(AddressSearchParameters.Usage), instance.Usage);
        AddSqlParameter(nameof(AddressSearchParameters.PageNumber), instance.PageNumber);
        AddSqlParameter(nameof(AddressSearchParameters.PageSize), instance.PageSize);
        AddSqlParameter(nameof(AddressSearchParameters.SortField), instance.SortField);
        AddSqlParameter(nameof(AddressSearchParameters.SortDirection), instance.SortDirection);

    }
}