// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.MasterData.StoredProcedures;

namespace BeaconAr.Data.Mappers.SqlParameters;

internal partial class CarrierSearchParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is CarrierSearchParameters instance)) return;

        AddSqlParameter(nameof(CarrierSearchParameters.Search), instance.Search);
        AddSqlParameter(nameof(CarrierSearchParameters.Active), instance.Active);
        AddSqlParameter(nameof(CarrierSearchParameters.PageNumber), instance.PageNumber);
        AddSqlParameter(nameof(CarrierSearchParameters.PageSize), instance.PageSize);
        AddSqlParameter(nameof(CarrierSearchParameters.SortField), instance.SortField);
        AddSqlParameter(nameof(CarrierSearchParameters.SortDirection), instance.SortDirection);

    }
}