// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.MasterData.StoredProcedures;

namespace BeaconAr.Data.Mappers.SqlParameters;

internal partial class CustomerSearchParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is CustomerSearchParameters instance)) return;

        AddSqlParameter(nameof(CustomerSearchParameters.Search), instance.Search);
        AddSqlParameter(nameof(CustomerSearchParameters.Active), instance.Active);
        AddSqlParameter(nameof(CustomerSearchParameters.PageNumber), instance.PageNumber);
        AddSqlParameter(nameof(CustomerSearchParameters.PageSize), instance.PageSize);
        AddSqlParameter(nameof(CustomerSearchParameters.SortField), instance.SortField);
        AddSqlParameter(nameof(CustomerSearchParameters.SortDirection), instance.SortDirection);

    }
}