// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Reporting.StoredProcedures;

namespace BeaconAr.Data.Mappers.SqlParameters;

internal partial class DashboardParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is DashboardParameters instance)) return;


    }
}