// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.MasterData.StoredProcedures;

namespace BeaconAr.Data.Mappers.SqlParameters;

internal partial class ProductSearchParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is ProductSearchParameters instance)) return;

        AddSqlParameter(nameof(ProductSearchParameters.Search), instance.Search);
        AddSqlParameter(nameof(ProductSearchParameters.Active), instance.Active);
        AddSqlParameter(nameof(ProductSearchParameters.PageNumber), instance.PageNumber);
        AddSqlParameter(nameof(ProductSearchParameters.PageSize), instance.PageSize);
        AddSqlParameter(nameof(ProductSearchParameters.SortField), instance.SortField);
        AddSqlParameter(nameof(ProductSearchParameters.SortDirection), instance.SortDirection);

    }
}