// <auto-generated/>
using Paradigm.Enterprise.Data.SqlServer.StoredProcedures.Mappers;
using BeaconAr.Data.Sales.StoredProcedures;

namespace BeaconAr.Data.Mappers.SqlParameters;

internal partial class SalesOrderSearchParametersMapper : SqlParameterMapperBase
{
    protected override void AddSqlParameters(object parameters)
    {
        if (!(parameters is SalesOrderSearchParameters instance)) return;

        AddSqlParameter(nameof(SalesOrderSearchParameters.Search), instance.Search);
        AddSqlParameter(nameof(SalesOrderSearchParameters.StatusId), instance.StatusId);
        AddSqlParameter(nameof(SalesOrderSearchParameters.CustomerId), instance.CustomerId);
        AddSqlParameter(nameof(SalesOrderSearchParameters.SourceQuoteId), instance.SourceQuoteId);
        AddSqlParameter(nameof(SalesOrderSearchParameters.PageNumber), instance.PageNumber);
        AddSqlParameter(nameof(SalesOrderSearchParameters.PageSize), instance.PageSize);
        AddSqlParameter(nameof(SalesOrderSearchParameters.SortField), instance.SortField);
        AddSqlParameter(nameof(SalesOrderSearchParameters.SortDirection), instance.SortDirection);

    }
}